package clb.core.channel.dto;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;
import java.util.List;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.validator.constraints.NotEmpty;

import com.hand.hap.core.annotation.Children;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import clb.core.core.annotation.SecurityField;
import clb.core.system.dto.ClbUser;

@ExtensionAttribute(disable=true)
@Table(name = "fms_cnl_channel")
public class CnlChannel extends BaseDTO {
    private static final long serialVersionUID = 1102817985863187350L;

    @Id
    @GeneratedValue
    private Long channelId;

    @NotEmpty
    private String channelCode;

    @NotEmpty
    private String channelName;

    private String contactPerson;

    @SecurityField
    private String phoneCode;

    @SecurityField
    private String contactPhone;

    private String email;

    private String province;

    private String city;

    @SecurityField
    private String address;

    private String channelTypeCode;

    private String industryBackground;

    private String experienceFlag;

    private String exhibitionMode;

    private String exhibitionRange;

    private String hkBank;

    private String hkBankAccountName;

    @SecurityField
    private String hkBankAccountNum;

    private String ilBank;

    private String ilBankAccountName;

    @SecurityField
    private String ilBankAccountNum;

    private String channelSource;

    private String statusCode;

    private String chineseName;

    private String englishName;

    private String certificateType;

    @SecurityField
    private String certificateNumber;

    private Long photoFileId;

    private Long programId;

    private Long requestId;

    private Date creationDate;

    @Transient
    private String area;

    @Transient
    private String provinceMeaning;

    @Transient
    private String cityMeaning;

    @Transient
    private String parentChannelName;

    @Transient
    private String contactPhoneComb;

    @Transient
    private String hkBankName;

    @Transient
    private String ilBankName;

    @Transient
    private Long userId;

    @Transient
    private String userName;

    @Transient
    private String userStatus;

    @Transient
    private String userStatusCode;

    @Transient
    private Long rateLevelId;

    @Transient
    private String rateLevelName;

    @Transient
    private String defineRateFlag;

    @Transient
    List<CnlContractRate> cnlChannelContractRate;

    @Transient
    private Long planCount;

    @Transient
    private Long reserveCount;

    @Transient
    private Long signCount;

    @Transient
    private Long pendingCount;

    @Transient
    private Long hkdAmount;

    @Transient
    private Long parentUserId;

    @Transient
    private Long parentChannelId;

    @Transient
    private Long parentSupplierId;

    @Transient
    private Date contractStartDate;

    @Transient
    private Date contractEndDate;

    @Transient
    private String photoFilePath;

    @Children
    @Transient
    private List<CnlChannelContact> cnlChannelContact;

    @Children
    @Transient
    private List<CnlChannelArchive> cnlChannelArchive;

    @Children
    @Transient
    private List<CnlChannelContract> cnlChannelContract;
    
    // 跟进数量（保险）
    @Transient
 	private Long insuranceInProcessQty;

 	// 跟进数量（债券）
    @Transient
 	private Long bondInProcessQty;

 	// 跟进数量（投资移民）
    @Transient
 	private Long immigrationInProcessQty;

 	// 跟进数量（基金）
    @Transient
 	private Long fundInProcessQty;

 	// 跟进数量（总量）
    @Transient
 	private Long totalInProcessQty;
    
    // 生效数量（全部跟进数量）
    @Transient
 	private Long allInProcessQty;
    
    // 生效数量（保险）
    @Transient
 	private Long insuranceInEffictiveQty;

 	// 生效数量（债券）
    @Transient
 	private Long bondInEffictiveQty;

 	// 生效数量（投资移民）
    @Transient
 	private Long immigrationInEffictiveQty;

 	// 生效数量（基金）
    @Transient
 	private Long fundInEffictiveQty;

 	// 生效数量（总量）
    @Transient
 	private Long totalInEffictiveQty;

    // 生效数量（总量）
    @Transient
 	private Long allInEffictiveQty;

 	// 签单数量
    @Transient
 	private Long signQty;
    
    // 签单数量(总量)
    @Transient
 	private Long allSignQty;
 	
 	// 签单金额
    @Transient
 	private BigDecimal signAmount;
    
    //签单总额
    @Transient
    private BigDecimal allSignAmount;

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public void setChannelId(Long channelId){
        this.channelId = channelId;
    }

    public Long getChannelId(){
        return channelId;
    }

    public void setChannelCode(String channelCode){
        this.channelCode = channelCode;
    }

    public String getChannelCode(){
        return channelCode;
    }

    public void setChannelName(String channelName){
        this.channelName = channelName;
    }

    public String getChannelName(){
        return channelName;
    }

    public void setContactPerson(String contactPerson){
        this.contactPerson = contactPerson;
    }

    public String getContactPerson(){
        return contactPerson;
    }

    public void setContactPhone(String contactPhone){
        this.contactPhone = contactPhone;
    }

    public String getContactPhone(){
        return contactPhone;
    }

    public void setProvince(String province){
        this.province = province;
    }

    public String getProvince(){
        return province;
    }

    public void setCity(String city){
        this.city = city;
    }

    public String getCity(){
        return city;
    }

    public void setAddress(String address){
        this.address = address;
    }

    public String getAddress(){
        return address;
    }

    public void setChannelTypeCode(String channelTypeCode){
        this.channelTypeCode = channelTypeCode;
    }

    public String getChannelTypeCode(){
        return channelTypeCode;
    }

    public void setIndustryBackground(String industryBackground){
        this.industryBackground = industryBackground;
    }

    public String getIndustryBackground(){
        return industryBackground;
    }

    public void setExperienceFlag(String experienceFlag){
        this.experienceFlag = experienceFlag;
    }

    public String getExperienceFlag(){
        return experienceFlag;
    }

    public void setExhibitionMode(String exhibitionMode){
        this.exhibitionMode = exhibitionMode;
    }

    public String getExhibitionMode(){
        return exhibitionMode;
    }

    public void setExhibitionRange(String exhibitionRange){
        this.exhibitionRange = exhibitionRange;
    }

    public String getExhibitionRange(){
        return exhibitionRange;
    }

    public void setHkBank(String hkBank){
        this.hkBank = hkBank;
    }

    public String getHkBank(){
        return hkBank;
    }

    public void setHkBankAccountName(String hkBankAccountName){
        this.hkBankAccountName = hkBankAccountName;
    }

    public String getHkBankAccountName(){
        return hkBankAccountName;
    }

    public void setHkBankAccountNum(String hkBankAccountNum){
        this.hkBankAccountNum = hkBankAccountNum;
    }

    public String getHkBankAccountNum(){
        return hkBankAccountNum;
    }

    public void setIlBank(String ilBank){
        this.ilBank = ilBank;
    }

    public String getIlBank(){
        return ilBank;
    }

    public void setIlBankAccountName(String ilBankAccountName){
        this.ilBankAccountName = ilBankAccountName;
    }

    public String getIlBankAccountName(){
        return ilBankAccountName;
    }

    public void setIlBankAccountNum(String ilBankAccountNum){
        this.ilBankAccountNum = ilBankAccountNum;
    }

    public String getIlBankAccountNum(){
        return ilBankAccountNum;
    }

    public String getChannelSource() {
        return channelSource;
    }

    public void setChannelSource(String channelSource) {
        this.channelSource = channelSource;
    }

    public void setStatusCode(String statusCode){
        this.statusCode = statusCode;
    }

    public String getStatusCode(){
        return statusCode;
    }

    public String getChineseName() {
        return chineseName;
    }

    public void setChineseName(String chineseName) {
        this.chineseName = chineseName;
    }

    public String getEnglishName() {
        return englishName;
    }

    public void setEnglishName(String englishName) {
        this.englishName = englishName;
    }

    public String getCertificateType() {
        return certificateType;
    }

    public void setCertificateType(String certificateType) {
        this.certificateType = certificateType;
    }

    public String getCertificateNumber() {
        return certificateNumber;
    }

    public void setCertificateNumber(String certificateNumber) {
        this.certificateNumber = certificateNumber;
    }

    public Long getPhotoFileId() {
        return photoFileId;
    }

    public void setPhotoFileId(Long photoFileId) {
        this.photoFileId = photoFileId;
    }

    public void setProgramId(Long programId){
        this.programId = programId;
    }

    public Long getProgramId(){
        return programId;
    }

    public void setRequestId(Long requestId){
        this.requestId = requestId;
    }

    public Long getRequestId(){
        return requestId;
    }

    public Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public String getArea() {
        return area;
    }

    public void setArea(String area) {
        this.area = area;
    }

    public List<CnlChannelContact> getCnlChannelContact() {
        return cnlChannelContact;
    }

    public void setCnlChannelContact(List<CnlChannelContact> cnlChannelContact) {
        this.cnlChannelContact = cnlChannelContact;
    }

    public List<CnlChannelArchive> getCnlChannelArchive() {
        return cnlChannelArchive;
    }

    public void setCnlChannelArchive(List<CnlChannelArchive> cnlChannelArchive) {
        this.cnlChannelArchive = cnlChannelArchive;
    }

    public List<CnlChannelContract> getCnlChannelContract() {
        return cnlChannelContract;
    }

    public void setCnlChannelContract(List<CnlChannelContract> cnlChannelContract) {
        this.cnlChannelContract = cnlChannelContract;
    }

    public String getProvinceMeaning() {
        return provinceMeaning;
    }

    public void setProvinceMeaning(String provinceMeaning) {
        this.provinceMeaning = provinceMeaning;
    }

    public String getCityMeaning() {
        return cityMeaning;
    }

    public void setCityMeaning(String cityMeaning) {
        this.cityMeaning = cityMeaning;
    }

    public String getParentChannelName() {
        return parentChannelName;
    }

    public void setParentChannelName(String parentChannelName) {
        this.parentChannelName = parentChannelName;
    }

    public String getPhoneCode() {
        return phoneCode;
    }

    public void setPhoneCode(String phoneCode) {
        this.phoneCode = phoneCode;
    }

    public String getContactPhoneComb() {
        return contactPhoneComb;
    }

    public void setContactPhoneComb(String contactPhoneComb) {
        this.contactPhoneComb = contactPhoneComb;
    }

    public String getHkBankName() {
        return hkBankName;
    }

    public void setHkBankName(String hkBankName) {
        this.hkBankName = hkBankName;
    }

    public String getIlBankName() {
        return ilBankName;
    }

    public void setIlBankName(String ilBankName) {
        this.ilBankName = ilBankName;
    }


    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserStatus() {
        return userStatus;
    }

    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus;
    }

    public String getUserStatusCode() {
        return userStatusCode;
    }

    public void setUserStatusCode(String userStatusCode) {
        this.userStatusCode = userStatusCode;
    }

    public Long getPlanCount() {
        return planCount;
    }

    public void setPlanCount(Long planCount) {
        this.planCount = planCount;
    }

    public Long getReserveCount() {
        return reserveCount;
    }

    public void setReserveCount(Long reserveCount) {
        this.reserveCount = reserveCount;
    }

    public Long getSignCount() {
        return signCount;
    }

    public void setSignCount(Long signCount) {
        this.signCount = signCount;
    }

    public Long getPendingCount() {
        return pendingCount;
    }

    public void setPendingCount(Long pendingCount) {
        this.pendingCount = pendingCount;
    }

    public Long getHkdAmount() {
        return hkdAmount;
    }

    public void setHkdAmount(Long hkdAmount) {
        this.hkdAmount = hkdAmount;
    }

    public Long getParentUserId() {
        return parentUserId;
    }

    public void setParentUserId(Long parentUserId) {
        this.parentUserId = parentUserId;
    }

    public Long getParentChannelId() {
        return parentChannelId;
    }

    public void setParentChannelId(Long parentChannelId) {
        this.parentChannelId = parentChannelId;
    }

    public Long getParentSupplierId() {
        return parentSupplierId;
    }

    public void setParentSupplierId(Long parentSupplierId) {
        this.parentSupplierId = parentSupplierId;
    }

    public Date getContractStartDate() {
        return contractStartDate;
    }

    public void setContractStartDate(Date contractStartDate) {
        this.contractStartDate = contractStartDate;
    }

    public Date getContractEndDate() {
        return contractEndDate;
    }

    public void setContractEndDate(Date contractEndDate) {
        this.contractEndDate = contractEndDate;
    }
    @Transient
    private ClbUser user;

	public ClbUser getUser() {
		return user;
	}

	public void setUser(ClbUser user) {
		this.user = user;
	}

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhotoFilePath() {
        return photoFilePath;
    }

    public void setPhotoFilePath(String photoFilePath) {
        this.photoFilePath = photoFilePath;
    }

    // 生效订单数
    @Transient
    private Long effectiveOrderQty;

	// 计划书额度
    @Transient
    private Long planQuota;

    // 订单总额HKD
    @Transient
    private Long orderAmountHKD;

    // 团队收益HKD
    @Transient
    private Long memberIncomeHKD;

    // 团队收益HKD
    @Transient
    private Long teamIncomeHKD;

    // 订单生效日期从
    @Transient
    private Date orderEffectiveDateFrom;

    // 订单生效日期至
    @Transient
    private Date orderEffectiveDateTo;
    
    // 订单生效日期至
    @Transient
    private List<SortParam> orderBy;

    public Date getOrderEffectiveDateFrom() {
        return orderEffectiveDateFrom;
    }

    public void setOrderEffectiveDateFrom(Date orderEffectiveDateFrom) {
        this.orderEffectiveDateFrom = orderEffectiveDateFrom;
    }

    public Date getOrderEffectiveDateTo() {
        return orderEffectiveDateTo;
    }

    public void setOrderEffectiveDateTo(Date orderEffectiveDateTo) {
        this.orderEffectiveDateTo = orderEffectiveDateTo;
    }

    public Long getEffectiveOrderQty() {
        return effectiveOrderQty;
    }

    public void setEffectiveOrderQty(Long effectiveOrderQty) {
        this.effectiveOrderQty = effectiveOrderQty;
    }

    public Long getPlanQuota() {
        return planQuota;
    }

    public void setPlanQuota(Long planQuota) {
        this.planQuota = planQuota;
    }

    public Long getOrderAmountHKD() {
        return orderAmountHKD;
    }

    public void setOrderAmountHKD(Long orderAmountHKD) {
        this.orderAmountHKD = orderAmountHKD;
    }

    public Long getMemberIncomeHKD() {
        return memberIncomeHKD;
    }

    public void setMemberIncomeHKD(Long memberIncomeHKD) {
        this.memberIncomeHKD = memberIncomeHKD;
    }

    public Long getTeamIncomeHKD() {
        return teamIncomeHKD;
    }

    public void setTeamIncomeHKD(Long teamIncomeHKD) {
        this.teamIncomeHKD = teamIncomeHKD;
    }

	public Long getInsuranceInProcessQty() {
		return insuranceInProcessQty;
	}

	public void setInsuranceInProcessQty(Long insuranceInProcessQty) {
		this.insuranceInProcessQty = insuranceInProcessQty;
	}

	public Long getBondInProcessQty() {
		return bondInProcessQty;
	}

	public void setBondInProcessQty(Long bondInProcessQty) {
		this.bondInProcessQty = bondInProcessQty;
	}

	public Long getImmigrationInProcessQty() {
		return immigrationInProcessQty;
	}

	public void setImmigrationInProcessQty(Long immigrationInProcessQty) {
		this.immigrationInProcessQty = immigrationInProcessQty;
	}

	public Long getFundInProcessQty() {
		return fundInProcessQty;
	}

	public void setFundInProcessQty(Long fundInProcessQty) {
		this.fundInProcessQty = fundInProcessQty;
	}

	public Long getTotalInProcessQty() {
		return totalInProcessQty;
	}

	public void setTotalInProcessQty(Long totalInProcessQty) {
		this.totalInProcessQty = totalInProcessQty;
	}

	public Long getInsuranceInEffictiveQty() {
		return insuranceInEffictiveQty;
	}

	public void setInsuranceInEffictiveQty(Long insuranceInEffictiveQty) {
		this.insuranceInEffictiveQty = insuranceInEffictiveQty;
	}

	public Long getBondInEffictiveQty() {
		return bondInEffictiveQty;
	}

	public void setBondInEffictiveQty(Long bondInEffictiveQty) {
		this.bondInEffictiveQty = bondInEffictiveQty;
	}

	public Long getImmigrationInEffictiveQty() {
		return immigrationInEffictiveQty;
	}

	public void setImmigrationInEffictiveQty(Long immigrationInEffictiveQty) {
		this.immigrationInEffictiveQty = immigrationInEffictiveQty;
	}

	public Long getFundInEffictiveQty() {
		return fundInEffictiveQty;
	}

	public void setFundInEffictiveQty(Long fundInEffictiveQty) {
		this.fundInEffictiveQty = fundInEffictiveQty;
	}

	public Long getTotalInEffictiveQty() {
		return totalInEffictiveQty;
	}

	public void setTotalInEffictiveQty(Long totalInEffictiveQty) {
		this.totalInEffictiveQty = totalInEffictiveQty;
	}

	public Long getSignQty() {
		return signQty;
	}

	public void setSignQty(Long signQty) {
		this.signQty = signQty;
	}

	

	public BigDecimal getSignAmount() {
		return signAmount;
	}

	public void setSignAmount(BigDecimal signAmount) {
		this.signAmount = signAmount;
	}

	public Long getAllInProcessQty() {
		return allInProcessQty;
	}

	public void setAllInProcessQty(Long allInProcessQty) {
		this.allInProcessQty = allInProcessQty;
	}

	public Long getAllInEffictiveQty() {
		return allInEffictiveQty;
	}

	public void setAllInEffictiveQty(Long allInEffictiveQty) {
		this.allInEffictiveQty = allInEffictiveQty;
	}

	public Long getAllSignQty() {
		return allSignQty;
	}

	public void setAllSignQty(Long allSignQty) {
		this.allSignQty = allSignQty;
	}

	public BigDecimal getAllSignAmount() {
		return allSignAmount;
	}

	public void setAllSignAmount(BigDecimal allSignAmount) {
		this.allSignAmount = allSignAmount;
	}

	public List<SortParam> getOrderBy() {
		return orderBy;
	}

	public void setOrderBy(List<SortParam> orderBy) {
		this.orderBy = orderBy;
	}

    public Long getRateLevelId() {
        return rateLevelId;
    }

    public void setRateLevelId(Long rateLevelId) {
        this.rateLevelId = rateLevelId;
    }

    public String getRateLevelName() {
        return rateLevelName;
    }

    public void setRateLevelName(String rateLevelName) {
        this.rateLevelName = rateLevelName;
    }

    public String getDefineRateFlag() {
        return defineRateFlag;
    }

    public void setDefineRateFlag(String defineRateFlag) {
        this.defineRateFlag = defineRateFlag;
    }

    public List<CnlContractRate> getCnlChannelContractRate() {
        return cnlChannelContractRate;
    }

    public void setCnlChannelContractRate(List<CnlContractRate> cnlChannelContractRate) {
        this.cnlChannelContractRate = cnlChannelContractRate;
    }
	
	
}
