package clb.core.channel.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;

import java.math.BigDecimal;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
@ExtensionAttribute(disable=true)
@Table(name = "fms_cnl_contract_rate")
public class CnlContractRate extends BaseDTO {
    private static final long serialVersionUID = 1796863896123395597L;

    @Id
    @GeneratedValue
    private Long channelRateId;

    @NotNull
    private Long channelContractId;

    private String specialDesc;

    private Long programId;

    private Long requestId;

    private String bigClass;

    private String midClass;

    private String minClass;

    private Long itemId;

    private Long sublineId;

    @Transient
    private String itemName;

    @Transient
    private String sublineItemName;

    @Transient
    private String bigClassDesc;

    @Transient
    private String midClassDesc;

    @Transient
    private String minClassDesc;


    private BigDecimal rate1;
    private BigDecimal rate2;
    private BigDecimal rate3;
    private BigDecimal rate4;
    private BigDecimal rate5;

    /*
     * 这五个字段用于查找渠道以及供应商的费率
     */
    //渠道分成ID
    @Transient
    private Long rateLevelId;
    //渠道级别名称
    @Transient
    private String rateLevelName;
    //供应商/渠道ID
    @Transient
    private Long partyId;
    //渠道分类
    @Transient
    private String channelTypeCode;
    //类型：CHANNEL OR SUPPLIER
    @Transient
    private String partyType;
    //自定义费率：Y OR N
    @Transient
    private String defineRateFlag;

    public BigDecimal getRate1() {
        return rate1;
    }

    public void setRate1(BigDecimal rate1) {
        this.rate1 = rate1;
    }

    public BigDecimal getRate2() {
        return rate2;
    }

    public void setRate2(BigDecimal rate2) {
        this.rate2 = rate2;
    }

    public BigDecimal getRate3() {
        return rate3;
    }

    public void setRate3(BigDecimal rate3) {
        this.rate3 = rate3;
    }

    public BigDecimal getRate4() {
        return rate4;
    }

    public void setRate4(BigDecimal rate4) {
        this.rate4 = rate4;
    }

    public BigDecimal getRate5() {
        return rate5;
    }

    public void setRate5(BigDecimal rate5) {
        this.rate5 = rate5;
    }

    public BigDecimal getRate6() {
        return rate6;
    }

    public void setRate6(BigDecimal rate6) {
        this.rate6 = rate6;
    }

    public BigDecimal getRate7() {
        return rate7;
    }

    public void setRate7(BigDecimal rate7) {
        this.rate7 = rate7;
    }

    public BigDecimal getRate8() {
        return rate8;
    }

    public void setRate8(BigDecimal rate8) {
        this.rate8 = rate8;
    }

    public BigDecimal getRate9() {
        return rate9;
    }

    public void setRate9(BigDecimal rate9) {
        this.rate9 = rate9;
    }

    public BigDecimal getRate10() {
        return rate10;
    }

    public void setRate10(BigDecimal rate10) {
        this.rate10 = rate10;
    }

    private BigDecimal rate6;
    private BigDecimal rate7;
    private BigDecimal rate8;
    private BigDecimal rate9;
    private BigDecimal rate10;

    private String performanceRequire;

    public void setChannelRateId(Long channelRateId){
        this.channelRateId = channelRateId;
    }

    public Long getChannelRateId(){
        return channelRateId;
    }

    public void setChannelContractId(Long channelContractId){
        this.channelContractId = channelContractId;
    }

    public Long getChannelContractId(){
        return channelContractId;
    }

    public void setSpecialDesc(String specialDesc){
        this.specialDesc = specialDesc;
    }

    public String getSpecialDesc(){
        return specialDesc;
    }

    public void setProgramId(Long programId){
        this.programId = programId;
    }

    public Long getProgramId(){
        return programId;
    }

    public void setRequestId(Long requestId){
        this.requestId = requestId;
    }

    public Long getRequestId(){
        return requestId;
    }

    public String getPerformanceRequire() {
        return performanceRequire;
    }

    public void setPerformanceRequire(String performanceRequire) {
        this.performanceRequire = performanceRequire;
    }

    public String getBigClass() {
        return bigClass;
    }

    public void setBigClass(String bigClass) {
        this.bigClass = bigClass;
    }

    public String getMidClass() {
        return midClass;
    }

    public void setMidClass(String midClass) {
        this.midClass = midClass;
    }

    public String getMinClass() {
        return minClass;
    }

    public void setMinClass(String minClass) {
        this.minClass = minClass;
    }

    public Long getItemId() {
        return itemId;
    }

    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    public Long getSublineId() {
        return sublineId;
    }

    public void setSublineId(Long sublineId) {
        this.sublineId = sublineId;
    }

    public String getItemName() { 
        return itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    public String getSublineItemName() {
        return sublineItemName;
    }

    public void setSublineItemName(String sublineItemName) {
        this.sublineItemName = sublineItemName;
    }

    public String getBigClassDesc() {
        return bigClassDesc;
    }

    public void setBigClassDesc(String bigClassDesc) {
        this.bigClassDesc = bigClassDesc;
    }

    public String getMidClassDesc() {
        return midClassDesc;
    }

    public void setMidClassDesc(String midClassDesc) {
        this.midClassDesc = midClassDesc;
    }

    public String getMinClassDesc() {
        return minClassDesc;
    }

    public void setMinClassDesc(String minClassDesc) {
        this.minClassDesc = minClassDesc;
    }

    public Long getRateLevelId() {
        return rateLevelId;
    }

    public void setRateLevelId(Long rateLevelId) {
        this.rateLevelId = rateLevelId;
    }

    public String getRateLevelName() {
        return rateLevelName;
    }

    public void setRateLevelName(String rateLevelName) {
        this.rateLevelName = rateLevelName;
    }

    public Long getPartyId() {
        return partyId;
    }

    public void setPartyId(Long partyId) {
        this.partyId = partyId;
    }

    public String getChannelTypeCode() {
        return channelTypeCode;
    }

    public void setChannelTypeCode(String channelTypeCode) {
        this.channelTypeCode = channelTypeCode;
    }

    public String getPartyType() {
        return partyType;
    }

    public void setPartyType(String partyType) {
        this.partyType = partyType;
    }

    public String getDefineRateFlag() {
        return defineRateFlag;
    }

    public void setDefineRateFlag(String defineRateFlag) {
        this.defineRateFlag = defineRateFlag;
    }
}
