package clb.core.channel.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;

import java.util.Date;

@ExtensionAttribute(disable=true)
@Table(name = "fms_cnl_contract_archive")
public class CnlContractArchive extends BaseDTO {
     @Id
     @GeneratedValue
      private Long contractArchiveId;

     @NotNull
      private Long channelContractId;

     @NotNull
      private Long fileId;

     @NotEmpty
      private String name;

      private String comments;

      private Long programId;

      private Long requestId;

    @Transient
    private Long fileSize;
    @Transient
    private Date uploadDate;
    @Transient
    private Long oldFileId;


     public void setContractArchiveId(Long contractArchiveId){
         this.contractArchiveId = contractArchiveId;
     }

     public Long getContractArchiveId(){
         return contractArchiveId;
     }

     public void setChannelContractId(Long channelContractId){
         this.channelContractId = channelContractId;
     }

     public Long getChannelContractId(){
         return channelContractId;
     }

     public void setFileId(Long fileId){
         this.fileId = fileId;
     }

     public Long getFileId(){
         return fileId;
     }

     public void setName(String name){
         this.name = name;
     }

     public String getName(){
         return name;
     }

     public void setComments(String comments){
         this.comments = comments;
     }

     public String getComments(){
         return comments;
     }

     public void setProgramId(Long programId){
         this.programId = programId;
     }

     public Long getProgramId(){
         return programId;
     }

     public void setRequestId(Long requestId){
         this.requestId = requestId;
     }

     public Long getRequestId(){
         return requestId;
     }

    public Long getFileSize() {
        return fileSize;
    }

    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    public Date getUploadDate() {
        return uploadDate;
    }

    public void setUploadDate(Date uploadDate) {
        this.uploadDate = uploadDate;
    }

    public Long getOldFileId() {
        return oldFileId;
    }

    public void setOldFileId(Long oldFileId) {
        this.oldFileId = oldFileId;
    }
}
