package clb.core.channel.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;

import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "fms_cnl_channel_archive")
public class CnlChannelArchive extends BaseDTO {
    @Id
    @GeneratedValue
    private Long channelArchiveId;

    @NotNull
    private Long channelId;

    @NotNull
    private Long fileId;

    @NotEmpty
    private String name;

    private String comments;

    private Long programId;

    private Long requestId;

    @Transient
    private Long fileSize;
    @Transient
    private Date uploadDate;
    @Transient
    private Long oldFileId;

    @Transient
    private String filePath;

    @Transient
    private String fileName;

    @Transient
    private String fileType;

    public void setChannelArchiveId(Long channelArchiveId){
        this.channelArchiveId = channelArchiveId;
    }

    public Long getChannelArchiveId(){
        return channelArchiveId;
    }

    public void setChannelId(Long channelId){
        this.channelId = channelId;
    }

    public Long getChannelId(){
        return channelId;
    }

    public void setFileId(Long fileId){
        this.fileId = fileId;
    }

    public Long getFileId(){
        return fileId;
    }

    public void setName(String name){
        this.name = name;
    }

    public String getName(){
        return name;
    }

    public void setComments(String comments){
        this.comments = comments;
    }

    public String getComments(){
        return comments;
    }

    public void setProgramId(Long programId){
        this.programId = programId;
    }

    public Long getProgramId(){
        return programId;
    }

    public void setRequestId(Long requestId){
        this.requestId = requestId;
    }

    public Long getRequestId(){
        return requestId;
    }

    public Long getFileSize() {
        return fileSize;
    }

    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    public Date getUploadDate() {
        return uploadDate;
    }

    public void setUploadDate(Date uploadDate) {
        this.uploadDate = uploadDate;
    }

    public Long getOldFileId() {
        return oldFileId;
    }

    public void setOldFileId(Long oldFileId) {
        this.oldFileId = oldFileId;
    }

    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getFileType() {
        return fileType;
    }

    public void setFileType(String fileType) {
        this.fileType = fileType;
    }
}
