package clb.core.channel.dto;

import javax.persistence.Column;
/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;

import java.math.BigDecimal;
import java.util.Date;
import org.hibernate.validator.constraints.NotEmpty;

@Table(name = "fms_cnl_level")
public class CnlLevel extends BaseDTO {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue
	@Column
	private Long id;

	@NotEmpty
	@Column
	private String channelClassCode;

	@NotEmpty
	@Column
	private String levelName;

	@NotEmpty
	@Column
	private BigDecimal theFirstYear;

	@NotEmpty
	@Column
	private BigDecimal theSecondYear;

	@NotEmpty
	@Column
	private BigDecimal theThirdTear;

	@NotEmpty
	@Column
	private BigDecimal theForthYear;

	@NotEmpty
	@Column
	private BigDecimal theFifthYear;

	@NotEmpty
	@Column
	private BigDecimal theSixthYear;

	@NotEmpty
	@Column
	private BigDecimal theSeventhYear;

	@NotEmpty
	@Column
	private BigDecimal theEightYear;

	@NotEmpty
	@Column
	private BigDecimal theNinthYear;

	@NotEmpty
	@Column
	private BigDecimal theTenthYear;

	@NotEmpty
	@Column
	private Long version;

	@NotEmpty
	@Column
	private Date effectiveStartDate;

	@NotEmpty
	@Column
	private Date effectiveEndDate;
	
	@NotEmpty
	@Column
	private Long supplierId;
	
	@Transient
	private String supplierCode;
	
	@Transient
	private String name;
	
	@Transient
	private Long maxVersion;
	
	@Transient
	private Long count;

	public Long getMaxVersion() {
		return maxVersion;
	}

	public void setMaxVersion(Long maxVersion) {
		this.maxVersion = maxVersion;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getId() {
		return id;
	}


	public String getChannelClassCode() {
		return channelClassCode;
	}

	public void setChannelClassCode(String channelClassCode) {
		this.channelClassCode = channelClassCode;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public String getLevelName() {
		return levelName;
	}

	public void setLevelName(String levelName) {
		this.levelName = levelName;
	}

	public BigDecimal getTheFirstYear() {
		return theFirstYear;
	}

	public void setTheFirstYear(BigDecimal theFirstYear) {
		this.theFirstYear = theFirstYear;
	}

	public BigDecimal getTheSecondYear() {
		return theSecondYear;
	}

	public void setTheSecondYear(BigDecimal theSecondYear) {
		this.theSecondYear = theSecondYear;
	}

	public BigDecimal getTheThirdTear() {
		return theThirdTear;
	}

	public void setTheThirdTear(BigDecimal theThirdTear) {
		this.theThirdTear = theThirdTear;
	}

	public BigDecimal getTheForthYear() {
		return theForthYear;
	}

	public void setTheForthYear(BigDecimal theForthYear) {
		this.theForthYear = theForthYear;
	}

	public BigDecimal getTheFifthYear() {
		return theFifthYear;
	}

	public void setTheFifthYear(BigDecimal theFifthYear) {
		this.theFifthYear = theFifthYear;
	}

	public BigDecimal getTheSixthYear() {
		return theSixthYear;
	}

	public void setTheSixthYear(BigDecimal theSixthYear) {
		this.theSixthYear = theSixthYear;
	}

	public BigDecimal getTheSeventhYear() {
		return theSeventhYear;
	}

	public void setTheSeventhYear(BigDecimal theSeventhYear) {
		this.theSeventhYear = theSeventhYear;
	}

	public BigDecimal getTheEightYear() {
		return theEightYear;
	}

	public void setTheEightYear(BigDecimal theEightYear) {
		this.theEightYear = theEightYear;
	}

	public BigDecimal getTheNinthYear() {
		return theNinthYear;
	}

	public void setTheNinthYear(BigDecimal theNinthYear) {
		this.theNinthYear = theNinthYear;
	}

	public BigDecimal getTheTenthYear() {
		return theTenthYear;
	}

	public void setTheTenthYear(BigDecimal theTenthYear) {
		this.theTenthYear = theTenthYear;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	public Long getVersion() {
		return version;
	}

	public void setEffectiveStartDate(Date effectiveStartDate) {
		this.effectiveStartDate = effectiveStartDate;
	}

	public Date getEffectiveStartDate() {
		return effectiveStartDate;
	}

	public void setEffectiveEndDate(Date effectiveEndDate) {
		this.effectiveEndDate = effectiveEndDate;
	}

	public Date getEffectiveEndDate() {
		return effectiveEndDate;
	}

	public Long getCount() {
		return count;
	}

	public void setCount(Long count) {
		this.count = count;
	}

	public static long getSerialVersionUID() {
		return serialVersionUID;
	}

	public Long getSupplierId() {
		return supplierId;
	}

	public void setSupplierId(Long supplierId) {
		this.supplierId = supplierId;
	}

	public String getSupplierCode() {
		return supplierCode;
	}

	public void setSupplierCode(String supplierCode) {
		this.supplierCode = supplierCode;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
}
