package clb.core.order.dto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.hand.hap.core.annotation.Children;
import com.hand.hap.mybatis.annotation.Condition;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;

import clb.core.core.annotation.SecurityField;

import javax.validation.constraints.NotNull;

import org.activiti.rest.common.util.DateToStringSerializer;
import org.hibernate.validator.constraints.NotEmpty;

@ExtensionAttribute(disable = true)
@Table(name = "fms_ord_after")
public class OrdAfter extends BaseDTO {

	@Id
	@GeneratedValue
	private Long afterId;

	@NotEmpty
	@Condition(operator = "LIKE")
	private String afterNum;

	@NotNull
	private Long orderId;

	@NotEmpty
	@Condition(operator = "LIKE")
	@Transient
	private String afterType;
	@Transient
	private String afterProject;
	
	private Long handlerUserId;
	@Transient
	private String handlerUserName;
	
	private Long templateId;
	@Transient
	private Long handlerName;

	private Long flag;

	@NotEmpty
	@Condition(operator = "LIKE")
	private String afterStatus;
	@Transient
	private String afterStatus1;
	
	
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	private Date creationDate;

	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	private Date lastUpdateDate;
	@Transient
	private String renewFlag;//续保成功的标识
	@Transient
	private String exitFlag;//退保成功的标识
	@Children
	@Transient
	private List<OrdAddition> ordAdditions;//附加险
	@Children
	@Transient
	private OrdAfter ordOrderInfo;//订单信息
	@Children
	@Transient
	private OrdOrder orderRenewalInfo;//续保信息
	@Children
	@Transient
	private List<OrdAfterFollow> ordAfterFollows;//跟进记录
	@Children
	@Transient
	private List<OrdOrderRenewal> ordOrderRenewals;//续保表格
	@Children
	@Transient
	private List<OrdAddition> ordOrderExit;//退保表格
	
	@Children
	@Transient
	private OrdAfterLog ordAfterLog;//售后状态为资料审核成功之后 弹窗数据
	
	@Children
	@Transient
	private OrdOrder orderRenewalSuccessInfo;//售后项目为续保 售后状态为成功之后 弹窗数据
	
	/*
	 * private Long programId;
	 * 
	 * private Long requestId;
	 */

	@Transient
	private String orderNumber;
	@Transient
	private String policyNumber;
	@Transient
	private String payNumber;
	@Transient
	private String customerNumber;
	@Transient
	private Long companyChannelId;
	@Transient
	private Long channelId;
	@Transient
	private Long contractRoleId;
	@Transient
	private Long productSupplierId;
	@Transient
	private Long itemId;
	@Transient
	private Long sublineId;

	@Transient
	private String currency;
	@Transient
	private String payMethod;
	@Transient
	private BigDecimal yearPayAmount;
	@Transient
	private BigDecimal policyAmount;
	@Transient
	private Long applicantCustomerId;
	@Transient
	private Long insurantCustomerId;
	@Transient
	private String increaseFlag;
	@Transient
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	private Date submitDate;
	@Transient
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	private Date reserveDate;
	@Transient
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	private Date reserveArrivalDate;
	@Transient
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	private Date reserveCheckDate;
	@Transient
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	private Date signDate;
	@Transient
	private Date effectiveDate;
	@Transient
	private Date approveDate;
	@Transient
	private Date expectCoolDate;
	@Transient
	private Date firstPayDate;
	@Transient
	private Date renewalDueDate;
	@Transient
	private Date graceDate;
	@Transient
	private Date administrativeDate;
	@Transient
	private String status;
	@Transient
	private String clubConfirmStatus;
	@Transient
	private String customerConfirmStatus;
	@Transient
	private String applicationStatus;
	@Transient
	private Long customerUserId;
	@Transient
	private String smsFlag;
	@Transient
	private Date customerOperateDate;
	@Transient
	private String hkContactPerson;
	@Transient
	private String hkContactPhone;
	@Transient
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	private Date receiptDate;
	@Transient
	private String quickCheckFlag;
	@Transient
	private String eleInsuranceFlag;
	@Transient
	private Long fillUserId;
	@Transient
	private String signAssistant;
	@Transient
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	private Date arrivalDate;
	@Transient
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	private Date leaveDate;
	@Transient
	private String phoneFlag;
	@Transient
	private String contactPerson;
	@Transient
	private String contactPhone;
	@Transient
	private String signAddress;
	@Transient
	private String meetAddress;
	@Transient
	private Long reserveSupplierId;
	@Transient
	private String reserveComment;
	@Transient
	private Long reserveUserId;
	@Transient
	private Long signSupplierId;
	@Transient
	private String signPerson;
	@Transient
	private String expressDeliveryInfo;
	@Transient
	private Long receptionUserId;
	@Transient
	private String reviewer1;
	@Transient
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	private Date reviewer1Date;
	@Transient
	private String reviewer2;
	@Transient
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	private Date reviewer2Date;
	@Transient
	private String reviewerComment;
	@Transient
	private String sendStatus;
	@Transient
	private Long sendUserId;
	@Transient
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	private Date sendDate;
	@Transient
	private Long planFileId;
	@Transient
	private Long reqFileId;
	@Transient
	private BigDecimal nextPolicyAmount;
	@Transient
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	private Date nextPolicyDueDate;
	@Transient
	private String firstPaymentMethod;
	@Transient
	private String renewalPaymentMethod;
	@Transient
	private String renewalOther;
	@Transient
	private String ddaFlag;
	@Transient
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	private Date ddaSubmitDate;
	@Transient
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	private Date ddaEffectiveDate;
	@Transient
	private BigDecimal feedbackBalance;
	@Transient
	private BigDecimal accountBalance;

	@Transient
	private String item;

	@Transient
	private String roleName;

	@Transient
	private String companyChannelName;

	@Transient
	private String channelName;

	@Transient
	private String applicant;

	@Transient
	private String insurant;

	@Transient
	private String signSupplierName;

	@Transient
	private String person;

	@Transient
	private String number;

	@Transient
	private String dateType;

	@Transient
	private String hisStatus;

	@Transient
	private String hisDesc;

	@Transient
	@JsonFormat(pattern = "yyyy-MM-dd")
	//@JsonSerialize(using = DateToStringSerializer.class, as = Date.class)
	private Date startDateActive;// 开始日期

	@Transient
	@JsonFormat(pattern = "yyyy-MM-dd")
	//@JsonSerialize(using = DateToStringSerializer.class, as = Date.class)
	private Date endDateActive;// 结束日期

	@Children
	@Transient
	private List<OrdAddition> ordAddition;

	@Children
	@Transient
	private List<OrdBeneficiary> ordBeneficiary;

	@Transient
	private Long oldPlanFileId;

	@Transient
	private Long oldReqFileId;

	@Transient
	private String planToken;

	@Transient
	private String reqToken;

	@Transient
	private String reserveSupplierName;

	@Transient
	private String orderInfo;

	@Transient
	private String customerEmployeeName;

	@Transient
	private String fillEmployeeName;

	@Transient
	private String sendEmployeeName;

	@Transient
	private Long channelCommissionLineId;

	@Transient
	private String ownSupplierName;

	@Transient
	private String middleSupplierName;

	@Transient
	private String insuranceSupplierName;

	@Transient
	private String statusDesc;

	@Transient
	private String sublineItemName;
	@Transient
	private String balanceCurrency;
	@Transient
	private String balancePaymentMethod;
	@Transient
	private Long payPeriods;

	@Transient
	private Long afterFollowId;

	@Transient
	private Long followUserId;
	@Transient
	private Date followDate;

	@Transient
	private String content;
	@Transient
	private Long fileId;

	@Transient
	private String userName;
	
    @Transient
    @JsonFormat(pattern="yyyy-MM-dd")
    @JsonSerialize(using = DateToStringSerializer.class, as = Date.class)
    private Date insurantBirthDate;

    @Transient
    private Long trChannelCount;

    @Transient
    private Long trSupplierCount;

    @Transient
    private Long parentChannelId;

    @Transient
    private String functionCode;
    
    @Transient
    private String renewalStatus;
    
    @Transient
    private String afterTypeDesc;
    
    @Transient
	private String afterProjectDesc;
    
    @Transient
	private String afterStatusDesc;
    
    @Transient
    private Long channelContractId;//一级渠道与所属供应商合约
    
    @Transient
    @SecurityField
    private String channelPhoneCode;

    @Transient
    @SecurityField
    private String channelPhone;
    
    @Transient
	private Long  companyFileid;//产品公司的图片ID
    
    @Transient
    private String  preName;//对接业务行政
    
    @Transient
    private String  stairSell;//所属一级
    
	public String getAfterTypeDesc() {
		return afterTypeDesc;
	}

	public void setAfterTypeDesc(String afterTypeDesc) {
		this.afterTypeDesc = afterTypeDesc;
	}

	public String getAfterProjectDesc() {
		return afterProjectDesc;
	}

	public void setAfterProjectDesc(String afterProjectDesc) {
		this.afterProjectDesc = afterProjectDesc;
	}

	public String getAfterStatusDesc() {
		return afterStatusDesc;
	}

	public void setAfterStatusDesc(String afterStatusDesc) {
		this.afterStatusDesc = afterStatusDesc;
	}

	public String getRenewalStatus() {
		return renewalStatus;
	}

	public void setRenewalStatus(String renewalStatus) {
		this.renewalStatus = renewalStatus;
	}

	public Date getInsurantBirthDate() {
		return insurantBirthDate;
	}

	public void setInsurantBirthDate(Date insurantBirthDate) {
		this.insurantBirthDate = insurantBirthDate;
	}

	public Long getTrChannelCount() {
		return trChannelCount;
	}

	public void setTrChannelCount(Long trChannelCount) {
		this.trChannelCount = trChannelCount;
	}

	public Long getTrSupplierCount() {
		return trSupplierCount;
	}

	public void setTrSupplierCount(Long trSupplierCount) {
		this.trSupplierCount = trSupplierCount;
	}

	public Long getParentChannelId() {
		return parentChannelId;
	}

	public void setParentChannelId(Long parentChannelId) {
		this.parentChannelId = parentChannelId;
	}

	public String getFunctionCode() {
		return functionCode;
	}

	public void setFunctionCode(String functionCode) {
		this.functionCode = functionCode;
	}

	public List<OrdOrderRenewal> getOrdOrderRenewals() {
		return ordOrderRenewals;
	}

	public void setOrdOrderRenewals(List<OrdOrderRenewal> ordOrderRenewals) {
		this.ordOrderRenewals = ordOrderRenewals;
	}

	public Long getAfterFollowId() {
		return afterFollowId;
	}

	public void setAfterFollowId(Long afterFollowId) {
		this.afterFollowId = afterFollowId;
	}

	public Long getFollowUserId() {
		return followUserId;
	}

	public void setFollowUserId(Long followUserId) {
		this.followUserId = followUserId;
	}

	public Date getFollowDate() {
		return followDate;
	}

	public void setFollowDate(Date followDate) {
		this.followDate = followDate;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Long getFileId() {
		return fileId;
	}

	public void setFileId(Long fileId) {
		this.fileId = fileId;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public OrdAfter getOrdOrderInfo() {
		return ordOrderInfo;
	}

	public void setOrdOrderInfo(OrdAfter ordOrderInfo) {
		this.ordOrderInfo = ordOrderInfo;
	}

	public OrdOrder getOrderRenewalInfo() {
		return orderRenewalInfo;
	}

	public void setOrderRenewalInfo(OrdOrder orderRenewalInfo) {
		this.orderRenewalInfo = orderRenewalInfo;
	}

	public List<OrdAfterFollow> getOrdAfterFollows() {
		return ordAfterFollows;
	}

	public void setOrdAfterFollows(List<OrdAfterFollow> ordAfterFollows) {
		this.ordAfterFollows = ordAfterFollows;
	}

	public List<OrdAddition> getOrdAdditions() {
		return ordAdditions;
	}

	public void setOrdAdditions(List<OrdAddition> ordAdditions) {
		this.ordAdditions = ordAdditions;
	}

	public Long getPayPeriods() {
		return payPeriods;
	}

	public void setPayPeriods(Long payPeriods) {
		this.payPeriods = payPeriods;
	}

	public Date getLastUpdateDate() {
		return lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public String getBalanceCurrency() {
		return balanceCurrency;
	}

	public void setBalanceCurrency(String balanceCurrency) {
		this.balanceCurrency = balanceCurrency;
	}

	public String getBalancePaymentMethod() {
		return balancePaymentMethod;
	}

	public void setBalancePaymentMethod(String balancePaymentMethod) {
		this.balancePaymentMethod = balancePaymentMethod;
	}

	public String getItem() {
		return item;
	}

	public void setItem(String item) {
		this.item = item;
	}

	public String getRoleName() {
		return roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getCompanyChannelName() {
		return companyChannelName;
	}

	public void setCompanyChannelName(String companyChannelName) {
		this.companyChannelName = companyChannelName;
	}

	public String getChannelName() {
		return channelName;
	}

	public void setChannelName(String channelName) {
		this.channelName = channelName;
	}

	public String getApplicant() {
		return applicant;
	}

	public void setApplicant(String applicant) {
		this.applicant = applicant;
	}

	public String getInsurant() {
		return insurant;
	}

	public void setInsurant(String insurant) {
		this.insurant = insurant;
	}

	public String getSignSupplierName() {
		return signSupplierName;
	}

	public void setSignSupplierName(String signSupplierName) {
		this.signSupplierName = signSupplierName;
	}

	public String getPerson() {
		return person;
	}

	public void setPerson(String person) {
		this.person = person;
	}

	public String getNumber() {
		return number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public String getDateType() {
		return dateType;
	}

	public void setDateType(String dateType) {
		this.dateType = dateType;
	}

	public String getHisStatus() {
		return hisStatus;
	}

	public void setHisStatus(String hisStatus) {
		this.hisStatus = hisStatus;
	}

	public String getHisDesc() {
		return hisDesc;
	}

	public void setHisDesc(String hisDesc) {
		this.hisDesc = hisDesc;
	}

	public Date getStartDateActive() {
		return startDateActive;
	}

	public void setStartDateActive(Date startDateActive) {
		this.startDateActive = startDateActive;
	}

	public Date getEndDateActive() {
		return endDateActive;
	}

	public void setEndDateActive(Date endDateActive) {
		this.endDateActive = endDateActive;
	}

	public List<OrdAddition> getOrdAddition() {
		return ordAddition;
	}

	public void setOrdAddition(List<OrdAddition> ordAddition) {
		this.ordAddition = ordAddition;
	}

	public List<OrdBeneficiary> getOrdBeneficiary() {
		return ordBeneficiary;
	}

	public void setOrdBeneficiary(List<OrdBeneficiary> ordBeneficiary) {
		this.ordBeneficiary = ordBeneficiary;
	}

	public Long getOldPlanFileId() {
		return oldPlanFileId;
	}

	public void setOldPlanFileId(Long oldPlanFileId) {
		this.oldPlanFileId = oldPlanFileId;
	}

	public Long getOldReqFileId() {
		return oldReqFileId;
	}

	public void setOldReqFileId(Long oldReqFileId) {
		this.oldReqFileId = oldReqFileId;
	}

	public String getPlanToken() {
		return planToken;
	}

	public void setPlanToken(String planToken) {
		this.planToken = planToken;
	}

	public String getReqToken() {
		return reqToken;
	}

	public void setReqToken(String reqToken) {
		this.reqToken = reqToken;
	}

	public String getReserveSupplierName() {
		return reserveSupplierName;
	}

	public void setReserveSupplierName(String reserveSupplierName) {
		this.reserveSupplierName = reserveSupplierName;
	}

	public String getOrderInfo() {
		return orderInfo;
	}

	public void setOrderInfo(String orderInfo) {
		this.orderInfo = orderInfo;
	}

	public String getCustomerEmployeeName() {
		return customerEmployeeName;
	}

	public void setCustomerEmployeeName(String customerEmployeeName) {
		this.customerEmployeeName = customerEmployeeName;
	}

	public String getFillEmployeeName() {
		return fillEmployeeName;
	}

	public void setFillEmployeeName(String fillEmployeeName) {
		this.fillEmployeeName = fillEmployeeName;
	}

	public String getSendEmployeeName() {
		return sendEmployeeName;
	}

	public void setSendEmployeeName(String sendEmployeeName) {
		this.sendEmployeeName = sendEmployeeName;
	}

	public Long getChannelCommissionLineId() {
		return channelCommissionLineId;
	}

	public void setChannelCommissionLineId(Long channelCommissionLineId) {
		this.channelCommissionLineId = channelCommissionLineId;
	}

	public String getOwnSupplierName() {
		return ownSupplierName;
	}

	public void setOwnSupplierName(String ownSupplierName) {
		this.ownSupplierName = ownSupplierName;
	}

	public String getMiddleSupplierName() {
		return middleSupplierName;
	}

	public void setMiddleSupplierName(String middleSupplierName) {
		this.middleSupplierName = middleSupplierName;
	}

	public String getInsuranceSupplierName() {
		return insuranceSupplierName;
	}

	public void setInsuranceSupplierName(String insuranceSupplierName) {
		this.insuranceSupplierName = insuranceSupplierName;
	}

	public String getStatusDesc() {
		return statusDesc;
	}

	public void setStatusDesc(String statusDesc) {
		this.statusDesc = statusDesc;
	}

	public String getSublineItemName() {
		return sublineItemName;
	}

	public void setSublineItemName(String sublineItemName) {
		this.sublineItemName = sublineItemName;
	}

	public String getAfterNum() {
		return afterNum;
	}

	public void setAfterNum(String afterNum) {
		this.afterNum = afterNum;
	}

	public void setAfterId(Long afterId) {
		this.afterId = afterId;
	}

	public Long getAfterId() {
		return afterId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	public Long getOrderId() {
		return orderId;
	}

	public void setAfterType(String afterType) {
		this.afterType = afterType;
	}

	public String getAfterType() {
		return afterType;
	}

	public void setAfterStatus(String afterStatus) {
		this.afterStatus = afterStatus;
	}

	public String getAfterStatus() {
		return afterStatus;
	}

	/*
	 * public void setProgramId(Long programId) { this.programId = programId; }
	 * 
	 * public Long getProgramId() { return programId; }
	 * 
	 * public void setRequestId(Long requestId) { this.requestId = requestId; }
	 * 
	 * public Long getRequestId() { return requestId; }
	 */
	public String getAfterProject() {
		return afterProject;
	}

	public void setAfterProject(String afterProject) {
		this.afterProject = afterProject;
	}

	public Long getFlag() {
		return flag;
	}

	public void setFlag(Long flag) {
		this.flag = flag;
	}

	public String getOrderNumber() {
		return orderNumber;
	}

	public void setOrderNumber(String orderNumber) {
		this.orderNumber = orderNumber;
	}

	public String getPolicyNumber() {
		return policyNumber;
	}

	public void setPolicyNumber(String policyNumber) {
		this.policyNumber = policyNumber;
	}

	public String getPayNumber() {
		return payNumber;
	}

	public void setPayNumber(String payNumber) {
		this.payNumber = payNumber;
	}

	public String getCustomerNumber() {
		return customerNumber;
	}

	public void setCustomerNumber(String customerNumber) {
		this.customerNumber = customerNumber;
	}

	public Long getCompanyChannelId() {
		return companyChannelId;
	}

	public void setCompanyChannelId(Long companyChannelId) {
		this.companyChannelId = companyChannelId;
	}

	public Long getChannelId() {
		return channelId;
	}

	public void setChannelId(Long channelId) {
		this.channelId = channelId;
	}

	public Long getContractRoleId() {
		return contractRoleId;
	}

	public void setContractRoleId(Long contractRoleId) {
		this.contractRoleId = contractRoleId;
	}

	public Long getProductSupplierId() {
		return productSupplierId;
	}

	public void setProductSupplierId(Long productSupplierId) {
		this.productSupplierId = productSupplierId;
	}

	public Long getItemId() {
		return itemId;
	}

	public void setItemId(Long itemId) {
		this.itemId = itemId;
	}

	public Long getSublineId() {
		return sublineId;
	}

	public void setSublineId(Long sublineId) {
		this.sublineId = sublineId;
	}

	public String getCurrency() {
		return currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public String getPayMethod() {
		return payMethod;
	}

	public void setPayMethod(String payMethod) {
		this.payMethod = payMethod;
	}

	public BigDecimal getYearPayAmount() {
		return yearPayAmount;
	}

	public void setYearPayAmount(BigDecimal yearPayAmount) {
		this.yearPayAmount = yearPayAmount;
	}

	public BigDecimal getPolicyAmount() {
		return policyAmount;
	}

	public void setPolicyAmount(BigDecimal policyAmount) {
		this.policyAmount = policyAmount;
	}

	public Long getApplicantCustomerId() {
		return applicantCustomerId;
	}

	public void setApplicantCustomerId(Long applicantCustomerId) {
		this.applicantCustomerId = applicantCustomerId;
	}

	public Long getInsurantCustomerId() {
		return insurantCustomerId;
	}

	public void setInsurantCustomerId(Long insurantCustomerId) {
		this.insurantCustomerId = insurantCustomerId;
	}

	public String getIncreaseFlag() {
		return increaseFlag;
	}

	public void setIncreaseFlag(String increaseFlag) {
		this.increaseFlag = increaseFlag;
	}

	public Date getSubmitDate() {
		return submitDate;
	}

	public void setSubmitDate(Date submitDate) {
		this.submitDate = submitDate;
	}

	public Date getReserveDate() {
		return reserveDate;
	}

	public void setReserveDate(Date reserveDate) {
		this.reserveDate = reserveDate;
	}

	public Date getReserveArrivalDate() {
		return reserveArrivalDate;
	}

	public void setReserveArrivalDate(Date reserveArrivalDate) {
		this.reserveArrivalDate = reserveArrivalDate;
	}

	public Date getReserveCheckDate() {
		return reserveCheckDate;
	}

	public void setReserveCheckDate(Date reserveCheckDate) {
		this.reserveCheckDate = reserveCheckDate;
	}

	public Date getSignDate() {
		return signDate;
	}

	public void setSignDate(Date signDate) {
		this.signDate = signDate;
	}

	public Date getEffectiveDate() {
		return effectiveDate;
	}

	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	public Date getApproveDate() {
		return approveDate;
	}

	public void setApproveDate(Date approveDate) {
		this.approveDate = approveDate;
	}

	public Date getExpectCoolDate() {
		return expectCoolDate;
	}

	public void setExpectCoolDate(Date expectCoolDate) {
		this.expectCoolDate = expectCoolDate;
	}

	public Date getFirstPayDate() {
		return firstPayDate;
	}

	public void setFirstPayDate(Date firstPayDate) {
		this.firstPayDate = firstPayDate;
	}

	public Date getRenewalDueDate() {
		return renewalDueDate;
	}

	public void setRenewalDueDate(Date renewalDueDate) {
		this.renewalDueDate = renewalDueDate;
	}

	public Date getGraceDate() {
		return graceDate;
	}

	public void setGraceDate(Date graceDate) {
		this.graceDate = graceDate;
	}

	public Date getAdministrativeDate() {
		return administrativeDate;
	}

	public void setAdministrativeDate(Date administrativeDate) {
		this.administrativeDate = administrativeDate;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getClubConfirmStatus() {
		return clubConfirmStatus;
	}

	public void setClubConfirmStatus(String clubConfirmStatus) {
		this.clubConfirmStatus = clubConfirmStatus;
	}

	public String getCustomerConfirmStatus() {
		return customerConfirmStatus;
	}

	public void setCustomerConfirmStatus(String customerConfirmStatus) {
		this.customerConfirmStatus = customerConfirmStatus;
	}

	public String getApplicationStatus() {
		return applicationStatus;
	}

	public void setApplicationStatus(String applicationStatus) {
		this.applicationStatus = applicationStatus;
	}

	public Long getCustomerUserId() {
		return customerUserId;
	}

	public void setCustomerUserId(Long customerUserId) {
		this.customerUserId = customerUserId;
	}

	public String getSmsFlag() {
		return smsFlag;
	}

	public void setSmsFlag(String smsFlag) {
		this.smsFlag = smsFlag;
	}

	public Date getCustomerOperateDate() {
		return customerOperateDate;
	}

	public void setCustomerOperateDate(Date customerOperateDate) {
		this.customerOperateDate = customerOperateDate;
	}

	public String getHkContactPerson() {
		return hkContactPerson;
	}

	public void setHkContactPerson(String hkContactPerson) {
		this.hkContactPerson = hkContactPerson;
	}

	public String getHkContactPhone() {
		return hkContactPhone;
	}

	public void setHkContactPhone(String hkContactPhone) {
		this.hkContactPhone = hkContactPhone;
	}

	public Date getReceiptDate() {
		return receiptDate;
	}

	public void setReceiptDate(Date receiptDate) {
		this.receiptDate = receiptDate;
	}

	public String getQuickCheckFlag() {
		return quickCheckFlag;
	}

	public void setQuickCheckFlag(String quickCheckFlag) {
		this.quickCheckFlag = quickCheckFlag;
	}

	public String getEleInsuranceFlag() {
		return eleInsuranceFlag;
	}

	public void setEleInsuranceFlag(String eleInsuranceFlag) {
		this.eleInsuranceFlag = eleInsuranceFlag;
	}

	public Long getFillUserId() {
		return fillUserId;
	}

	public void setFillUserId(Long fillUserId) {
		this.fillUserId = fillUserId;
	}

	public String getSignAssistant() {
		return signAssistant;
	}

	public void setSignAssistant(String signAssistant) {
		this.signAssistant = signAssistant;
	}

	public Date getArrivalDate() {
		return arrivalDate;
	}

	public void setArrivalDate(Date arrivalDate) {
		this.arrivalDate = arrivalDate;
	}

	public Date getLeaveDate() {
		return leaveDate;
	}

	public void setLeaveDate(Date leaveDate) {
		this.leaveDate = leaveDate;
	}

	public String getPhoneFlag() {
		return phoneFlag;
	}

	public void setPhoneFlag(String phoneFlag) {
		this.phoneFlag = phoneFlag;
	}

	public String getContactPerson() {
		return contactPerson;
	}

	public void setContactPerson(String contactPerson) {
		this.contactPerson = contactPerson;
	}

	public String getContactPhone() {
		return contactPhone;
	}

	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone;
	}

	public String getSignAddress() {
		return signAddress;
	}

	public void setSignAddress(String signAddress) {
		this.signAddress = signAddress;
	}

	public String getMeetAddress() {
		return meetAddress;
	}

	public void setMeetAddress(String meetAddress) {
		this.meetAddress = meetAddress;
	}

	public Long getReserveSupplierId() {
		return reserveSupplierId;
	}

	public void setReserveSupplierId(Long reserveSupplierId) {
		this.reserveSupplierId = reserveSupplierId;
	}

	public String getReserveComment() {
		return reserveComment;
	}

	public void setReserveComment(String reserveComment) {
		this.reserveComment = reserveComment;
	}

	public Long getReserveUserId() {
		return reserveUserId;
	}

	public void setReserveUserId(Long reserveUserId) {
		this.reserveUserId = reserveUserId;
	}

	public Long getSignSupplierId() {
		return signSupplierId;
	}

	public void setSignSupplierId(Long signSupplierId) {
		this.signSupplierId = signSupplierId;
	}

	public String getSignPerson() {
		return signPerson;
	}

	public void setSignPerson(String signPerson) {
		this.signPerson = signPerson;
	}

	public String getExpressDeliveryInfo() {
		return expressDeliveryInfo;
	}

	public void setExpressDeliveryInfo(String expressDeliveryInfo) {
		this.expressDeliveryInfo = expressDeliveryInfo;
	}

	public Long getReceptionUserId() {
		return receptionUserId;
	}

	public void setReceptionUserId(Long receptionUserId) {
		this.receptionUserId = receptionUserId;
	}

	public String getReviewer1() {
		return reviewer1;
	}

	public void setReviewer1(String reviewer1) {
		this.reviewer1 = reviewer1;
	}

	public Date getReviewer1Date() {
		return reviewer1Date;
	}

	public void setReviewer1Date(Date reviewer1Date) {
		this.reviewer1Date = reviewer1Date;
	}

	public String getReviewer2() {
		return reviewer2;
	}

	public void setReviewer2(String reviewer2) {
		this.reviewer2 = reviewer2;
	}

	public Date getReviewer2Date() {
		return reviewer2Date;
	}

	public void setReviewer2Date(Date reviewer2Date) {
		this.reviewer2Date = reviewer2Date;
	}

	public String getReviewerComment() {
		return reviewerComment;
	}

	public void setReviewerComment(String reviewerComment) {
		this.reviewerComment = reviewerComment;
	}

	public String getSendStatus() {
		return sendStatus;
	}

	public void setSendStatus(String sendStatus) {
		this.sendStatus = sendStatus;
	}

	public Long getSendUserId() {
		return sendUserId;
	}

	public void setSendUserId(Long sendUserId) {
		this.sendUserId = sendUserId;
	}

	public Date getSendDate() {
		return sendDate;
	}

	public void setSendDate(Date sendDate) {
		this.sendDate = sendDate;
	}

	public Long getPlanFileId() {
		return planFileId;
	}

	public void setPlanFileId(Long planFileId) {
		this.planFileId = planFileId;
	}

	public Long getTemplateId() {
		return templateId;
	}

	public void setTemplateId(Long templateId) {
		this.templateId = templateId;
	}

	public Long getReqFileId() {
		return reqFileId;
	}

	public void setReqFileId(Long reqFileId) {
		this.reqFileId = reqFileId;
	}

	public BigDecimal getNextPolicyAmount() {
		return nextPolicyAmount;
	}

	public void setNextPolicyAmount(BigDecimal nextPolicyAmount) {
		this.nextPolicyAmount = nextPolicyAmount;
	}

	public Date getNextPolicyDueDate() {
		return nextPolicyDueDate;
	}

	public void setNextPolicyDueDate(Date nextPolicyDueDate) {
		this.nextPolicyDueDate = nextPolicyDueDate;
	}

	public String getFirstPaymentMethod() {
		return firstPaymentMethod;
	}

	public void setFirstPaymentMethod(String firstPaymentMethod) {
		this.firstPaymentMethod = firstPaymentMethod;
	}

	public String getRenewalPaymentMethod() {
		return renewalPaymentMethod;
	}

	public void setRenewalPaymentMethod(String renewalPaymentMethod) {
		this.renewalPaymentMethod = renewalPaymentMethod;
	}

	public String getRenewalOther() {
		return renewalOther;
	}

	public void setRenewalOther(String renewalOther) {
		this.renewalOther = renewalOther;
	}

	public String getDdaFlag() {
		return ddaFlag;
	}

	public void setDdaFlag(String ddaFlag) {
		this.ddaFlag = ddaFlag;
	}

	public Date getDdaSubmitDate() {
		return ddaSubmitDate;
	}

	public void setDdaSubmitDate(Date ddaSubmitDate) {
		this.ddaSubmitDate = ddaSubmitDate;
	}

	public BigDecimal getFeedbackBalance() {
		return feedbackBalance;
	}

	public void setFeedbackBalance(BigDecimal feedbackBalance) {
		this.feedbackBalance = feedbackBalance;
	}

	public BigDecimal getAccountBalance() {
		return accountBalance;
	}

	public void setAccountBalance(BigDecimal accountBalance) {
		this.accountBalance = accountBalance;
	}

	public Date getCreationDate() {
		return creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Date getDdaEffectiveDate() {
		return ddaEffectiveDate;
	}

	public void setDdaEffectiveDate(Date ddaEffectiveDate) {
		this.ddaEffectiveDate = ddaEffectiveDate;
	}

	public List<OrdAddition> getOrdOrderExit() {
		return ordOrderExit;
	}

	public void setOrdOrderExit(List<OrdAddition> ordOrderExit) {
		this.ordOrderExit = ordOrderExit;
	}

	public Long getHandlerUserId() {
		return handlerUserId;
	}

	public void setHandlerUserId(Long handlerUserId) {
		this.handlerUserId = handlerUserId;
	}

	public Long getHandlerName() {
		return handlerName;
	}

	public void setHandlerName(Long handlerName) {
		this.handlerName = handlerName;
	}

	public String getAfterStatus1() {
		return afterStatus1;
	}

	public void setAfterStatus1(String afterStatus1) {
		this.afterStatus1 = afterStatus1;
	}

	public String getRenewFlag() {
		return renewFlag;
	}

	public void setRenewFlag(String renewFlag) {
		this.renewFlag = renewFlag;
	}

	public String getExitFlag() {
		return exitFlag;
	}

	public void setExitFlag(String exitFlag) {
		this.exitFlag = exitFlag;
	}

	public String getHandlerUserName() {
		return handlerUserName;
	}

	public void setHandlerUserName(String handlerUserName) {
		this.handlerUserName = handlerUserName;
	}

	public Long getChannelContractId() {
		return channelContractId;
	}

	public void setChannelContractId(Long channelContractId) {
		this.channelContractId = channelContractId;
	}

	public String getChannelPhoneCode() {
		return channelPhoneCode;
	}

	public void setChannelPhoneCode(String channelPhoneCode) {
		this.channelPhoneCode = channelPhoneCode;
	}

	public String getChannelPhone() {
		return channelPhone;
	}

	public void setChannelPhone(String channelPhone) {
		this.channelPhone = channelPhone;
	}

	public Long getCompanyFileid() {
		return companyFileid;
	}

	public void setCompanyFileid(Long companyFileid) {
		this.companyFileid = companyFileid;
	}

	public String getPreName() {
		return preName;
	}

	public void setPreName(String preName) {
		this.preName = preName;
	}

	public String getStairSell() {
		return stairSell;
	}

	public void setStairSell(String stairSell) {
		this.stairSell = stairSell;
	}

	public OrdAfterLog getOrdAfterLog() {
		return ordAfterLog;
	}

	public void setOrdAfterLog(OrdAfterLog ordAfterLog) {
		this.ordAfterLog = ordAfterLog;
	}

	public OrdOrder getOrderRenewalSuccessInfo() {
		return orderRenewalSuccessInfo;
	}

	public void setOrderRenewalSuccessInfo(OrdOrder orderRenewalSuccessInfo) {
		this.orderRenewalSuccessInfo = orderRenewalSuccessInfo;
	}
}
