package clb.core.order.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import java.math.BigDecimal;
import java.util.Date;

@ExtensionAttribute(disable=true)
@Table(name = "fms_ord_addition")
public class OrdAddition extends BaseDTO {
    @Id
    @GeneratedValue
    private Long additionId;

    @NotNull
    private Long orderId;

    @NotNull
    private Long itemId;

    @NotNull
    private Long sublineId;

    private String payMethod;

    private BigDecimal yearPayAmount;

    private BigDecimal policyAmount;

    private Long programId;

    private Long requestId;

    private String securityLevel;

    private String securityRegion;

    private String selfpay;

    private String status;
    
    private String surrenderFlag;
    
    private String saveStatus;

    @Transient
    private String itemName;

    @Transient
    private String statusDesc;

    @Transient
    private String dependMainFlag;
    
    @Transient
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date renewalDueDate;
    
    @Transient
    private BigDecimal nextPolicyAmount;
    
    @Transient
    private String currency;
    
    @Transient
    private String attribute1;

    @Transient
    private String payMethodDesc;

    @Transient
    private String sublineItemName;
    
    @Transient
	private Long payPeriods;
    
    @Transient
    private String source;//判断来源  订单表  附加险表

    @Transient
    private String minClass;

    @Transient
    private String orderNumber;

    @Transient
    private Long comCount;
    
    public String getSource() {
		return source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public Long getPayPeriods() {
		return payPeriods;
	}

	public void setPayPeriods(Long payPeriods) {
		this.payPeriods = payPeriods;
	}

	public String getSurrenderFlag() {
		return surrenderFlag;
	}

	public void setSurrenderFlag(String surrenderFlag) {
		this.surrenderFlag = surrenderFlag;
	}

	public String getAttribute1() {
		return attribute1;
	}

	public void setAttribute1(String attribute1) {
		this.attribute1 = attribute1;
	}

	public void setAdditionId(Long additionId){
        this.additionId = additionId;
    }

    public Long getAdditionId(){
        return additionId;
    }

    public void setOrderId(Long orderId){
        this.orderId = orderId;
    }

    public Long getOrderId(){
        return orderId;
    }

    public void setItemId(Long itemId){
        this.itemId = itemId;
    }

    public Long getItemId(){
        return itemId;
    }

    public Long getSublineId() {
        return sublineId;
    }

    public void setSublineId(Long sublineId) {
        this.sublineId = sublineId;
    }

    public void setPayMethod(String payMethod){
        this.payMethod = payMethod;
    }

    public String getPayMethod(){
        return payMethod;
    }

    public BigDecimal getYearPayAmount() {
        return yearPayAmount;
    }

    public void setYearPayAmount(BigDecimal yearPayAmount) {
        this.yearPayAmount = yearPayAmount;
    }

    public BigDecimal getPolicyAmount() {
        return policyAmount;
    }

    public void setPolicyAmount(BigDecimal policyAmount) {
        this.policyAmount = policyAmount;
    }

    public void setProgramId(Long programId){
        this.programId = programId;
    }

    public Long getProgramId(){
        return programId;
    }

    public void setRequestId(Long requestId){
        this.requestId = requestId;
    }

    public Long getRequestId(){
        return requestId;
    }

    public String getSecurityLevel() {
        return securityLevel;
    }

    public void setSecurityLevel(String securityLevel) {
        this.securityLevel = securityLevel;
    }

    public String getSecurityRegion() {
        return securityRegion;
    }

    public void setSecurityRegion(String securityRegion) {
        this.securityRegion = securityRegion;
    }

    public String getSelfpay() {
        return selfpay;
    }

    public void setSelfpay(String selfpay) {
        this.selfpay = selfpay;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getItemName() {
        return itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    public String getStatusDesc() {
        return statusDesc;
    }

    public void setStatusDesc(String statusDesc) {
        this.statusDesc = statusDesc;
    }

    public String getDependMainFlag() {
        return dependMainFlag;
    }

    public void setDependMainFlag(String dependMainFlag) {
        this.dependMainFlag = dependMainFlag;
    }

    public String getPayMethodDesc() {
        return payMethodDesc;
    }

    public void setPayMethodDesc(String payMethodDesc) {
        this.payMethodDesc = payMethodDesc;
    }

    public String getSublineItemName() {
        return sublineItemName;
    }

    public void setSublineItemName(String sublineItemName) {
        this.sublineItemName = sublineItemName;
    }

	public Date getRenewalDueDate() {
		return renewalDueDate;
	}

	public void setRenewalDueDate(Date renewalDueDate) {
		this.renewalDueDate = renewalDueDate;
	}

	public BigDecimal getNextPolicyAmount() {
		return nextPolicyAmount;
	}

	public void setNextPolicyAmount(BigDecimal nextPolicyAmount) {
		this.nextPolicyAmount = nextPolicyAmount;
	}

	public String getCurrency() {
		return currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

    public String getMinClass() {
        return minClass;
    }

    public void setMinClass(String minClass) {
        this.minClass = minClass;
    }

	public String getSaveStatus() {
		return saveStatus;
	}

	public void setSaveStatus(String saveStatus) {
		this.saveStatus = saveStatus;
	}

    public String getOrderNumber() {
        return orderNumber;
    }

    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    public Long getComCount() {
        return comCount;
    }

    public void setComCount(Long comCount) {
        this.comCount = comCount;
    }
}
