package clb.core.order.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "fms_ord_after_follow")
public class OrdAfterFollow extends BaseDTO {
     @Id
     @GeneratedValue
      private Long afterFollowId;

     @NotNull
      private Long afterId;

      private Long followUserId;
      @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
      private Date followDate;

     @NotEmpty
      private String content;
     
      private Long fileId;

      private Long programId;

      private Long requestId;
      
      @Transient
      private String userName;

     public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public void setAfterFollowId(Long afterFollowId){
         this.afterFollowId = afterFollowId;
     }

     public Long getAfterFollowId(){
         return afterFollowId;
     }

     public void setAfterId(Long afterId){
         this.afterId = afterId;
     }

     public Long getAfterId(){
         return afterId;
     }

     public void setFollowUserId(Long followUserId){
         this.followUserId = followUserId;
     }

     public Long getFollowUserId(){
         return followUserId;
     }

     public void setFollowDate(Date followDate){
         this.followDate = followDate;
     }

     public Date getFollowDate(){
         return followDate;
     }

     public void setContent(String content){
         this.content = content;
     }

     public String getContent(){
         return content;
     }

     public void setFileId(Long fileId){
         this.fileId = fileId;
     }

     public Long getFileId(){
         return fileId;
     }

     public void setProgramId(Long programId){
         this.programId = programId;
     }

     public Long getProgramId(){
         return programId;
     }

     public void setRequestId(Long requestId){
         this.requestId = requestId;
     }

     public Long getRequestId(){
         return requestId;
     }

     }
