package clb.core.order.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import java.math.BigDecimal;
import java.util.Date;

@ExtensionAttribute(disable=true)
@Table(name = "fms_ord_beneficiary")
public class OrdBeneficiary extends BaseDTO {
    @Id
    @GeneratedValue
    private Long ordBeneficiaryId;

    @NotNull
    private Long orderId;

    private String chineseName;

    private String englishName;

    private Long age;

    private String identityNumber;

    private String relationship;

    private BigDecimal rate;

    @JsonFormat(pattern="yyyy-MM-dd")
    private Date birthDate;

    private String highestEducation;

    private String career;

    private Long programId;

    private Long requestId;

    @Transient
    private String orderNumber;

    public void setOrdBeneficiaryId(Long ordBeneficiaryId){
        this.ordBeneficiaryId = ordBeneficiaryId;
    }

    public Long getOrdBeneficiaryId(){
        return ordBeneficiaryId;
    }

    public void setOrderId(Long orderId){
        this.orderId = orderId;
    }

    public Long getOrderId(){
        return orderId;
    }

    public void setChineseName(String chineseName){
        this.chineseName = chineseName;
    }

    public String getChineseName(){
        return chineseName;
    }

    public void setEnglishName(String englishName){
        this.englishName = englishName;
    }

    public String getEnglishName(){
        return englishName;
    }

    public void setAge(Long age){
        this.age = age;
    }

    public Long getAge(){
        return age;
    }

    public void setIdentityNumber(String identityNumber){
        this.identityNumber = identityNumber;
    }

    public String getIdentityNumber(){
        return identityNumber;
    }

    public void setRelationship(String relationship){
        this.relationship = relationship;
    }

    public String getRelationship(){
        return relationship;
    }

    public void setRate(BigDecimal rate){
        this.rate = rate;
    }

    public BigDecimal getRate(){
        return rate;
    }

    public Date getBirthDate() {
        return birthDate;
    }

    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    public String getHighestEducation() {
        return highestEducation;
    }

    public void setHighestEducation(String highestEducation) {
        this.highestEducation = highestEducation;
    }

    public String getCareer() {
        return career;
    }

    public void setCareer(String career) {
        this.career = career;
    }

    public void setProgramId(Long programId){
        this.programId = programId;
    }

    public Long getProgramId(){
        return programId;
    }

    public void setRequestId(Long requestId){
        this.requestId = requestId;
    }

    public Long getRequestId(){
        return requestId;
    }

    public String getOrderNumber() {
        return orderNumber;
    }

    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }
}
