package clb.core.order.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import javax.validation.constraints.NotNull;
@ExtensionAttribute(disable=true)
@Table(name = "fms_ord_cst_skill")
public class OrdCstSkill extends BaseDTO {
     @Id
     @GeneratedValue
      private Long cstSkillId;

     @NotNull
      private Long orderId;

      private String skillName;

      private String certificate;

      private String description;

      private Long programId;

      private Long requestId;


     public void setCstSkillId(Long cstSkillId){
         this.cstSkillId = cstSkillId;
     }

     public Long getCstSkillId(){
         return cstSkillId;
     }

     public void setOrderId(Long orderId){
         this.orderId = orderId;
     }

     public Long getOrderId(){
         return orderId;
     }

     public void setSkillName(String skillName){
         this.skillName = skillName;
     }

     public String getSkillName(){
         return skillName;
     }

     public void setCertificate(String certificate){
         this.certificate = certificate;
     }

     public String getCertificate(){
         return certificate;
     }

     public void setDescription(String description){
         this.description = description;
     }

     public String getDescription(){
         return description;
     }

     public void setProgramId(Long programId){
         this.programId = programId;
     }

     public Long getProgramId(){
         return programId;
     }

     public void setRequestId(Long requestId){
         this.requestId = requestId;
     }

     public Long getRequestId(){
         return requestId;
     }

     }
