package clb.core.order.dto;

import java.math.BigDecimal;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import clb.core.channel.dto.CnlChannelContract;

@ExtensionAttribute(disable=true)
@Table(name = "fms_ord_commission")
public class OrdCommission extends BaseDTO {
    @Id
    @GeneratedValue
    private Long commissionId;

    @NotNull
    private Long orderId;

    private Long seqNum;

    private Long companyId;

    private String companyType;

    private Long itemId;

    private String currency;

    private Long additionId;

    private BigDecimal theFirstYear;

    private BigDecimal theSecondYear;

    private BigDecimal theThirdYear;

    private BigDecimal theFourthYear;

    private BigDecimal theFifthYear;

    private BigDecimal theSixthYear;

    private BigDecimal theSeventhYear;

    private BigDecimal theEightYear;

    private BigDecimal theNinthYear;

    private BigDecimal theTenthYear;

    private BigDecimal firstYearAmount;

    private BigDecimal secondYearAmount;

    private BigDecimal thirdYearAmount;

    private BigDecimal fourthYearAmount;

    private BigDecimal fifthYearAmount;

    private BigDecimal sixthYearAmount;

    private BigDecimal seventhYearAmount;

    private BigDecimal eightYearAmount;

    private BigDecimal ninthYearAmount;

    private BigDecimal tenthYearAmount;

    private BigDecimal firstYearActual;

    private BigDecimal secondYearActual;

    private BigDecimal thirdYearActual;

    private BigDecimal fourthYearActual;

    private BigDecimal fifthYearActual;

    private BigDecimal sixthYearActual;

    private BigDecimal seventhYearActual;

    private BigDecimal eightYearActual;

    private BigDecimal ninthYearActual;

    private BigDecimal tenthYearActual;

    private Long channelContractId;

    private Long programId;

    private Long requestId;

    private String manualFlag;

    @Transient
    private String companyName;

    @Transient
    private String itemName;
    
    //实际费率
    @Transient
    private BigDecimal actualRate;
    
    //合约详情
    @Transient
    private CnlChannelContract channelContract;

    @Transient
    private BigDecimal yearPayAmount;
    
    @Transient
    private String contractCode;
    
    @Transient
    private String orderType;

    @Transient
    private String orderNumber;

    @Transient
    private String commissionPerson;

    @Transient
    private Long preUserId;

    @Transient
    private String allManual;

    public void setCommissionId(Long commissionId){
        this.commissionId = commissionId;
    }

    public Long getCommissionId(){
        return commissionId;
    }

    public void setOrderId(Long orderId){
        this.orderId = orderId;
    }

    public Long getOrderId(){
        return orderId;
    }

    public Long getSeqNum() {
        return seqNum;
    }

    public void setSeqNum(Long seqNum) {
        this.seqNum = seqNum;
    }

    public Long getCompanyId() {
        return companyId;
    }

    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    public String getCompanyType() {
        return companyType;
    }

    public void setCompanyType(String companyType) {
        this.companyType = companyType;
    }

    public void setItemId(Long itemId){
        this.itemId = itemId;
    }

    public Long getItemId(){
        return itemId;
    }

    public void setCurrency(String currency){
        this.currency = currency;
    }

    public String getCurrency(){
        return currency;
    }

    public Long getAdditionId() {
        return additionId;
    }

    public void setAdditionId(Long additionId) {
        this.additionId = additionId;
    }

    public BigDecimal getTheFirstYear() {
        return theFirstYear;
    }

    public void setTheFirstYear(BigDecimal theFirstYear) {
        this.theFirstYear = theFirstYear;
    }

    public BigDecimal getTheSecondYear() {
        return theSecondYear;
    }

    public void setTheSecondYear(BigDecimal theSecondYear) {
        this.theSecondYear = theSecondYear;
    }

    public BigDecimal getTheThirdYear() {
        return theThirdYear;
    }

    public void setTheThirdYear(BigDecimal theThirdYear) {
        this.theThirdYear = theThirdYear;
    }

    public BigDecimal getTheFourthYear() {
        return theFourthYear;
    }

    public void setTheFourthYear(BigDecimal theFourthYear) {
        this.theFourthYear = theFourthYear;
    }

    public BigDecimal getTheFifthYear() {
        return theFifthYear;
    }

    public void setTheFifthYear(BigDecimal theFifthYear) {
        this.theFifthYear = theFifthYear;
    }

    public BigDecimal getTheSixthYear() {
        return theSixthYear;
    }

    public void setTheSixthYear(BigDecimal theSixthYear) {
        this.theSixthYear = theSixthYear;
    }

    public BigDecimal getTheSeventhYear() {
        return theSeventhYear;
    }

    public void setTheSeventhYear(BigDecimal theSeventhYear) {
        this.theSeventhYear = theSeventhYear;
    }

    public BigDecimal getTheEightYear() {
        return theEightYear;
    }

    public void setTheEightYear(BigDecimal theEightYear) {
        this.theEightYear = theEightYear;
    }

    public BigDecimal getTheNinthYear() {
        return theNinthYear;
    }

    public void setTheNinthYear(BigDecimal theNinthYear) {
        this.theNinthYear = theNinthYear;
    }

    public BigDecimal getTheTenthYear() {
        return theTenthYear;
    }

    public void setTheTenthYear(BigDecimal theTenthYear) {
        this.theTenthYear = theTenthYear;
    }

    public BigDecimal getFirstYearAmount() {
        return firstYearAmount;
    }

    public void setFirstYearAmount(BigDecimal firstYearAmount) {
        this.firstYearAmount = firstYearAmount;
    }

    public BigDecimal getSecondYearAmount() {
        return secondYearAmount;
    }

    public void setSecondYearAmount(BigDecimal secondYearAmount) {
        this.secondYearAmount = secondYearAmount;
    }

    public BigDecimal getThirdYearAmount() {
        return thirdYearAmount;
    }

    public void setThirdYearAmount(BigDecimal thirdYearAmount) {
        this.thirdYearAmount = thirdYearAmount;
    }

    public BigDecimal getFourthYearAmount() {
        return fourthYearAmount;
    }

    public void setFourthYearAmount(BigDecimal fourthYearAmount) {
        this.fourthYearAmount = fourthYearAmount;
    }

    public BigDecimal getFifthYearAmount() {
        return fifthYearAmount;
    }

    public void setFifthYearAmount(BigDecimal fifthYearAmount) {
        this.fifthYearAmount = fifthYearAmount;
    }

    public BigDecimal getSixthYearAmount() {
        return sixthYearAmount;
    }

    public void setSixthYearAmount(BigDecimal sixthYearAmount) {
        this.sixthYearAmount = sixthYearAmount;
    }

    public BigDecimal getSeventhYearAmount() {
        return seventhYearAmount;
    }

    public void setSeventhYearAmount(BigDecimal seventhYearAmount) {
        this.seventhYearAmount = seventhYearAmount;
    }

    public BigDecimal getEightYearAmount() {
        return eightYearAmount;
    }

    public void setEightYearAmount(BigDecimal eightYearAmount) {
        this.eightYearAmount = eightYearAmount;
    }

    public BigDecimal getNinthYearAmount() {
        return ninthYearAmount;
    }

    public void setNinthYearAmount(BigDecimal ninthYearAmount) {
        this.ninthYearAmount = ninthYearAmount;
    }

    public BigDecimal getTenthYearAmount() {
        return tenthYearAmount;
    }

    public void setTenthYearAmount(BigDecimal tenthYearAmount) {
        this.tenthYearAmount = tenthYearAmount;
    }

    public BigDecimal getFirstYearActual() {
        return firstYearActual;
    }

    public void setFirstYearActual(BigDecimal firstYearActual) {
        this.firstYearActual = firstYearActual;
    }

    public BigDecimal getSecondYearActual() {
        return secondYearActual;
    }

    public void setSecondYearActual(BigDecimal secondYearActual) {
        this.secondYearActual = secondYearActual;
    }

    public BigDecimal getThirdYearActual() {
        return thirdYearActual;
    }

    public void setThirdYearActual(BigDecimal thirdYearActual) {
        this.thirdYearActual = thirdYearActual;
    }

    public BigDecimal getFourthYearActual() {
        return fourthYearActual;
    }

    public void setFourthYearActual(BigDecimal fourthYearActual) {
        this.fourthYearActual = fourthYearActual;
    }

    public BigDecimal getFifthYearActual() {
        return fifthYearActual;
    }

    public void setFifthYearActual(BigDecimal fifthYearActual) {
        this.fifthYearActual = fifthYearActual;
    }

    public BigDecimal getSixthYearActual() {
        return sixthYearActual;
    }

    public void setSixthYearActual(BigDecimal sixthYearActual) {
        this.sixthYearActual = sixthYearActual;
    }

    public BigDecimal getSeventhYearActual() {
        return seventhYearActual;
    }

    public void setSeventhYearActual(BigDecimal seventhYearActual) {
        this.seventhYearActual = seventhYearActual;
    }

    public BigDecimal getEightYearActual() {
        return eightYearActual;
    }

    public void setEightYearActual(BigDecimal eightYearActual) {
        this.eightYearActual = eightYearActual;
    }

    public BigDecimal getNinthYearActual() {
        return ninthYearActual;
    }

    public void setNinthYearActual(BigDecimal ninthYearActual) {
        this.ninthYearActual = ninthYearActual;
    }

    public BigDecimal getTenthYearActual() {
        return tenthYearActual;
    }

    public void setTenthYearActual(BigDecimal tenthYearActual) {
        this.tenthYearActual = tenthYearActual;
    }

    public Long getChannelContractId() {
        return channelContractId;
    }

    public void setChannelContractId(Long channelContractId) {
        this.channelContractId = channelContractId;
    }

    public void setProgramId(Long programId){
        this.programId = programId;
    }

    public Long getProgramId(){
        return programId;
    }

    public void setRequestId(Long requestId){
        this.requestId = requestId;
    }

    public Long getRequestId(){
        return requestId;
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public String getItemName() {
        return itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

	public BigDecimal getActualRate() {
		return actualRate;
	}

	public void setActualRate(BigDecimal actualRate) {
		this.actualRate = actualRate;
	}

	public CnlChannelContract getChannelContract() {
		return channelContract;
	}

	public void setChannelContract(CnlChannelContract channelContract) {
		this.channelContract = channelContract;
	}

    public BigDecimal getYearPayAmount() {
        return yearPayAmount;
    }

    public void setYearPayAmount(BigDecimal yearPayAmount) {
        this.yearPayAmount = yearPayAmount;
    }

	public String getContractCode() {
		return contractCode;
	}

	public void setContractCode(String contractCode) {
		this.contractCode = contractCode;
	}

	public String getOrderType() {
		return orderType;
	}

	public void setOrderType(String orderType) {
		this.orderType = orderType;
	}

    public String getOrderNumber() {
        return orderNumber;
    }

    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    public String getCommissionPerson() {
        return commissionPerson;
    }

    public void setCommissionPerson(String commissionPerson) {
        this.commissionPerson = commissionPerson;
    }

    public Long getPreUserId() {
        return preUserId;
    }

    public void setPreUserId(Long preUserId) {
        this.preUserId = preUserId;
    }

    public String getManualFlag() {
        return manualFlag;
    }

    public void setManualFlag(String manualFlag) {
        this.manualFlag = manualFlag;
    }

    public String getAllManual() {
        return allManual;
    }

    public void setAllManual(String allManual) {
        this.allManual = allManual;
    }
}
