package clb.core.order.dto;

/**Auto Generated By Hap Code Generator**/

import clb.core.core.annotation.SecurityField;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
@ExtensionAttribute(disable=true)
@Table(name = "fms_ord_customer")
public class OrdCustomer extends BaseDTO {
    private static final long serialVersionUID = 2222011317593188238L;

    @Id
    @GeneratedValue
    private Long ordCustomerId;

    @NotNull
    private Long orderId;

    private String customerType;

    private String chineseName;

    private String englishName;
    
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date birthDate;

    private String sex;

    private String nationality;

    private Long height;

    private Long weight;

    @SecurityField
    private String phoneCode;

    @SecurityField
    private String phone;

    private String email;

    private String companyName;

    private String industry;

    private String companyAddress;

    private String city;

    private Long income;

    private String job;

    private String position;

    private String education;

    private String marriageStatus;

    private String smokeFlag;

    private String americanCitizenFlag;

    private String identityNumber;

    private String identityEffectiveDate;

    private String certificateType;

    private String certificateNumber;

    private String certificateEffectiveDate;

    private String identityNation;

    private String identityProvince;

    private String identityCity;

    private String identityAddress;

    private String identityFlag;

    private String postNation;

    private String postProvince;

    private String postCity;

    private String postAddress;

    private String premiumSource;

    private Double amountPerMonth;

    private Double currentAssets;

    private Double fixedAssets;

    private String premiumRate;

    private Double liabilities;

    private String badFlag;

    private String badInsuranceName;

    private String badInsuranceType;

    private Date badEffactiveDate;

    private String guaranteeFlag;

    private String guaranteeInsuranceName;

    private String guaranteeInsuranceType;

    private Date guaranteeEffactiveDate;

    private String compensateFlag;

    private String compensateInsuranceName;

    private String compensateInsuranceType;

    private Date compensateEffactiveDate;

    private String smokeDesc;

    private String drinkFlag;

    private String drinkDesc;

    private String drugFlag;

    private String drugDesc;

    private String dangerousFlag;

    private String dangerousDesc;

    private String abroadFlag;

    private String abroadDesc;

    private String disabilityFlag;

    private String disabilityDesc;

    private String spiritFlag;

    private String spiritDesc;

    private String endocrineFlag;

    private String endocrineDesc;

    private String faceFlag;

    private String faceDesc;

    private String respirationFlag;

    private String respirationDesc;

    private String threeFlag;

    private String threeDesc;

    private String cycleFlag;

    private String cycleDesc;

    private String digestionFlag;

    private String digestionDesc;

    private String liverFlag;

    private String liverDesc;

    private String reproductionFlag;

    private String reproductionDesc;

    private String jointFlag;

    private String jointDesc;

    private String tumorFlag;

    private String tumorDesc;

    private String bloodFlag;

    private String bloodDesc;

    private String aidsFlag;

    private String aidsDesc;

    private String aidsTestFlag;

    private String aidsTestDesc;

    private String skinFlag;

    private String skinDesc;

    private String otherFlag;

    private String otherDesc;

    private String otherTreatFlag;

    private String otherTreatDesc;

    private String examinationFlag;

    private String examinationDesc;

    private String hereditaryFlag;

    private String hereditaryDesc;

    private String pregnancyFlag;

    private String pregnancyDesc;

    private String downTestFlag;

    private String downTestDesc;

    private String gynecologyFlag;

    private String gynecologyDesc;

    private String complicationFlag;

    private String complicationDesc;

    private String gynecologyOthFlag;

    private String gynecologyOthDesc;

    private String customerLang;

    private String hkCardFlag;

    private String securitiesFlag;

    private String professionalFlag;

    private String abroadLiveFlag;

    private String visaRefuseFlag;

    private String visaRefuseCountry;

    private String visaRefuseReason;

    private String abroadEducationFlag;

    private String abroadEducationCountry;

    private String abroadEducationSchool;

    private String abroadEducationProfession;

    private Date abroadEducationStartDate;

    private Date abroadEducationEndDate;

    private String englishAbility;

    private BigDecimal ieltsScore;

    private String otherLang;

    private Long programId;

    private Long requestId;

    private String companyNation;

    private String companyProvince;

    private String companyCity;

    @Transient
    private List<Long> orderIds;

    @Transient
    private Long customerId;

    @Transient
    private String coverType;

    @Transient
    private String orderNumber;

    public void setOrdCustomerId(Long ordCustomerId){
        this.ordCustomerId = ordCustomerId;
    }

    public Long getOrdCustomerId(){
        return ordCustomerId;
    }

    public void setOrderId(Long orderId){
        this.orderId = orderId;
    }

    public Long getOrderId(){
        return orderId;
    }

    public void setCustomerType(String customerType){
        this.customerType = customerType;
    }

    public String getCustomerType(){
        return customerType;
    }

    public void setChineseName(String chineseName){
        this.chineseName = chineseName;
    }

    public String getChineseName(){
        return chineseName;
    }

    public void setEnglishName(String englishName){
        this.englishName = englishName;
    }

    public String getEnglishName(){
        return englishName;
    }

    public void setBirthDate(Date birthDate){
        this.birthDate = birthDate;
    }

    public Date getBirthDate(){
        return birthDate;
    }

    public void setSex(String sex){
        this.sex = sex;
    }

    public String getSex(){
        return sex;
    }

    public void setNationality(String nationality){
        this.nationality = nationality;
    }

    public String getNationality(){
        return nationality;
    }

    public void setHeight(Long height){
        this.height = height;
    }

    public Long getHeight(){
        return height;
    }

    public void setWeight(Long weight){
        this.weight = weight;
    }

    public Long getWeight(){
        return weight;
    }

    public String getPhoneCode() {
        return phoneCode;
    }

    public void setPhoneCode(String phoneCode) {
        this.phoneCode = phoneCode;
    }

    public void setPhone(String phone){
        this.phone = phone;
    }

    public String getPhone(){
        return phone;
    }

    public void setEmail(String email){
        this.email = email;
    }

    public String getEmail(){
        return email;
    }

    public void setCompanyName(String companyName){
        this.companyName = companyName;
    }

    public String getCompanyName(){
        return companyName;
    }

    public void setIndustry(String industry){
        this.industry = industry;
    }

    public String getIndustry(){
        return industry;
    }

    public void setCompanyAddress(String companyAddress){
        this.companyAddress = companyAddress;
    }

    public String getCompanyAddress(){
        return companyAddress;
    }

    public void setCity(String city){
        this.city = city;
    }

    public String getCity(){
        return city;
    }

    public void setIncome(Long income){
        this.income = income;
    }

    public Long getIncome(){
        return income;
    }

    public void setJob(String job){
        this.job = job;
    }

    public String getJob(){
        return job;
    }

    public void setPosition(String position){
        this.position = position;
    }

    public String getPosition(){
        return position;
    }

    public void setEducation(String education){
        this.education = education;
    }

    public String getEducation(){
        return education;
    }

    public void setMarriageStatus(String marriageStatus){
        this.marriageStatus = marriageStatus;
    }

    public String getMarriageStatus(){
        return marriageStatus;
    }

    public void setSmokeFlag(String smokeFlag){
        this.smokeFlag = smokeFlag;
    }

    public String getSmokeFlag(){
        return smokeFlag;
    }

    public void setAmericanCitizenFlag(String americanCitizenFlag){
        this.americanCitizenFlag = americanCitizenFlag;
    }

    public String getAmericanCitizenFlag(){
        return americanCitizenFlag;
    }

    public void setIdentityNumber(String identityNumber){
        this.identityNumber = identityNumber;
    }

    public String getIdentityNumber(){
        return identityNumber;
    }

    public void setIdentityEffectiveDate(String identityEffectiveDate){
        this.identityEffectiveDate = identityEffectiveDate;
    }

    public String getIdentityEffectiveDate(){
        return identityEffectiveDate;
    }

    public void setCertificateType(String certificateType){
        this.certificateType = certificateType;
    }

    public String getCertificateType(){
        return certificateType;
    }

    public void setCertificateNumber(String certificateNumber){
        this.certificateNumber = certificateNumber;
    }

    public String getCertificateNumber(){
        return certificateNumber;
    }

    public void setCertificateEffectiveDate(String certificateEffectiveDate){
        this.certificateEffectiveDate = certificateEffectiveDate;
    }

    public String getCertificateEffectiveDate(){
        return certificateEffectiveDate;
    }

    public void setIdentityNation(String identityNation){
        this.identityNation = identityNation;
    }

    public String getIdentityNation(){
        return identityNation;
    }

    public void setIdentityProvince(String identityProvince){
        this.identityProvince = identityProvince;
    }

    public String getIdentityProvince(){
        return identityProvince;
    }

    public void setIdentityCity(String identityCity){
        this.identityCity = identityCity;
    }

    public String getIdentityCity(){
        return identityCity;
    }

    public void setIdentityAddress(String identityAddress){
        this.identityAddress = identityAddress;
    }

    public String getIdentityAddress(){
        return identityAddress;
    }

    public void setIdentityFlag(String identityFlag){
        this.identityFlag = identityFlag;
    }

    public String getIdentityFlag(){
        return identityFlag;
    }

    public void setPostNation(String postNation){
        this.postNation = postNation;
    }

    public String getPostNation(){
        return postNation;
    }

    public void setPostProvince(String postProvince){
        this.postProvince = postProvince;
    }

    public String getPostProvince(){
        return postProvince;
    }

    public void setPostCity(String postCity){
        this.postCity = postCity;
    }

    public String getPostCity(){
        return postCity;
    }

    public void setPostAddress(String postAddress){
        this.postAddress = postAddress;
    }

    public String getPostAddress(){
        return postAddress;
    }

    public void setPremiumSource(String premiumSource){
        this.premiumSource = premiumSource;
    }

    public String getPremiumSource(){
        return premiumSource;
    }

    public void setAmountPerMonth(Double amountPerMonth){
        this.amountPerMonth = amountPerMonth;
    }

    public Double getAmountPerMonth(){
        return amountPerMonth;
    }

    public void setCurrentAssets(Double currentAssets){
        this.currentAssets = currentAssets;
    }

    public Double getCurrentAssets(){
        return currentAssets;
    }

    public void setFixedAssets(Double fixedAssets){
        this.fixedAssets = fixedAssets;
    }

    public Double getFixedAssets(){
        return fixedAssets;
    }

    public void setPremiumRate(String premiumRate){
        this.premiumRate = premiumRate;
    }

    public String getPremiumRate(){
        return premiumRate;
    }

    public void setLiabilities(Double liabilities){
        this.liabilities = liabilities;
    }

    public Double getLiabilities(){
        return liabilities;
    }

    public void setBadFlag(String badFlag){
        this.badFlag = badFlag;
    }

    public String getBadFlag(){
        return badFlag;
    }

    public void setCompensateFlag(String compensateFlag){
        this.compensateFlag = compensateFlag;
    }

    public String getCompensateFlag(){
        return compensateFlag;
    }

    public void setBadInsuranceName(String badInsuranceName){
        this.badInsuranceName = badInsuranceName;
    }

    public String getBadInsuranceName(){
        return badInsuranceName;
    }

    public void setBadInsuranceType(String badInsuranceType){
        this.badInsuranceType = badInsuranceType;
    }

    public String getBadInsuranceType(){
        return badInsuranceType;
    }

    public void setBadEffactiveDate(Date badEffactiveDate){
        this.badEffactiveDate = badEffactiveDate;
    }

    public Date getBadEffactiveDate(){
        return badEffactiveDate;
    }

    public void setCompensateInsuranceName(String compensateInsuranceName){
        this.compensateInsuranceName = compensateInsuranceName;
    }

    public String getCompensateInsuranceName(){
        return compensateInsuranceName;
    }

    public void setCompensateInsuranceType(String compensateInsuranceType){
        this.compensateInsuranceType = compensateInsuranceType;
    }

    public String getCompensateInsuranceType(){
        return compensateInsuranceType;
    }

    public void setCompensateEffactiveDate(Date compensateEffactiveDate){
        this.compensateEffactiveDate = compensateEffactiveDate;
    }

    public Date getCompensateEffactiveDate(){
        return compensateEffactiveDate;
    }

    public void setSmokeDesc(String smokeDesc){
        this.smokeDesc = smokeDesc;
    }

    public String getSmokeDesc(){
        return smokeDesc;
    }

    public void setDrinkFlag(String drinkFlag){
        this.drinkFlag = drinkFlag;
    }

    public String getDrinkFlag(){
        return drinkFlag;
    }

    public void setDrinkDesc(String drinkDesc){
        this.drinkDesc = drinkDesc;
    }

    public String getDrinkDesc(){
        return drinkDesc;
    }

    public void setDrugFlag(String drugFlag){
        this.drugFlag = drugFlag;
    }

    public String getDrugFlag(){
        return drugFlag;
    }

    public void setDrugDesc(String drugDesc){
        this.drugDesc = drugDesc;
    }

    public String getDrugDesc(){
        return drugDesc;
    }

    public void setDangerousFlag(String dangerousFlag){
        this.dangerousFlag = dangerousFlag;
    }

    public String getDangerousFlag(){
        return dangerousFlag;
    }

    public void setDangerousDesc(String dangerousDesc){
        this.dangerousDesc = dangerousDesc;
    }

    public String getDangerousDesc(){
        return dangerousDesc;
    }

    public void setAbroadFlag(String abroadFlag){
        this.abroadFlag = abroadFlag;
    }

    public String getAbroadFlag(){
        return abroadFlag;
    }

    public void setAbroadDesc(String abroadDesc){
        this.abroadDesc = abroadDesc;
    }

    public String getAbroadDesc(){
        return abroadDesc;
    }

    public void setDisabilityFlag(String disabilityFlag){
        this.disabilityFlag = disabilityFlag;
    }

    public String getDisabilityFlag(){
        return disabilityFlag;
    }

    public void setDisabilityDesc(String disabilityDesc){
        this.disabilityDesc = disabilityDesc;
    }

    public String getDisabilityDesc(){
        return disabilityDesc;
    }

    public void setSpiritFlag(String spiritFlag){
        this.spiritFlag = spiritFlag;
    }

    public String getSpiritFlag(){
        return spiritFlag;
    }

    public void setSpiritDesc(String spiritDesc){
        this.spiritDesc = spiritDesc;
    }

    public String getSpiritDesc(){
        return spiritDesc;
    }

    public void setEndocrineFlag(String endocrineFlag){
        this.endocrineFlag = endocrineFlag;
    }

    public String getEndocrineFlag(){
        return endocrineFlag;
    }

    public void setEndocrineDesc(String endocrineDesc){
        this.endocrineDesc = endocrineDesc;
    }

    public String getEndocrineDesc(){
        return endocrineDesc;
    }

    public void setFaceFlag(String faceFlag){
        this.faceFlag = faceFlag;
    }

    public String getFaceFlag(){
        return faceFlag;
    }

    public void setFaceDesc(String faceDesc){
        this.faceDesc = faceDesc;
    }

    public String getFaceDesc(){
        return faceDesc;
    }

    public void setRespirationFlag(String respirationFlag){
        this.respirationFlag = respirationFlag;
    }

    public String getRespirationFlag(){
        return respirationFlag;
    }

    public void setRespirationDesc(String respirationDesc){
        this.respirationDesc = respirationDesc;
    }

    public String getRespirationDesc(){
        return respirationDesc;
    }

    public void setThreeFlag(String threeFlag){
        this.threeFlag = threeFlag;
    }

    public String getThreeFlag(){
        return threeFlag;
    }

    public void setThreeDesc(String threeDesc){
        this.threeDesc = threeDesc;
    }

    public String getThreeDesc(){
        return threeDesc;
    }

    public void setCycleFlag(String cycleFlag){
        this.cycleFlag = cycleFlag;
    }

    public String getCycleFlag(){
        return cycleFlag;
    }

    public void setCycleDesc(String cycleDesc){
        this.cycleDesc = cycleDesc;
    }

    public String getCycleDesc(){
        return cycleDesc;
    }

    public void setDigestionFlag(String digestionFlag){
        this.digestionFlag = digestionFlag;
    }

    public String getDigestionFlag(){
        return digestionFlag;
    }

    public void setDigestionDesc(String digestionDesc){
        this.digestionDesc = digestionDesc;
    }

    public String getDigestionDesc(){
        return digestionDesc;
    }

    public void setLiverFlag(String liverFlag){
        this.liverFlag = liverFlag;
    }

    public String getLiverFlag(){
        return liverFlag;
    }

    public void setLiverDesc(String liverDesc){
        this.liverDesc = liverDesc;
    }

    public String getLiverDesc(){
        return liverDesc;
    }

    public void setReproductionFlag(String reproductionFlag){
        this.reproductionFlag = reproductionFlag;
    }

    public String getReproductionFlag(){
        return reproductionFlag;
    }

    public void setReproductionDesc(String reproductionDesc){
        this.reproductionDesc = reproductionDesc;
    }

    public String getReproductionDesc(){
        return reproductionDesc;
    }

    public void setJointFlag(String jointFlag){
        this.jointFlag = jointFlag;
    }

    public String getJointFlag(){
        return jointFlag;
    }

    public void setJointDesc(String jointDesc){
        this.jointDesc = jointDesc;
    }

    public String getJointDesc(){
        return jointDesc;
    }

    public void setTumorFlag(String tumorFlag){
        this.tumorFlag = tumorFlag;
    }

    public String getTumorFlag(){
        return tumorFlag;
    }

    public void setTumorDesc(String tumorDesc){
        this.tumorDesc = tumorDesc;
    }

    public String getTumorDesc(){
        return tumorDesc;
    }

    public void setBloodFlag(String bloodFlag){
        this.bloodFlag = bloodFlag;
    }

    public String getBloodFlag(){
        return bloodFlag;
    }

    public void setBloodDesc(String bloodDesc){
        this.bloodDesc = bloodDesc;
    }

    public String getBloodDesc(){
        return bloodDesc;
    }

    public void setAidsFlag(String aidsFlag){
        this.aidsFlag = aidsFlag;
    }

    public String getAidsFlag(){
        return aidsFlag;
    }

    public void setAidsDesc(String aidsDesc){
        this.aidsDesc = aidsDesc;
    }

    public String getAidsDesc(){
        return aidsDesc;
    }

    public void setAidsTestFlag(String aidsTestFlag){
        this.aidsTestFlag = aidsTestFlag;
    }

    public String getAidsTestFlag(){
        return aidsTestFlag;
    }

    public void setAidsTestDesc(String aidsTestDesc){
        this.aidsTestDesc = aidsTestDesc;
    }

    public String getAidsTestDesc(){
        return aidsTestDesc;
    }

    public void setSkinFlag(String skinFlag){
        this.skinFlag = skinFlag;
    }

    public String getSkinFlag(){
        return skinFlag;
    }

    public void setSkinDesc(String skinDesc){
        this.skinDesc = skinDesc;
    }

    public String getSkinDesc(){
        return skinDesc;
    }

    public void setOtherFlag(String otherFlag){
        this.otherFlag = otherFlag;
    }

    public String getOtherFlag(){
        return otherFlag;
    }

    public void setOtherDesc(String otherDesc){
        this.otherDesc = otherDesc;
    }

    public String getOtherDesc(){
        return otherDesc;
    }

    public String getOtherTreatFlag() {
        return otherTreatFlag;
    }

    public void setOtherTreatFlag(String otherTreatFlag) {
        this.otherTreatFlag = otherTreatFlag;
    }

    public String getOtherTreatDesc() {
        return otherTreatDesc;
    }

    public void setOtherTreatDesc(String otherTreatDesc) {
        this.otherTreatDesc = otherTreatDesc;
    }

    public void setExaminationFlag(String examinationFlag){
        this.examinationFlag = examinationFlag;
    }

    public String getExaminationFlag(){
        return examinationFlag;
    }

    public void setExaminationDesc(String examinationDesc){
        this.examinationDesc = examinationDesc;
    }

    public String getExaminationDesc(){
        return examinationDesc;
    }

    public void setHereditaryFlag(String hereditaryFlag){
        this.hereditaryFlag = hereditaryFlag;
    }

    public String getHereditaryFlag(){
        return hereditaryFlag;
    }

    public void setHereditaryDesc(String hereditaryDesc){
        this.hereditaryDesc = hereditaryDesc;
    }

    public String getHereditaryDesc(){
        return hereditaryDesc;
    }

    public void setPregnancyFlag(String pregnancyFlag){
        this.pregnancyFlag = pregnancyFlag;
    }

    public String getPregnancyFlag(){
        return pregnancyFlag;
    }

    public void setPregnancyDesc(String pregnancyDesc){
        this.pregnancyDesc = pregnancyDesc;
    }

    public String getPregnancyDesc(){
        return pregnancyDesc;
    }

    public void setDownTestFlag(String downTestFlag){
        this.downTestFlag = downTestFlag;
    }

    public String getDownTestFlag(){
        return downTestFlag;
    }

    public void setDownTestDesc(String downTestDesc){
        this.downTestDesc = downTestDesc;
    }

    public String getDownTestDesc(){
        return downTestDesc;
    }

    public void setGynecologyFlag(String gynecologyFlag){
        this.gynecologyFlag = gynecologyFlag;
    }

    public String getGynecologyFlag(){
        return gynecologyFlag;
    }

    public void setGynecologyDesc(String gynecologyDesc){
        this.gynecologyDesc = gynecologyDesc;
    }

    public String getGynecologyDesc(){
        return gynecologyDesc;
    }

    public void setComplicationFlag(String complicationFlag){
        this.complicationFlag = complicationFlag;
    }

    public String getComplicationFlag(){
        return complicationFlag;
    }

    public void setComplicationDesc(String complicationDesc){
        this.complicationDesc = complicationDesc;
    }

    public String getComplicationDesc(){
        return complicationDesc;
    }

    public void setGynecologyOthFlag(String gynecologyOthFlag){
        this.gynecologyOthFlag = gynecologyOthFlag;
    }

    public String getGynecologyOthFlag(){
        return gynecologyOthFlag;
    }

    public void setGynecologyOthDesc(String gynecologyOthDesc){
        this.gynecologyOthDesc = gynecologyOthDesc;
    }

    public String getGynecologyOthDesc(){
        return gynecologyOthDesc;
    }

    public String getCustomerLang() {
        return customerLang;
    }

    public void setCustomerLang(String customerLang) {
        this.customerLang = customerLang;
    }

    public String getHkCardFlag() {
        return hkCardFlag;
    }

    public void setHkCardFlag(String hkCardFlag) {
        this.hkCardFlag = hkCardFlag;
    }

    public String getSecuritiesFlag() {
        return securitiesFlag;
    }

    public void setSecuritiesFlag(String securitiesFlag) {
        this.securitiesFlag = securitiesFlag;
    }

    public String getProfessionalFlag() {
        return professionalFlag;
    }

    public void setProfessionalFlag(String professionalFlag) {
        this.professionalFlag = professionalFlag;
    }

    public String getAbroadLiveFlag() {
        return abroadLiveFlag;
    }

    public void setAbroadLiveFlag(String abroadLiveFlag) {
        this.abroadLiveFlag = abroadLiveFlag;
    }

    public String getVisaRefuseFlag() {
        return visaRefuseFlag;
    }

    public void setVisaRefuseFlag(String visaRefuseFlag) {
        this.visaRefuseFlag = visaRefuseFlag;
    }

    public String getVisaRefuseCountry() {
        return visaRefuseCountry;
    }

    public void setVisaRefuseCountry(String visaRefuseCountry) {
        this.visaRefuseCountry = visaRefuseCountry;
    }

    public String getVisaRefuseReason() {
        return visaRefuseReason;
    }

    public void setVisaRefuseReason(String visaRefuseReason) {
        this.visaRefuseReason = visaRefuseReason;
    }

    public String getAbroadEducationFlag() {
        return abroadEducationFlag;
    }

    public void setAbroadEducationFlag(String abroadEducationFlag) {
        this.abroadEducationFlag = abroadEducationFlag;
    }

    public String getAbroadEducationCountry() {
        return abroadEducationCountry;
    }

    public void setAbroadEducationCountry(String abroadEducationCountry) {
        this.abroadEducationCountry = abroadEducationCountry;
    }

    public String getAbroadEducationSchool() {
        return abroadEducationSchool;
    }

    public void setAbroadEducationSchool(String abroadEducationSchool) {
        this.abroadEducationSchool = abroadEducationSchool;
    }

    public String getAbroadEducationProfession() {
        return abroadEducationProfession;
    }

    public void setAbroadEducationProfession(String abroadEducationProfession) {
        this.abroadEducationProfession = abroadEducationProfession;
    }

    public Date getAbroadEducationStartDate() {
        return abroadEducationStartDate;
    }

    public void setAbroadEducationStartDate(Date abroadEducationStartDate) {
        this.abroadEducationStartDate = abroadEducationStartDate;
    }

    public String getEnglishAbility() {
        return englishAbility;
    }

    public void setEnglishAbility(String englishAbility) {
        this.englishAbility = englishAbility;
    }

    public BigDecimal getIeltsScore() {
        return ieltsScore;
    }

    public void setIeltsScore(BigDecimal ieltsScore) {
        this.ieltsScore = ieltsScore;
    }

    public String getOtherLang() {
        return otherLang;
    }

    public void setOtherLang(String otherLang) {
        this.otherLang = otherLang;
    }

    public void setProgramId(Long programId){
        this.programId = programId;
    }

    public Long getProgramId(){
        return programId;
    }

    public void setRequestId(Long requestId){
        this.requestId = requestId;
    }

    public Long getRequestId(){
        return requestId;
    }

    public List<Long> getOrderIds() {
        return orderIds;
    }

    public void setOrderIds(List<Long> orderIds) {
        this.orderIds = orderIds;
    }

    public Date getAbroadEducationEndDate() {
        return abroadEducationEndDate;
    }

    public void setAbroadEducationEndDate(Date abroadEducationEndDate) {
        this.abroadEducationEndDate = abroadEducationEndDate;
    }

    public Long getCustomerId() {
        return customerId;
    }

    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    public String getCoverType() {
        return coverType;
    }

    public void setCoverType(String coverType) {
        this.coverType = coverType;
    }

    public String getCompanyNation() {
        return companyNation;
    }

    public void setCompanyNation(String companyNation) {
        this.companyNation = companyNation;
    }

    public String getCompanyProvince() {
        return companyProvince;
    }

    public void setCompanyProvince(String companyProvince) {
        this.companyProvince = companyProvince;
    }

    public String getCompanyCity() {
        return companyCity;
    }

    public void setCompanyCity(String companyCity) {
        this.companyCity = companyCity;
    }

    public String getOrderNumber() {
        return orderNumber;
    }

    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    public String getGuaranteeFlag() {
        return guaranteeFlag;
    }

    public void setGuaranteeFlag(String guaranteeFlag) {
        this.guaranteeFlag = guaranteeFlag;
    }

    public String getGuaranteeInsuranceName() {
        return guaranteeInsuranceName;
    }

    public void setGuaranteeInsuranceName(String guaranteeInsuranceName) {
        this.guaranteeInsuranceName = guaranteeInsuranceName;
    }

    public String getGuaranteeInsuranceType() {
        return guaranteeInsuranceType;
    }

    public void setGuaranteeInsuranceType(String guaranteeInsuranceType) {
        this.guaranteeInsuranceType = guaranteeInsuranceType;
    }

    public Date getGuaranteeEffactiveDate() {
        return guaranteeEffactiveDate;
    }

    public void setGuaranteeEffactiveDate(Date guaranteeEffactiveDate) {
        this.guaranteeEffactiveDate = guaranteeEffactiveDate;
    }
}
