package clb.core.order.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
import javax.validation.constraints.NotNull;
@ExtensionAttribute(disable=true)
@Table(name = "fms_ord_cst_education")
public class OrdCstEducation extends BaseDTO {
     @Id
     @GeneratedValue
      private Long cstEducationId;

     @NotNull
      private Long orderId;

      private Date educationTime;

      private String school;

      private String certificate;

      private String profession;

      private String fullTimeFlag;

      private Long programId;

      private Long requestId;


     public void setCstEducationId(Long cstEducationId){
         this.cstEducationId = cstEducationId;
     }

     public Long getCstEducationId(){
         return cstEducationId;
     }

     public void setOrderId(Long orderId){
         this.orderId = orderId;
     }

     public Long getOrderId(){
         return orderId;
     }

     public void setEducationTime(Date educationTime){
         this.educationTime = educationTime;
     }

     public Date getEducationTime(){
         return educationTime;
     }

     public void setSchool(String school){
         this.school = school;
     }

     public String getSchool(){
         return school;
     }

     public void setCertificate(String certificate){
         this.certificate = certificate;
     }

     public String getCertificate(){
         return certificate;
     }

     public void setProfession(String profession){
         this.profession = profession;
     }

     public String getProfession(){
         return profession;
     }

     public void setFullTimeFlag(String fullTimeFlag){
         this.fullTimeFlag = fullTimeFlag;
     }

     public String getFullTimeFlag(){
         return fullTimeFlag;
     }

     public void setProgramId(Long programId){
         this.programId = programId;
     }

     public Long getProgramId(){
         return programId;
     }

     public void setRequestId(Long requestId){
         this.requestId = requestId;
     }

     public Long getRequestId(){
         return requestId;
     }

     }
