package clb.core.order.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;

import java.security.SecureRandom;

@ExtensionAttribute(disable=true)
@Table(name = "fms_ord_file")
public class OrdFile extends BaseDTO {
    @Id
    @GeneratedValue
    private Long ordFileId;

    private Long orderId;

    private Long fileSeq;

    private Long fileId;

    private Long programId;

    private Long requestId;

    @Transient
    private String token;

    @Transient
    private String fileName;

    public void setOrdFileId(Long ordFileId){
        this.ordFileId = ordFileId;
    }

    public Long getOrdFileId(){
        return ordFileId;
    }

    public void setOrderId(Long orderId){
        this.orderId = orderId;
    }

    public Long getOrderId(){
        return orderId;
    }

    public void setFileSeq(Long fileSeq){
        this.fileSeq = fileSeq;
    }

    public Long getFileSeq(){
        return fileSeq;
    }

    public void setFileId(Long fileId){
        this.fileId = fileId;
    }

    public Long getFileId(){
        return fileId;
    }

    public void setProgramId(Long programId){
        this.programId = programId;
    }

    public Long getProgramId(){
        return programId;
    }

    public void setRequestId(Long requestId){
        this.requestId = requestId;
    }

    public Long getRequestId(){
        return requestId;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
}
