package clb.core.order.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
@ExtensionAttribute(disable=true)
@Table(name = "fms_ord_trade_route_show")
public class OrdTradeRouteShow extends BaseDTO {
     @Id
     @GeneratedValue
      private Long tradeRouteShowId;

     @NotNull
      private Long orderId;

      private Long channelCount;

      private Long supplierCount;

      private Long channelId1;

      private Long channelId2;

      private Long channelId3;

      private Long channelId4;

      private Long channelId5;

      private Long channelId6;

      private Long channelId7;

      private Long channelId8;

      private Long channelId9;

      private Long channelId10;

      private Long channelId11;

      private Long channelId12;

      private Long channelId13;

      private Long channelId14;

      private Long channelId15;

      private Long channelId16;

      private Long channelId17;

      private Long channelId18;

      private Long channelId19;

      private Long channelId20;

      private String channelName1;

      private String channelName2;

      private String channelName3;

      private String channelName4;

      private String channelName5;

      private String channelName6;

      private String channelName7;

      private String channelName8;

      private String channelName9;

      private String channelName10;

      private String channelName11;

      private String channelName12;

      private String channelName13;

      private String channelName14;

      private String channelName15;

      private String channelName16;

      private String channelName17;

      private String channelName18;

      private String channelName19;

      private String channelName20;

      private Long supplierId1;

      private Long supplierId2;

      private Long supplierId3;

      private Long supplierId4;

      private Long supplierId5;

      private Long supplierId6;

      private Long supplierId7;

      private Long supplierId8;

      private Long supplierId9;

      private Long supplierId10;

      private Long supplierId11;

      private Long supplierId12;

      private Long supplierId13;

      private Long supplierId14;

      private Long supplierId15;

      private Long supplierId16;

      private Long supplierId17;

      private Long supplierId18;

      private Long supplierId19;

      private Long supplierId20;

      private String supplierName1;

      private String supplierName2;

      private String supplierName3;

      private String supplierName4;

      private String supplierName5;

      private String supplierName6;

      private String supplierName7;

      private String supplierName8;

      private String supplierName9;

      private String supplierName10;

      private String supplierName11;

      private String supplierName12;

      private String supplierName13;

      private String supplierName14;

      private String supplierName15;

      private String supplierName16;

      private String supplierName17;

      private String supplierName18;

      private String supplierName19;

      private String supplierName20;

      private Long programId;

      private Long requestId;

      @Transient
      private String orderNumber;


     public void setTradeRouteShowId(Long tradeRouteShowId){
         this.tradeRouteShowId = tradeRouteShowId;
     }

     public Long getTradeRouteShowId(){
         return tradeRouteShowId;
     }

     public void setOrderId(Long orderId){
         this.orderId = orderId;
     }

     public Long getOrderId(){
         return orderId;
     }

     public void setChannelCount(Long channelCount){
         this.channelCount = channelCount;
     }

     public Long getChannelCount(){
         return channelCount;
     }

     public void setSupplierCount(Long supplierCount){
         this.supplierCount = supplierCount;
     }

     public Long getSupplierCount(){
         return supplierCount;
     }

     public void setChannelId1(Long channelId1){
         this.channelId1 = channelId1;
     }

     public Long getChannelId1(){
         return channelId1;
     }

     public void setChannelId2(Long channelId2){
         this.channelId2 = channelId2;
     }

     public Long getChannelId2(){
         return channelId2;
     }

     public void setChannelId3(Long channelId3){
         this.channelId3 = channelId3;
     }

     public Long getChannelId3(){
         return channelId3;
     }

     public void setChannelId4(Long channelId4){
         this.channelId4 = channelId4;
     }

     public Long getChannelId4(){
         return channelId4;
     }

     public void setChannelId5(Long channelId5){
         this.channelId5 = channelId5;
     }

     public Long getChannelId5(){
         return channelId5;
     }

     public void setChannelId6(Long channelId6){
         this.channelId6 = channelId6;
     }

     public Long getChannelId6(){
         return channelId6;
     }

     public void setChannelId7(Long channelId7){
         this.channelId7 = channelId7;
     }

     public Long getChannelId7(){
         return channelId7;
     }

     public void setChannelId8(Long channelId8){
         this.channelId8 = channelId8;
     }

     public Long getChannelId8(){
         return channelId8;
     }

     public void setChannelId9(Long channelId9){
         this.channelId9 = channelId9;
     }

     public Long getChannelId9(){
         return channelId9;
     }

     public void setChannelId10(Long channelId10){
         this.channelId10 = channelId10;
     }

     public Long getChannelId10(){
         return channelId10;
     }

     public void setChannelId11(Long channelId11){
         this.channelId11 = channelId11;
     }

     public Long getChannelId11(){
         return channelId11;
     }

     public void setChannelId12(Long channelId12){
         this.channelId12 = channelId12;
     }

     public Long getChannelId12(){
         return channelId12;
     }

     public void setChannelId13(Long channelId13){
         this.channelId13 = channelId13;
     }

     public Long getChannelId13(){
         return channelId13;
     }

     public void setChannelId14(Long channelId14){
         this.channelId14 = channelId14;
     }

     public Long getChannelId14(){
         return channelId14;
     }

     public void setChannelId15(Long channelId15){
         this.channelId15 = channelId15;
     }

     public Long getChannelId15(){
         return channelId15;
     }

     public void setChannelId16(Long channelId16){
         this.channelId16 = channelId16;
     }

     public Long getChannelId16(){
         return channelId16;
     }

     public void setChannelId17(Long channelId17){
         this.channelId17 = channelId17;
     }

     public Long getChannelId17(){
         return channelId17;
     }

     public void setChannelId18(Long channelId18){
         this.channelId18 = channelId18;
     }

     public Long getChannelId18(){
         return channelId18;
     }

     public void setChannelId19(Long channelId19){
         this.channelId19 = channelId19;
     }

     public Long getChannelId19(){
         return channelId19;
     }

     public void setChannelId20(Long channelId20){
         this.channelId20 = channelId20;
     }

     public Long getChannelId20(){
         return channelId20;
     }

     public void setChannelName1(String channelName1){
         this.channelName1 = channelName1;
     }

     public String getChannelName1(){
         return channelName1;
     }

     public void setChannelName2(String channelName2){
         this.channelName2 = channelName2;
     }

     public String getChannelName2(){
         return channelName2;
     }

     public void setChannelName3(String channelName3){
         this.channelName3 = channelName3;
     }

     public String getChannelName3(){
         return channelName3;
     }

     public void setChannelName4(String channelName4){
         this.channelName4 = channelName4;
     }

     public String getChannelName4(){
         return channelName4;
     }

     public void setChannelName5(String channelName5){
         this.channelName5 = channelName5;
     }

     public String getChannelName5(){
         return channelName5;
     }

     public void setChannelName6(String channelName6){
         this.channelName6 = channelName6;
     }

     public String getChannelName6(){
         return channelName6;
     }

     public void setChannelName7(String channelName7){
         this.channelName7 = channelName7;
     }

     public String getChannelName7(){
         return channelName7;
     }

     public void setChannelName8(String channelName8){
         this.channelName8 = channelName8;
     }

     public String getChannelName8(){
         return channelName8;
     }

     public void setChannelName9(String channelName9){
         this.channelName9 = channelName9;
     }

     public String getChannelName9(){
         return channelName9;
     }

     public void setChannelName10(String channelName10){
         this.channelName10 = channelName10;
     }

     public String getChannelName10(){
         return channelName10;
     }

     public void setChannelName11(String channelName11){
         this.channelName11 = channelName11;
     }

     public String getChannelName11(){
         return channelName11;
     }

     public void setChannelName12(String channelName12){
         this.channelName12 = channelName12;
     }

     public String getChannelName12(){
         return channelName12;
     }

     public void setChannelName13(String channelName13){
         this.channelName13 = channelName13;
     }

     public String getChannelName13(){
         return channelName13;
     }

     public void setChannelName14(String channelName14){
         this.channelName14 = channelName14;
     }

     public String getChannelName14(){
         return channelName14;
     }

     public void setChannelName15(String channelName15){
         this.channelName15 = channelName15;
     }

     public String getChannelName15(){
         return channelName15;
     }

     public void setChannelName16(String channelName16){
         this.channelName16 = channelName16;
     }

     public String getChannelName16(){
         return channelName16;
     }

     public void setChannelName17(String channelName17){
         this.channelName17 = channelName17;
     }

     public String getChannelName17(){
         return channelName17;
     }

     public void setChannelName18(String channelName18){
         this.channelName18 = channelName18;
     }

     public String getChannelName18(){
         return channelName18;
     }

     public void setChannelName19(String channelName19){
         this.channelName19 = channelName19;
     }

     public String getChannelName19(){
         return channelName19;
     }

     public void setChannelName20(String channelName20){
         this.channelName20 = channelName20;
     }

     public String getChannelName20(){
         return channelName20;
     }

     public void setSupplierId1(Long supplierId1){
         this.supplierId1 = supplierId1;
     }

     public Long getSupplierId1(){
         return supplierId1;
     }

     public void setSupplierId2(Long supplierId2){
         this.supplierId2 = supplierId2;
     }

     public Long getSupplierId2(){
         return supplierId2;
     }

     public void setSupplierId3(Long supplierId3){
         this.supplierId3 = supplierId3;
     }

     public Long getSupplierId3(){
         return supplierId3;
     }

     public void setSupplierId4(Long supplierId4){
         this.supplierId4 = supplierId4;
     }

     public Long getSupplierId4(){
         return supplierId4;
     }

     public void setSupplierId5(Long supplierId5){
         this.supplierId5 = supplierId5;
     }

     public Long getSupplierId5(){
         return supplierId5;
     }

     public void setSupplierId6(Long supplierId6){
         this.supplierId6 = supplierId6;
     }

     public Long getSupplierId6(){
         return supplierId6;
     }

     public void setSupplierId7(Long supplierId7){
         this.supplierId7 = supplierId7;
     }

     public Long getSupplierId7(){
         return supplierId7;
     }

     public void setSupplierId8(Long supplierId8){
         this.supplierId8 = supplierId8;
     }

     public Long getSupplierId8(){
         return supplierId8;
     }

     public void setSupplierId9(Long supplierId9){
         this.supplierId9 = supplierId9;
     }

     public Long getSupplierId9(){
         return supplierId9;
     }

     public void setSupplierId10(Long supplierId10){
         this.supplierId10 = supplierId10;
     }

     public Long getSupplierId10(){
         return supplierId10;
     }

     public void setSupplierId11(Long supplierId11){
         this.supplierId11 = supplierId11;
     }

     public Long getSupplierId11(){
         return supplierId11;
     }

     public void setSupplierId12(Long supplierId12){
         this.supplierId12 = supplierId12;
     }

     public Long getSupplierId12(){
         return supplierId12;
     }

     public void setSupplierId13(Long supplierId13){
         this.supplierId13 = supplierId13;
     }

     public Long getSupplierId13(){
         return supplierId13;
     }

     public void setSupplierId14(Long supplierId14){
         this.supplierId14 = supplierId14;
     }

     public Long getSupplierId14(){
         return supplierId14;
     }

     public void setSupplierId15(Long supplierId15){
         this.supplierId15 = supplierId15;
     }

     public Long getSupplierId15(){
         return supplierId15;
     }

     public void setSupplierId16(Long supplierId16){
         this.supplierId16 = supplierId16;
     }

     public Long getSupplierId16(){
         return supplierId16;
     }

     public void setSupplierId17(Long supplierId17){
         this.supplierId17 = supplierId17;
     }

     public Long getSupplierId17(){
         return supplierId17;
     }

     public void setSupplierId18(Long supplierId18){
         this.supplierId18 = supplierId18;
     }

     public Long getSupplierId18(){
         return supplierId18;
     }

     public void setSupplierId19(Long supplierId19){
         this.supplierId19 = supplierId19;
     }

     public Long getSupplierId19(){
         return supplierId19;
     }

     public void setSupplierId20(Long supplierId20){
         this.supplierId20 = supplierId20;
     }

     public Long getSupplierId20(){
         return supplierId20;
     }

     public void setSupplierName1(String supplierName1){
         this.supplierName1 = supplierName1;
     }

     public String getSupplierName1(){
         return supplierName1;
     }

     public void setSupplierName2(String supplierName2){
         this.supplierName2 = supplierName2;
     }

     public String getSupplierName2(){
         return supplierName2;
     }

     public void setSupplierName3(String supplierName3){
         this.supplierName3 = supplierName3;
     }

     public String getSupplierName3(){
         return supplierName3;
     }

     public void setSupplierName4(String supplierName4){
         this.supplierName4 = supplierName4;
     }

     public String getSupplierName4(){
         return supplierName4;
     }

     public void setSupplierName5(String supplierName5){
         this.supplierName5 = supplierName5;
     }

     public String getSupplierName5(){
         return supplierName5;
     }

     public void setSupplierName6(String supplierName6){
         this.supplierName6 = supplierName6;
     }

     public String getSupplierName6(){
         return supplierName6;
     }

     public void setSupplierName7(String supplierName7){
         this.supplierName7 = supplierName7;
     }

     public String getSupplierName7(){
         return supplierName7;
     }

     public void setSupplierName8(String supplierName8){
         this.supplierName8 = supplierName8;
     }

     public String getSupplierName8(){
         return supplierName8;
     }

     public void setSupplierName9(String supplierName9){
         this.supplierName9 = supplierName9;
     }

     public String getSupplierName9(){
         return supplierName9;
     }

     public void setSupplierName10(String supplierName10){
         this.supplierName10 = supplierName10;
     }

     public String getSupplierName10(){
         return supplierName10;
     }

     public void setSupplierName11(String supplierName11){
         this.supplierName11 = supplierName11;
     }

     public String getSupplierName11(){
         return supplierName11;
     }

     public void setSupplierName12(String supplierName12){
         this.supplierName12 = supplierName12;
     }

     public String getSupplierName12(){
         return supplierName12;
     }

     public void setSupplierName13(String supplierName13){
         this.supplierName13 = supplierName13;
     }

     public String getSupplierName13(){
         return supplierName13;
     }

     public void setSupplierName14(String supplierName14){
         this.supplierName14 = supplierName14;
     }

     public String getSupplierName14(){
         return supplierName14;
     }

     public void setSupplierName15(String supplierName15){
         this.supplierName15 = supplierName15;
     }

     public String getSupplierName15(){
         return supplierName15;
     }

     public void setSupplierName16(String supplierName16){
         this.supplierName16 = supplierName16;
     }

     public String getSupplierName16(){
         return supplierName16;
     }

     public void setSupplierName17(String supplierName17){
         this.supplierName17 = supplierName17;
     }

     public String getSupplierName17(){
         return supplierName17;
     }

     public void setSupplierName18(String supplierName18){
         this.supplierName18 = supplierName18;
     }

     public String getSupplierName18(){
         return supplierName18;
     }

     public void setSupplierName19(String supplierName19){
         this.supplierName19 = supplierName19;
     }

     public String getSupplierName19(){
         return supplierName19;
     }

     public void setSupplierName20(String supplierName20){
         this.supplierName20 = supplierName20;
     }

     public String getSupplierName20(){
         return supplierName20;
     }

     public void setProgramId(Long programId){
         this.programId = programId;
     }

     public Long getProgramId(){
         return programId;
     }

     public void setRequestId(Long requestId){
         this.requestId = requestId;
     }

     public Long getRequestId(){
         return requestId;
     }

    public String getOrderNumber() {
        return orderNumber;
    }

    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }
}
