package clb.core.order.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "fms_ord_trade_route")
public class OrdTradeRoute extends BaseDTO {
    @Id
    @GeneratedValue
    private Long tradeRouteId;

    @NotNull
    private Long orderId;

    @NotNull
    private Long seqNum;

    @NotNull
    private Long companyId;

    @NotEmpty
    private String companyType;

    private Long parentRouteId;

    private String supplierType;

    private Long channelLevel;

    private Long programId;

    private Long requestId;

    private String attribute1;
    private String attribute2;
    private String attribute3;
    private String attribute4;
    private String attribute5;
    private String attribute6;
    private String attribute7;
    private String attribute8;
    private String attribute9;
    private String attribute10;
    private String attribute11;
    private String attribute12;
    private String attribute13;
    private String attribute14;
    private String attribute15;

    @Transient
    private String companyName;

    @Transient
    private Long channelId;

    @Transient
    private Long channelCount;

    @Transient
    private String orderNumber;

    @Transient
    private Long preUserId;

    @Transient
    private String preName;

    private Long channelContractId;

    public void setTradeRouteId(Long tradeRouteId){
        this.tradeRouteId = tradeRouteId;
    }

    public Long getTradeRouteId(){
        return tradeRouteId;
    }

    public void setOrderId(Long orderId){
        this.orderId = orderId;
    }

    public Long getOrderId(){
        return orderId;
    }

    public void setSeqNum(Long seqNum){
        this.seqNum = seqNum;
    }

    public Long getSeqNum(){
        return seqNum;
    }

    public void setCompanyId(Long companyId){
        this.companyId = companyId;
    }

    public Long getCompanyId(){
        return companyId;
    }

    public void setCompanyType(String companyType){
        this.companyType = companyType;
    }

    public String getCompanyType(){
        return companyType;
    }

    public void setParentRouteId(Long parentRouteId){
        this.parentRouteId = parentRouteId;
    }

    public Long getParentRouteId(){
        return parentRouteId;
    }

    public void setSupplierType(String supplierType){
        this.supplierType = supplierType;
    }

    public String getSupplierType(){
        return supplierType;
    }

    public void setProgramId(Long programId){
        this.programId = programId;
    }

    public Long getProgramId(){
        return programId;
    }

    public void setRequestId(Long requestId){
        this.requestId = requestId;
    }

    public Long getRequestId(){
        return requestId;
    }

    @Override
    public String getAttribute1() {
        return innerGet("attribute1");
    }

    @Override
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }

    @Override
    public String getAttribute2() {
        return innerGet("attribute2");
    }

    @Override
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }

    @Override
    public String getAttribute3() {
        return innerGet("attribute3");
    }

    @Override
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    @Override
    public String getAttribute4() {
        return innerGet("attribute4");
    }

    @Override
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    @Override
    public String getAttribute5() {
        return innerGet("attribute5");
    }

    @Override
    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }

    @Override
    public String getAttribute6() {
        return innerGet("attribute6");
    }

    @Override
    public void setAttribute6(String attribute6) {
        this.attribute6 = attribute6;
    }

    @Override
    public String getAttribute7() {
        return innerGet("attribute7");
    }

    @Override
    public void setAttribute7(String attribute7) {
        this.attribute7 = attribute7;
    }

    @Override
    public String getAttribute8() {
        return innerGet("attribute8");
    }

    @Override
    public void setAttribute8(String attribute8) {
        this.attribute8 = attribute8;
    }

    @Override
    public String getAttribute9() {
        return innerGet("attribute9");
    }

    @Override
    public void setAttribute9(String attribute9) {
        this.attribute9 = attribute9;
    }

    @Override
    public String getAttribute10() {
        return innerGet("attribute10");
    }

    @Override
    public void setAttribute10(String attribute10) {
        this.attribute10 = attribute10;
    }

    @Override
    public String getAttribute11() {
        return innerGet("attribute11");
    }

    @Override
    public void setAttribute11(String attribute11) {
        this.attribute11 = attribute11;
    }

    @Override
    public String getAttribute12() {
        return innerGet("attribute12");
    }

    @Override
    public void setAttribute12(String attribute12) {
        this.attribute12 = attribute12;
    }

    @Override
    public String getAttribute13() {
        return innerGet("attribute13");
    }

    @Override
    public void setAttribute13(String attribute13) {
        this.attribute13 = attribute13;
    }

    @Override
    public String getAttribute14() {
        return innerGet("attribute14");
    }

    @Override
    public void setAttribute14(String attribute14) {
        this.attribute14 = attribute14;
    }

    @Override
    public String getAttribute15() {
        return innerGet("attribute15");
    }

    @Override
    public void setAttribute15(String attribute15) {
        this.attribute15 = attribute15;
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public Long getChannelId() {
        return channelId;
    }

    public void setChannelId(Long channelId) {
        this.channelId = channelId;
    }

    public Long getChannelCount() {
        return channelCount;
    }

    public void setChannelCount(Long channelCount) {
        this.channelCount = channelCount;
    }

    public Long getChannelLevel() {
        return channelLevel;
    }

    public void setChannelLevel(Long channelLevel) {
        this.channelLevel = channelLevel;
    }

    public String getOrderNumber() {
        return orderNumber;
    }

    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    public Long getChannelContractId() {
        return channelContractId;
    }

    public void setChannelContractId(Long channelContractId) {
        this.channelContractId = channelContractId;
    }

    public Long getPreUserId() {
        return preUserId;
    }

    public void setPreUserId(Long preUserId) {
        this.preUserId = preUserId;
    }

    public String getPreName() {
        return preName;
    }

    public void setPreName(String preName) {
        this.preName = preName;
    }
}
