package clb.core.order.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "fms_sys_order_cfg_field")
public class SysOrderCfgField extends BaseDTO {
    @Id
    @GeneratedValue
    private Long lineId;

    @NotNull
    private Long cfgId;

    @NotEmpty
    private String fieldCode;

    @NotNull
    private Long seqNum;

    private Long programId;

    private Long requestId;

    @Transient
    private String functionCode;
    
    @Transient
    private String value;
   
    @Transient
    private String meaning;
    
    public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getMeaning() {
		return meaning;
	}

	public void setMeaning(String meaning) {
		this.meaning = meaning;
	}

	public void setLineId(Long lineId){
        this.lineId = lineId;
    }

    public Long getLineId(){
        return lineId;
    }

    public void setCfgId(Long cfgId){
        this.cfgId = cfgId;
    }

    public Long getCfgId(){
        return cfgId;
    }

    public void setFieldCode(String fieldCode){
        this.fieldCode = fieldCode;
    }

    public String getFieldCode(){
        return fieldCode;
    }

    public void setSeqNum(Long seqNum){
        this.seqNum = seqNum;
    }

    public Long getSeqNum(){
        return seqNum;
    }

    public void setProgramId(Long programId){
        this.programId = programId;
    }

    public Long getProgramId(){
        return programId;
    }

    public void setRequestId(Long requestId){
        this.requestId = requestId;
    }

    public Long getRequestId(){
        return requestId;
    }

    public String getFunctionCode() {
        return functionCode;
    }

    public void setFunctionCode(String functionCode) {
        this.functionCode = functionCode;
    }
}
