package clb.core.order.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "fms_sys_page_field_cfg")
public class SysPageFieldCfg extends BaseDTO {
     @Id
     @GeneratedValue
      private Long lineId;
     
     @Transient
     private Long id;

     @NotEmpty
      private String roleCode;

     @NotEmpty
      private String resourceType;

     @NotEmpty
      private String resourceId;

      private String queryFlag;

      private String updateFlag;

      private Long parentLineId;

      private Long programId;

      private Long requestId;
      
      @Transient
      private String value;
      
      @Transient
      private String meaning;
      
      @Transient
      private String parentMeaning;

     public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getParentMeaning() {
		return parentMeaning;
	}

	public void setParentMeaning(String parentMeaning) {
		this.parentMeaning = parentMeaning;
	}

	public void setLineId(Long lineId){
         this.lineId = lineId;
     }

     public Long getLineId(){
         return lineId;
     }

     public void setRoleCode(String roleCode){
         this.roleCode = roleCode;
     }

     public String getRoleCode(){
         return roleCode;
     }

     public void setResourceType(String resourceType){
         this.resourceType = resourceType;
     }

     public String getResourceType(){
         return resourceType;
     }

     public void setQueryFlag(String queryFlag){
         this.queryFlag = queryFlag;
     }

     public String getQueryFlag(){
         return queryFlag;
     }

     public void setUpdateFlag(String updateFlag){
         this.updateFlag = updateFlag;
     }

     public String getUpdateFlag(){
         return updateFlag;
     }

     public void setParentLineId(Long parentLineId){
         this.parentLineId = parentLineId;
     }

     public Long getParentLineId(){
         return parentLineId;
     }

     public void setProgramId(Long programId){
         this.programId = programId;
     }

     public Long getProgramId(){
         return programId;
     }

     public void setRequestId(Long requestId){
         this.requestId = requestId;
     }

     public Long getRequestId(){
         return requestId;
     }

	public String getResourceId() {
		return resourceId;
	}

	public void setResourceId(String resourceId) {
		this.resourceId = resourceId;
	}

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getMeaning() {
		return meaning;
	}

	public void setMeaning(String meaning) {
		this.meaning = meaning;
	}
}
