package clb.core.sys.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "sys_if_invoke_outbound")
public class IfInvokeOutbound extends BaseDTO {
     @Id
     @GeneratedValue
      private Long outboundId;

     @NotEmpty
      private String interfaceName;

     @NotEmpty
      private String interfaceUrl;

      private Date requestTime;

      private String requestParameter;

      private String requestStatus;

      private String responseContent;

      private Long responseTime;

      private String responseCode;

      private String stacktrace;


     public void setOutboundId(Long outboundId){
         this.outboundId = outboundId;
     }

     public Long getOutboundId(){
         return outboundId;
     }

     public void setInterfaceName(String interfaceName){
         this.interfaceName = interfaceName;
     }

     public String getInterfaceName(){
         return interfaceName;
     }

     public void setInterfaceUrl(String interfaceUrl){
         this.interfaceUrl = interfaceUrl;
     }

     public String getInterfaceUrl(){
         return interfaceUrl;
     }

     public void setRequestTime(Date requestTime){
         this.requestTime = requestTime;
     }

     public Date getRequestTime(){
         return requestTime;
     }

     public void setRequestParameter(String requestParameter){
         this.requestParameter = requestParameter;
     }

     public String getRequestParameter(){
         return requestParameter;
     }

     public void setRequestStatus(String requestStatus){
         this.requestStatus = requestStatus;
     }

     public String getRequestStatus(){
         return requestStatus;
     }

     public void setResponseContent(String responseContent){
         this.responseContent = responseContent;
     }

     public String getResponseContent(){
         return responseContent;
     }

     public void setResponseTime(Long responseTime){
         this.responseTime = responseTime;
     }

     public Long getResponseTime(){
         return responseTime;
     }

     public void setResponseCode(String responseCode){
         this.responseCode = responseCode;
     }

     public String getResponseCode(){
         return responseCode;
     }

     public void setStacktrace(String stacktrace){
         this.stacktrace = stacktrace;
     }

     public String getStacktrace(){
         return stacktrace;
     }

     }
