package clb.core.sys.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "sys_if_invoke_inbound")
public class IfInvokeInbound extends BaseDTO {
     @Id
     @GeneratedValue
      private Long inboundId;

     @NotEmpty
      private String interfaceName;

     @NotEmpty
      private String interfaceUrl;

      private Date requestTime;

      private String requestHeaderParameter;

      private String requestBodyParameter;

      private String requestMethod;

      private String requestStatus;

      private String responseContent;

      private Long responseTime;

      private String stacktrace;

      private String ip;

      private String referer;

      private String userAgent;


     public void setInboundId(Long inboundId){
         this.inboundId = inboundId;
     }

     public Long getInboundId(){
         return inboundId;
     }

     public void setInterfaceName(String interfaceName){
         this.interfaceName = interfaceName;
     }

     public String getInterfaceName(){
         return interfaceName;
     }

     public void setInterfaceUrl(String interfaceUrl){
         this.interfaceUrl = interfaceUrl;
     }

     public String getInterfaceUrl(){
         return interfaceUrl;
     }

     public void setRequestTime(Date requestTime){
         this.requestTime = requestTime;
     }

     public Date getRequestTime(){
         return requestTime;
     }

     public void setRequestHeaderParameter(String requestHeaderParameter){
         this.requestHeaderParameter = requestHeaderParameter;
     }

     public String getRequestHeaderParameter(){
         return requestHeaderParameter;
     }

     public void setRequestBodyParameter(String requestBodyParameter){
         this.requestBodyParameter = requestBodyParameter;
     }

     public String getRequestBodyParameter(){
         return requestBodyParameter;
     }

     public void setRequestMethod(String requestMethod){
         this.requestMethod = requestMethod;
     }

     public String getRequestMethod(){
         return requestMethod;
     }

     public void setRequestStatus(String requestStatus){
         this.requestStatus = requestStatus;
     }

     public String getRequestStatus(){
         return requestStatus;
     }

     public void setResponseContent(String responseContent){
         this.responseContent = responseContent;
     }

     public String getResponseContent(){
         return responseContent;
     }

     public void setResponseTime(Long responseTime){
         this.responseTime = responseTime;
     }

     public Long getResponseTime(){
         return responseTime;
     }

     public void setStacktrace(String stacktrace){
         this.stacktrace = stacktrace;
     }

     public String getStacktrace(){
         return stacktrace;
     }

     public void setIp(String ip){
         this.ip = ip;
     }

     public String getIp(){
         return ip;
     }

     public void setReferer(String referer){
         this.referer = referer;
     }

     public String getReferer(){
         return referer;
     }

     public void setUserAgent(String userAgent){
         this.userAgent = userAgent;
     }

     public String getUserAgent(){
         return userAgent;
     }

     }
