package clb.core.forecast.dto;

import javax.persistence.Column;
/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;

import clb.core.common.annotations.Title;

import java.math.BigDecimal;
import java.util.Date;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "fms_fet_actual_payment")
public class FetActualPayment extends BaseDTO {
     @Id
     @GeneratedValue
     private Long paymentId;

     @NotNull
     private Long paymentSummaryId;

     @NotEmpty
     private String paymentType;

     @NotNull
     @Column
     private Long orderId;
     
     @NotNull
     @Column
     private Long itemId;
     
     //币种
     private String orderCurrency;

     //金额
     private BigDecimal amount;

     @NotNull
     @Column
     private BigDecimal rate;

     @NotNull
     @Column
     private BigDecimal exchangeRate;

     @NotNull
     @Column
     private BigDecimal hkdAmount;
     
     @NotNull
     @Column
     private Date actualDate;


     @Column
     private String comments;
     
     //订单编号
     @Transient
     private String orderNumber;
     
     //产品名称
     @Transient
     private String itemName;
     
     //供款期
     @Transient
     private String contributionPeriod;
     
     //投保人
     @Transient
     private String applicantName;

	public Long getPaymentId() {
		return paymentId;
	}

	public void setPaymentId(Long paymentId) {
		this.paymentId = paymentId;
	}

	public Long getPaymentSummaryId() {
		return paymentSummaryId;
	}

	public void setPaymentSummaryId(Long paymentSummaryId) {
		this.paymentSummaryId = paymentSummaryId;
	}

	public String getPaymentType() {
		return paymentType;
	}

	public void setPaymentType(String paymentType) {
		this.paymentType = paymentType;
	}

	public Long getOrderId() {
		return orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	public String getOrderCurrency() {
		return orderCurrency;
	}

	public void setOrderCurrency(String orderCurrency) {
		this.orderCurrency = orderCurrency;
	}

	public BigDecimal getAmount() {
		return amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public BigDecimal getRate() {
		return rate;
	}

	public void setRate(BigDecimal rate) {
		this.rate = rate;
	}

	public BigDecimal getExchangeRate() {
		return exchangeRate;
	}

	public void setExchangeRate(BigDecimal exchangeRate) {
		this.exchangeRate = exchangeRate;
	}

	public BigDecimal getHkdAmount() {
		return hkdAmount;
	}

	public void setHkdAmount(BigDecimal hkdAmount) {
		this.hkdAmount = hkdAmount;
	}

	public String getComments() {
		return comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getOrderNumber() {
		return orderNumber;
	}

	public void setOrderNumber(String orderNumber) {
		this.orderNumber = orderNumber;
	}

	public String getItemName() {
		return itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public String getContributionPeriod() {
		return contributionPeriod;
	}

	public void setContributionPeriod(String contributionPeriod) {
		this.contributionPeriod = contributionPeriod;
	}

	public String getApplicantName() {
		return applicantName;
	}

	public void setApplicantName(String applicantName) {
		this.applicantName = applicantName;
	}

	public Date getActualDate() {
		return actualDate;
	}

	public void setActualDate(Date actualDate) {
		this.actualDate = actualDate;
	}

	public Long getItemId() {
		return itemId;
	}

	public void setItemId(Long itemId) {
		this.itemId = itemId;
	}

    
     

	
}
