package clb.core.forecast.dto;

import java.math.BigDecimal;
import java.util.Date;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;

import clb.core.common.annotations.Title;

import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "fms_fet_actual_receipt_summary")
public class FetActualReceiptSummary extends BaseDTO {
     @Id
     @GeneratedValue
      private Long receiptSummaryId;

     @NotEmpty
     @Title(title="fet.actual.receipt.receiptperiod",index=1)
      private String receiptPeriod;
     
     @Transient
     @Title(title="fet.actual.receipt.receivecompanyname",index=2)
     private String receiveSupplierName;
     
     @Transient
     @Title(title="fet.actual.receipt.paymentcompanyname",index=3)
     private String paymentSupplierName;

     //收入类型
     @Transient
     @Title(title="fet.actual.receipt.receipttype",index=4)
      private String receiptType;
     

     //订单编号
     @Transient
     @Title(title="fet.actual.receipt.orderNumber",index=5)
     private String orderNumber;
     
     //产品名称
     @Transient
     @Title(title="fet.actual.payment.itemName",index=6)
     private String itemName;
     
     //币种
     @Transient
     @Title(title="fet.actual.receipt.ordercurrency",index=7)
     private String orderCurrency;

     //金额
     @Transient
     @Title(title="fet.actual.receipt.amount",index=8)
     private BigDecimal amount;

     @Transient
     @Title(title="fet.actual.receipt.rate",index=9)
      private BigDecimal rate;

     @Transient
     @Title(title="fet.actual.receipt.exchangerate",index=10)
      private BigDecimal exchangeRate;
     
     @Transient
     @Title(title="fet.actual.receipt.actualdate",index=11)
     private Date actualDate;

     @Transient
     @Title(title="fet.actual.receipt.comments",index=12)
     private String comments;
     
     @Transient
     private Long orderId;
     
     @NotNull
      private Long receiveSupplierId;

     @NotNull
      private Long paymentSupplierId;

     @NotNull
      private Long version;

      private BigDecimal hkdAmount;

      private Long certificateFileId;
      
      private Long programId;

      private Long requestId;
      
      
      
      @Transient
      private String fileToken;
      
      @Transient
      private Long oldFileId;
      
      @Transient
      private Long itemId;



     public void setReceiptSummaryId(Long receiptSummaryId){
         this.receiptSummaryId = receiptSummaryId;
     }

     public Long getReceiptSummaryId(){
         return receiptSummaryId;
     }

     public void setReceiptPeriod(String receiptPeriod){
         this.receiptPeriod = receiptPeriod;
     }

     public String getReceiptPeriod(){
         return receiptPeriod;
     }

     public void setReceiveSupplierId(Long receiveSupplierId){
         this.receiveSupplierId = receiveSupplierId;
     }

     public Long getReceiveSupplierId(){
         return receiveSupplierId;
     }

     public void setPaymentSupplierId(Long paymentSupplierId){
         this.paymentSupplierId = paymentSupplierId;
     }

     public Long getPaymentSupplierId(){
         return paymentSupplierId;
     }

     public void setVersion(Long version){
         this.version = version;
     }

     public Long getVersion(){
         return version;
     }
     
     

     public BigDecimal getHkdAmount() {
		return hkdAmount;
	}

	public void setHkdAmount(BigDecimal hkdAmount) {
		this.hkdAmount = hkdAmount;
	}

	public void setCertificateFileId(Long certificateFileId){
         this.certificateFileId = certificateFileId;
     }

     public Long getCertificateFileId(){
         return certificateFileId;
     }

     public void setProgramId(Long programId){
         this.programId = programId;
     }

     public Long getProgramId(){
         return programId;
     }

     public void setRequestId(Long requestId){
         this.requestId = requestId;
     }

     public Long getRequestId(){
         return requestId;
     }

	public String getReceiveSupplierName() {
		return receiveSupplierName;
	}

	public void setReceiveSupplierName(String receiveSupplierName) {
		this.receiveSupplierName = receiveSupplierName;
	}

	public String getPaymentSupplierName() {
		return paymentSupplierName;
	}

	public void setPaymentSupplierName(String paymentSupplierName) {
		this.paymentSupplierName = paymentSupplierName;
	}

	public Long getOldFileId() {
		return oldFileId;
	}

	public void setOldFileId(Long oldFileId) {
		this.oldFileId = oldFileId;
	}

	public String getFileToken() {
		return fileToken;
	}

	public void setFileToken(String fileToken) {
		this.fileToken = fileToken;
	}

	public String getReceiptType() {
		return receiptType;
	}

	public void setReceiptType(String receiptType) {
		this.receiptType = receiptType;
	}

	public String getOrderNumber() {
		return orderNumber;
	}

	public void setOrderNumber(String orderNumber) {
		this.orderNumber = orderNumber;
	}

	public String getOrderCurrency() {
		return orderCurrency;
	}

	public void setOrderCurrency(String orderCurrency) {
		this.orderCurrency = orderCurrency;
	}

	public BigDecimal getAmount() {
		return amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public BigDecimal getRate() {
		return rate;
	}

	public void setRate(BigDecimal rate) {
		this.rate = rate;
	}

	public BigDecimal getExchangeRate() {
		return exchangeRate;
	}

	public void setExchangeRate(BigDecimal exchangeRate) {
		this.exchangeRate = exchangeRate;
	}

	public Date getActualDate() {
		return actualDate;
	}

	public void setActualDate(Date actualDate) {
		this.actualDate = actualDate;
	}

	public String getComments() {
		return comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Long getOrderId() {
		return orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	public String getItemName() {
		return itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public Long getItemId() {
		return itemId;
	}

	public void setItemId(Long itemId) {
		this.itemId = itemId;
	}
     
	
    

}
