package clb.core.forecast.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.mybatis.annotation.Condition;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;

@ExtensionAttribute(disable = true)
@Table(name = "fms_fet_period")
public class FetPeriod extends BaseDTO {
	@Id
	@GeneratedValue
	private Long periodId;

	@Condition(operator = "LIKE")
	@NotEmpty
	private String periodName;

	@NotEmpty
	private Long headId;

	@NotNull
	private Long year;
	
	@NotEmpty
	private Date startDate;
	
	@NotEmpty
	private Date endDate;

	@NotEmpty
	private String statusCode;

	private String updateFlag;

	@NotEmpty
	private Integer quarter;

	@NotEmpty
	private Integer adjustFlag;

	@Transient
	private Long partyId;

	@Transient
	private String partyType;

	private Long programId;

	private Long requestId;

	public Long getPartyId() {
		return partyId;
	}

	public void setPartyId(Long partyId) {
		this.partyId = partyId;
	}

	public String getPartyType() {
		return partyType;
	}

	public void setPartyType(String partyType) {
		this.partyType = partyType;
	}

	public String getUpdateFlag() {
		return updateFlag;
	}

	public void setUpdateFlag(String updateFlag) {
		this.updateFlag = updateFlag;
	}

	public Integer getQuarter() {
		return quarter;
	}

	public void setQuarter(Integer quarter) {
		this.quarter = quarter;
	}

	public Integer getAdjustFlag() {
		return adjustFlag;
	}

	public void setAdjustFlag(Integer adjustFlag) {
		this.adjustFlag = adjustFlag;
	}

	public void setPeriodId(Long periodId) {
		this.periodId = periodId;
	}

	public Long getPeriodId() {
		return periodId;
	}

	public void setPeriodName(String periodName) {
		this.periodName = periodName;
	}

	public String getPeriodName() {
		return periodName;
	}

	public void setYear(Long year) {
		this.year = year;
	}

	public Long getYear() {
		return year;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setStatusCode(String statusCode) {
		this.statusCode = statusCode;
	}

	public String getStatusCode() {
		return statusCode;
	}

	public void setProgramId(Long programId) {
		this.programId = programId;
	}

	public Long getProgramId() {
		return programId;
	}

	public void setRequestId(Long requestId) {
		this.requestId = requestId;
	}

	public Long getRequestId() {
		return requestId;
	}

	public Long getHeadId() {
		return headId;
	}

	public void setHeadId(Long headId) {
		this.headId = headId;
	}
}
