package clb.core.forecast.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.hand.hap.attachment.dto.SysFile;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
import java.util.List;

import javax.validation.constraints.NotNull;
@ExtensionAttribute(disable=true)
@Table(name = "fms_fet_question_line")
public class FetQuestionLine extends BaseDTO {
     @Id
     @GeneratedValue
      private Long questionLineId;

     @NotNull
      private Long questionId;

      private String content;

      @JsonFormat(pattern = "yyyy-MM-dd HH:mm")
      private Date submitDate;
      
      @Transient
      private Boolean isRight;
      @Transient
      private String userName;
      
      @Transient
      private List<SysFile> attaches;

     public void setQuestionLineId(Long questionLineId){
         this.questionLineId = questionLineId;
     }

     public Long getQuestionLineId(){
         return questionLineId;
     }

     public void setQuestionId(Long questionId){
         this.questionId = questionId;
     }

     public Long getQuestionId(){
         return questionId;
     }

     public void setContent(String content){
         this.content = content;
     }

     public String getContent(){
         return content;
     }

     public void setSubmitDate(Date submitDate){
         this.submitDate = submitDate;
     }

     public Date getSubmitDate(){
         return submitDate;
     }
     
    public Boolean getIsRight() {
		return isRight;
	}

	public void setIsRight(Boolean isRight) {
		this.isRight = isRight;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public List<SysFile> getAttaches() {
		return attaches;
	}

	public void setAttaches(List<SysFile> attaches) {
		this.attaches = attaches;
	}

	
     

}
