package clb.core.forecast.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;

import javax.persistence.Table;

import com.hand.hap.system.dto.BaseDTO;

import java.math.BigDecimal;
import java.util.Date;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotEmpty;

@ExtensionAttribute(disable = true)
@Table(name = "fms_fet_time_receivable")
public class FetTimeReceivable extends BaseDTO {
    @Id
    @GeneratedValue
    private Long receivableId;

    @NotEmpty
    private String receiptPeriod;

    @NotEmpty
    private String paymentCompanyType;

    @NotEmpty
    private String receiveCompanyType;

    @NotNull
    private Long paymentCompanyId;

    @NotNull
    private Long receiveCompanyId;

    @NotEmpty
    private String receiptType;

    @NotNull
    private Long orderId;

    @NotNull
    private Long itemId;

    @NotEmpty
    private String orderCurrency;

    private BigDecimal amount;

    private BigDecimal rate;

    private BigDecimal exchangeRate;

    private BigDecimal hkdAmount;

    private Date dueDate;

    private Long version;

    private String comments;

    private Long programId;

    private Long requestId;


    public void setReceivableId(Long receivableId) {
        this.receivableId = receivableId;
    }

    public Long getReceivableId() {
        return receivableId;
    }

    public void setReceiptPeriod(String receiptPeriod) {
        this.receiptPeriod = receiptPeriod;
    }

    public String getReceiptPeriod() {
        return receiptPeriod;
    }

    public void setPaymentCompanyType(String paymentCompanyType) {
        this.paymentCompanyType = paymentCompanyType;
    }

    public String getPaymentCompanyType() {
        return paymentCompanyType;
    }

    public void setReceiveCompanyType(String receiveCompanyType) {
        this.receiveCompanyType = receiveCompanyType;
    }

    public String getReceiveCompanyType() {
        return receiveCompanyType;
    }

    public void setPaymentCompanyId(Long paymentCompanyId) {
        this.paymentCompanyId = paymentCompanyId;
    }

    public Long getPaymentCompanyId() {
        return paymentCompanyId;
    }

    public void setReceiveCompanyId(Long receiveCompanyId) {
        this.receiveCompanyId = receiveCompanyId;
    }

    public Long getReceiveCompanyId() {
        return receiveCompanyId;
    }

    public void setReceiptType(String receiptType) {
        this.receiptType = receiptType;
    }

    public String getReceiptType() {
        return receiptType;
    }

    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    public Long getOrderId() {
        return orderId;
    }

    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    public Long getItemId() {
        return itemId;
    }

    public void setOrderCurrency(String orderCurrency) {
        this.orderCurrency = orderCurrency;
    }

    public String getOrderCurrency() {
        return orderCurrency;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    public BigDecimal getRate() {
        return rate;
    }

    public void setExchangeRate(BigDecimal exchangeRate) {
        this.exchangeRate = exchangeRate;
    }

    public BigDecimal getExchangeRate() {
        return exchangeRate;
    }

    public void setHkdAmount(BigDecimal hkdAmount) {
        this.hkdAmount = hkdAmount;
    }

    public BigDecimal getHkdAmount() {
        return hkdAmount;
    }

    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    public Date getDueDate() {
        return dueDate;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    public Long getVersion() {
        return version;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public String getComments() {
        return comments;
    }

    public void setProgramId(Long programId) {
        this.programId = programId;
    }

    public Long getProgramId() {
        return programId;
    }

    public void setRequestId(Long requestId) {
        this.requestId = requestId;
    }

    public Long getRequestId() {
        return requestId;
    }

}
