package clb.core.exchangeRate.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "fms_fet_exchange_rate")
public class FetExchangeRate extends BaseDTO {
     @Id
     @GeneratedValue
      private Long rateId;

     @NotEmpty
      private String foreignCurrency;

     @NotEmpty
      private String baseCurrency;

      private Double rate;

      private Date effectiveDateFrom;

      private Date effectiveDateTo;

      private Long programId;

      private Long requestId;
      @Transient
      private Date currentTime;
      
     public Date getCurrentTime() {
		return currentTime;
	}

	public void setCurrentTime(Date currentTime) {
		this.currentTime = currentTime;
	}

	public void setRateId(Long rateId){
         this.rateId = rateId;
     }

     public Long getRateId(){
         return rateId;
     }

     public void setForeignCurrency(String foreignCurrency){
         this.foreignCurrency = foreignCurrency;
     }

     public String getForeignCurrency(){
         return foreignCurrency;
     }

     public void setBaseCurrency(String baseCurrency){
         this.baseCurrency = baseCurrency;
     }

     public String getBaseCurrency(){
         return baseCurrency;
     }

     public void setRate(Double rate){
         this.rate = rate;
     }

     public Double getRate(){
         return rate;
     }

     public void setEffectiveDateFrom(Date effectiveDateFrom){
         this.effectiveDateFrom = effectiveDateFrom;
     }

     public Date getEffectiveDateFrom(){
         return effectiveDateFrom;
     }

     public void setEffectiveDateTo(Date effectiveDateTo){
         this.effectiveDateTo = effectiveDateTo;
     }

     public Date getEffectiveDateTo(){
         return effectiveDateTo;
     }

     public void setProgramId(Long programId){
         this.programId = programId;
     }

     public Long getProgramId(){
         return programId;
     }

     public void setRequestId(Long requestId){
         this.requestId = requestId;
     }

     public Long getRequestId(){
         return requestId;
     }

     }
