package clb.core.question.dto;

import java.util.Date;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "fms_qa_consult_line")
public class QaConsultLine extends BaseDTO {
     @Id
     @GeneratedValue
      private Long lineId;

     @NotNull
      private Long consultId;
     
     @Transient
	  private Date statusDate;
     
     @Transient
	  private String orderId;
     
     @Transient
	  private String newAnswer;
     
     @Transient
	  private String newfileId;
     
     @Transient
     private String flag;
     
     @NotEmpty
      private String question;

      private String answer;

      private Long questionFileId;

      private Long answerFileId;

     @Transient
     private String questionFilePath;

     @Transient
     private String answerFilePath;
     
     @Transient
     private Long downloadFileId;
     
     @Transient
     private Date lastUpdateDate;

      private Long programId;

      private Long requestId;
    
	public Date getLastUpdateDate() {
		return lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public Long getDownloadFileId() {
		return downloadFileId;
	}

	public void setDownloadFileId(Long downloadFileId) {
		this.downloadFileId = downloadFileId;
	}

	public String getFlag() {
		return flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public String getNewfileId() {
		return newfileId;
	}

	public void setNewfileId(String newfileId) {
		this.newfileId = newfileId;
	}

	public String getNewAnswer() {
		return newAnswer;
	}

	public void setNewAnswer(String newAnswer) {
		this.newAnswer = newAnswer;
	}

	public Date getStatusDate() {
		return statusDate;
	}

	public void setStatusDate(Date statusDate) {
		this.statusDate = statusDate;
	}

	public String getOrderId() {
		return orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public void setLineId(Long lineId){
         this.lineId = lineId;
     }

     public Long getLineId(){
         return lineId;
     }

     public void setConsultId(Long consultId){
         this.consultId = consultId;
     }

     public Long getConsultId(){
         return consultId;
     }

     public void setQuestion(String question){
         this.question = question;
     }

     public String getQuestion(){
         return question;
     }

     public void setAnswer(String answer){
         this.answer = answer;
     }

     public String getAnswer(){
         return answer;
     }

     public void setQuestionFileId(Long questionFileId){
         this.questionFileId = questionFileId;
     }

     public Long getQuestionFileId(){
         return questionFileId;
     }

     public void setAnswerFileId(Long answerFileId){
         this.answerFileId = answerFileId;
     }

     public Long getAnswerFileId(){
         return answerFileId;
     }

     public void setProgramId(Long programId){
         this.programId = programId;
     }

     public Long getProgramId(){
         return programId;
     }

     public void setRequestId(Long requestId){
         this.requestId = requestId;
     }

     public Long getRequestId(){
         return requestId;
     }

    public String getQuestionFilePath() {
        return questionFilePath;
    }

    public void setQuestionFilePath(String questionFilePath) {
        this.questionFilePath = questionFilePath;
    }

    public String getAnswerFilePath() {
        return answerFilePath;
    }

    public void setAnswerFilePath(String answerFilePath) {
        this.answerFilePath = answerFilePath;
    }
}
