package clb.core.question.dto;

import java.util.List;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.mybatis.annotation.Condition;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "fms_qa_guideline")
public class QaGuideline extends BaseDTO {
     @Id
     @GeneratedValue
      private Long guidelineId;

     @NotEmpty
     @Condition(operator="LIKE")
      private String guidelineName;

      private String comments;
      
      @Transient 
      private List<QaGuidelineFile> fileGrid;

      private Long programId;

      private Long requestId;


     public void setGuidelineId(Long guidelineId){
         this.guidelineId = guidelineId;
     }

     public Long getGuidelineId(){
         return guidelineId;
     }

     public void setGuidelineName(String guidelineName){
         this.guidelineName = guidelineName;
     }

     public String getGuidelineName(){
         return guidelineName;
     }

     public void setComments(String comments){
         this.comments = comments;
     }

     public String getComments(){
         return comments;
     }

     public void setProgramId(Long programId){
         this.programId = programId;
     }

     public Long getProgramId(){
         return programId;
     }

     public void setRequestId(Long requestId){
         this.requestId = requestId;
     }

     public Long getRequestId(){
         return requestId;
     }

	public List<QaGuidelineFile> getFileGrid() {
		return fileGrid;
	}

	public void setFileGrid(List<QaGuidelineFile> fileGrid) {
		this.fileGrid = fileGrid;
	}

     }
