package clb.core.question.dto;

import javax.persistence.Column;
/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.mybatis.annotation.Condition;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

@ExtensionAttribute(disable = true)
@Table(name = "fms_qa_question")
public class QaQuestion extends BaseDTO {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue
	@Column
	private Long questionId;


	@NotEmpty
	@Column
	private String questionType;

	@NotEmpty
	@Column
	@Condition(operator="LIKE")
	private String questionName;

	@Column
	private String comments;

	@Column
	private String solution;

	@Column
	private Long programId;

	@Column
	private Long requestId;

	public void setQuestionId(Long questionId) {
		this.questionId = questionId;
	}

	public Long getQuestionId() {
		return questionId;
	}

	public void setQuestionType(String questionType) {
		this.questionType = questionType;
	}

	public String getQuestionType() {
		return questionType;
	}

	public void setQuestionName(String questionName) {
		this.questionName = questionName;
	}

	public String getQuestionName() {
		return questionName;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getComments() {
		return comments;
	}

	public void setSolution(String solution) {
		this.solution = solution;
	}

	public String getSolution() {
		return solution;
	}

	public void setProgramId(Long programId) {
		this.programId = programId;
	}

	public Long getProgramId() {
		return programId;
	}

	public void setRequestId(Long requestId) {
		this.requestId = requestId;
	}

	public Long getRequestId() {
		return requestId;
	}

}
