package clb.core.question.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "fms_qa_question_consult")
public class QaQuestionConsult extends BaseDTO {
     @Id
     @GeneratedValue
      private Long consultId;

     @NotNull
      private Long orderId;

     @NotNull
      private Long userId;
     
      /**
 	  * 用户名
 	  */
 	  @Transient
 	  private String userName;
 	  
     @NotEmpty
      private String contactPersonName;
     
      private String phoneCode;
     
     @NotEmpty
      private String contactNumber;

      private String emailAddress;

      private Long channelId;

      private String channelRelation;
      
      private Date questionDate;

      @NotEmpty
      private String questionType;

      @NotEmpty
      private String questionDescription;

      @NotEmpty
      private String answerStatus;

      @NotEmpty
      private String solveFlag;
     
      private Date answerDate;

      private Long fileId;

      private Long programId;

      private Long requestId;

      @Transient
 	  private String answerTo;
      
      @Transient
 	  private String answerFrom;
      
      @Transient
 	  private String questionTo;
      
      @Transient
 	  private String questionFrom;
      
      @Transient
      private String questionDescriptionTemp;
      
      @Transient
      private String orderNumber;
      
      @Transient
  	  private String channelName;
      
      @Transient
      private String contactPhoneComb;
      
    public String getPhoneCode() {
		return phoneCode;
	}

	public void setPhoneCode(String phoneCode) {
		this.phoneCode = phoneCode;
	}

	public String getContactPhoneComb() {
		return contactPhoneComb;
	}

	public void setContactPhoneComb(String contactPhoneComb) {
		this.contactPhoneComb = contactPhoneComb;
	}

	public String getQuestionDescriptionTemp() {
		return questionDescriptionTemp;
	}

	public void setQuestionDescriptionTemp(String questionDescriptionTemp) {
		this.questionDescriptionTemp = questionDescriptionTemp;
	}

	public String getChannelName() {
		return channelName;
	}

	public void setChannelName(String channelName) {
		this.channelName = channelName;
	}

	public String getOrderNumber() {
		return orderNumber;
	}

	public void setOrderNumber(String orderNumber) {
		this.orderNumber = orderNumber;
	}

	public String getAnswerTo() {
		return answerTo;
	}

	public void setAnswerTo(String answerTo) {
		this.answerTo = answerTo;
	}

	public String getAnswerFrom() {
		return answerFrom;
	}

	public void setAnswerFrom(String answerFrom) {
		this.answerFrom = answerFrom;
	}

	public String getQuestionTo() {
		return questionTo;
	}

	public void setQuestionTo(String questionTo) {
		this.questionTo = questionTo;
	}

	public String getQuestionFrom() {
		return questionFrom;
	}

	public void setQuestionFrom(String questionFrom) {
		this.questionFrom = questionFrom;
	}

	public void setConsultId(Long consultId){
         this.consultId = consultId;
     }

     public Long getConsultId(){
         return consultId;
     }

     public void setOrderId(Long orderId){
         this.orderId = orderId;
     }

     public Long getOrderId(){
         return orderId;
     }

     public void setUserId(Long userId){
         this.userId = userId;
     }

     public Long getUserId(){
         return userId;
     }
     
     public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public void setContactPersonName(String contactPersonName){
         this.contactPersonName = contactPersonName;
     }

     public String getContactPersonName(){
         return contactPersonName;
     }

     public void setContactNumber(String contactNumber){
         this.contactNumber = contactNumber;
     }

     public String getContactNumber(){
         return contactNumber;
     }

     public void setEmailAddress(String emailAddress){
         this.emailAddress = emailAddress;
     }

     public String getEmailAddress(){
         return emailAddress;
     }

     public void setChannelId(Long channelId){
         this.channelId = channelId;
     }

     public Long getChannelId(){
         return channelId;
     }

     public void setChannelRelation(String channelRelation){
         this.channelRelation = channelRelation;
     }

     public String getChannelRelation(){
         return channelRelation;
     }

     public void setQuestionDate(Date questionDate){
         this.questionDate = questionDate;
     }

     public Date getQuestionDate(){
         return questionDate;
     }

     public void setQuestionType(String questionType){
         this.questionType = questionType;
     }

     public String getQuestionType(){
         return questionType;
     }

     public void setQuestionDescription(String questionDescription){
         this.questionDescription = questionDescription;
     }

     public String getQuestionDescription(){
         return questionDescription;
     }

     public void setAnswerStatus(String answerStatus){
         this.answerStatus = answerStatus;
     }

     public String getAnswerStatus(){
         return answerStatus;
     }

     public void setSolveFlag(String solveFlag){
         this.solveFlag = solveFlag;
     }

     public String getSolveFlag(){
         return solveFlag;
     }

     public void setAnswerDate(Date answerDate){
         this.answerDate = answerDate;
     }

     public Date getAnswerDate(){
         return answerDate;
     }

     public void setFileId(Long fileId){
         this.fileId = fileId;
     }

     public Long getFileId(){
         return fileId;
     }

     public void setProgramId(Long programId){
         this.programId = programId;
     }

     public Long getProgramId(){
         return programId;
     }

     public void setRequestId(Long requestId){
         this.requestId = requestId;
     }

     public Long getRequestId(){
         return requestId;
     }

     }
