package clb.core.prc.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "fms_prc_radar_line_detail")
public class PrcRadarLineDetail extends BaseDTO {
     @Id
     @GeneratedValue
      private Long detailId;

     @NotNull
      private Long serialNumber;

     @NotEmpty
      private String detailName;

     @NotEmpty
      private String sourceType;

 /*     private String selectProAttr;*/

     private Long attId;
     
      private String sqlContent;

     @NotEmpty
      private String status;

     @NotNull
      private Long lineId;

      private Long programId;

      private Long requestId;
      
      @Transient
      private String value;
      
      @Transient
      private String meaning;
      
      @Transient
      private Long attSetId;
      
      @Transient
      private String compareRule;
      
     public Long getAttSetId() {
		return attSetId;
	}

	public void setAttSetId(Long attSetId) {
		this.attSetId = attSetId;
	}

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getMeaning() {
		return meaning;
	}

	public void setMeaning(String meaning) {
		this.meaning = meaning;
	}

	public void setDetailId(Long detailId){
         this.detailId = detailId;
     }

     public Long getDetailId(){
         return detailId;
     }

     public void setSerialNumber(Long serialNumber){
         this.serialNumber = serialNumber;
     }

     public Long getSerialNumber(){
         return serialNumber;
     }

     public void setDetailName(String detailName){
         this.detailName = detailName;
     }

     public String getDetailName(){
         return detailName;
     }

     public void setSourceType(String sourceType){
         this.sourceType = sourceType;
     }

     public String getSourceType(){
         return sourceType;
     }


     public Long getAttId() {
		return attId;
	}

	public void setAttId(Long attId) {
		this.attId = attId;
	}

	public void setSqlContent(String sqlContent){
         this.sqlContent = sqlContent;
     }

     public String getSqlContent(){
         return sqlContent;
     }

     public void setStatus(String status){
         this.status = status;
     }

     public String getStatus(){
         return status;
     }

     public void setLineId(Long lineId){
         this.lineId = lineId;
     }

     public Long getLineId(){
         return lineId;
     }

     public void setProgramId(Long programId){
         this.programId = programId;
     }

     public Long getProgramId(){
         return programId;
     }

     public void setRequestId(Long requestId){
         this.requestId = requestId;
     }

     public Long getRequestId(){
         return requestId;
     }

	public String getCompareRule() {
		return compareRule;
	}

	public void setCompareRule(String compareRule) {
		this.compareRule = compareRule;
	}

     }
