package clb.core.commission.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import java.util.Date;
import java.util.List;

@ExtensionAttribute(disable=true)
public class CmnCalc extends BaseDTO {

    @Transient
    private Long coverage;

    @Transient
    private String paymentMethod;

    @Transient
    private String gender;

    @Transient
    private Long age;

    @Transient
    private Long nextAge;
    
    @Transient
    private String agePremium;

    @Transient
    private String smokeFlag;

    @Transient
    private String currency;

    @Transient
    private Long itemId;

    @Transient
    private String securityLevel;

    @Transient
    private String securityArea;

    @Transient
    private String selfpay;

    @Transient
    private String livingCountry;

    @Transient
    private String livingCity;

    @Transient
    private String productionAgeLimit;

    @Transient
    private double stagePermium;

    @Transient
    private double yearPermium;

    @Transient
    private Long channelId;

    @Transient
    private String minClass;
    
    @Transient
    private CmnChannelCommission cnmChannelCommissionList;

    public CmnChannelCommission getCnmChannelCommissionList() {
        return cnmChannelCommissionList;
    }

    public String getPaymentMethod() {
        return paymentMethod;
    }

    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    public void setCnmChannelCommissionList(CmnChannelCommission cnmChannelCommissionList) {
        this.cnmChannelCommissionList = cnmChannelCommissionList;
    }

    public Long getChannelId() {
        return channelId;
    }

    public void setChannelId(Long channelId) {
        this.channelId = channelId;
    }

    public Long getCoverage() {
        return coverage;
    }

    public double getStagePermium() {
        return stagePermium;
    }

    public void setStagePermium(double stagePermium) {
        this.stagePermium = stagePermium;
    }

    public double getYearPermium() {
        return yearPermium;
    }

    public void setYearPermium(double yearPermium) {
        this.yearPermium = yearPermium;
    }

    public void setCoverage(Long coverage) {
        this.coverage = coverage;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getAgePremium() {
        return agePremium;
    }

    public void setAgePremium(String agePremium) {
        this.agePremium = agePremium;
    }

    public Long getAge() {
        return age;
    }

    public void setAge(Long age) {
        this.age = age;
    }

    public Long getNextAge() {
		return nextAge;
	}

	public void setNextAge(Long nextAge) {
		this.nextAge = nextAge;
	}

	public String getSmokeFlag() {
        return smokeFlag;
    }

    public void setSmokeFlag(String smokeFlag) {
        this.smokeFlag = smokeFlag;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public Long getItemId() {
        return itemId;
    }

    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    public String getSecurityLevel() {
        return securityLevel;
    }

    public void setSecurityLevel(String securityLevel) {
        this.securityLevel = securityLevel;
    }

    public String getSelfpay() {
        return selfpay;
    }

    public void setSelfpay(String selfpay) {
        this.selfpay = selfpay;
    }

    public String getLivingCity() {
        return livingCity;
    }

    public void setLivingCity(String livingCity) {
        this.livingCity = livingCity;
    }

    public String getProductionAgeLimit() {
        return productionAgeLimit;
    }

    public void setProductionAgeLimit(String productionAgeLimit) {
        this.productionAgeLimit = productionAgeLimit;
    }
    
    @Transient
    private List<Long> itemIdList;

	public List<Long> getItemIdList() {
		return itemIdList;
	}

	public void setItemIdList(List<Long> itemIdList) {
		this.itemIdList = itemIdList;
	}

    public String getSecurityArea() {
        return securityArea;
    }

    public void setSecurityArea(String securityArea) {
        this.securityArea = securityArea;
    }

    public String getLivingCountry() {
        return livingCountry;
    }

    public void setLivingCountry(String livingCountry) {
        this.livingCountry = livingCountry;
    }

    public String getMinClass() {
        return minClass;
    }

    public void setMinClass(String minClass) {
        this.minClass = minClass;
    }

    
}

