package clb.core.commission.dto;

import java.math.BigDecimal;
import java.util.Date;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotEmpty;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "fms_cmn_extra")
public class CmnExtra extends BaseDTO {
    @Id
    @GeneratedValue
    private Long extraId;

    @NotNull
    private Long supplierId;
    
    private Long parentExtraId;

    @NotNull
    private Long superiorSupplierId;

    private String channelTypeCode;

    @NotNull
    private Long itemId;

    @NotEmpty
    private String contributionPeriod;

    @NotEmpty
    private String currency;

    @NotEmpty
    private String payMethod;

    @NotNull
    private Long policyholdersMinAge;

    @NotNull
    private Long policyholdersMaxAge;

    private BigDecimal superiorExtra1;

    private BigDecimal extra1;

    private BigDecimal adjustment1;

    private BigDecimal superiorExtra2;

    private BigDecimal extra2;

    private BigDecimal adjustment2;

    private BigDecimal superiorExtra3;

    private BigDecimal extra3;

    private BigDecimal adjustment3;

    private BigDecimal superiorExtra4;

    private BigDecimal extra4;

    private BigDecimal adjustment4;

    private BigDecimal superiorExtra5;

    private BigDecimal extra5;

    private BigDecimal adjustment5;

    private BigDecimal superiorExtra6;

    private BigDecimal extra6;

    private BigDecimal adjustment6;

    private BigDecimal superiorExtra7;

    private BigDecimal extra7;

    private BigDecimal adjustment7;

    private BigDecimal superiorExtra8;

    private BigDecimal extra8;

    private BigDecimal adjustment8;

    private BigDecimal superiorExtra9;

    private BigDecimal extra9;

    private BigDecimal adjustment9;

    private BigDecimal superiorExtra10;

    private BigDecimal extra10;

    private BigDecimal adjustment10;

    @NotNull
    private Long version;

    private Date effectiveStartDate;

    private Date effectiveEndDate;

    private Long programId;

    private Long requestId;

    @Transient
    private String supplierName;

    @Transient
    private String parentSupplierName;

    @Transient
    private Long itemSupplierId;

    @Transient
    private String itemSupplierName;

    @Transient
    private String itemCode;

    @Transient
    private String itemName;

    @Transient
    private String policyHoldersAge;

    public String getSupplierName() {
        return supplierName;
    }

    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }

    public String getParentSupplierName() {
        return parentSupplierName;
    }

    public void setParentSupplierName(String parentSupplierName) {
        this.parentSupplierName = parentSupplierName;
    }

    public Long getItemSupplierId() {
        return itemSupplierId;
    }

    public void setItemSupplierId(Long itemSupplierId) {
        this.itemSupplierId = itemSupplierId;
    }

    public String getItemSupplierName() {
        return itemSupplierName;
    }

    public void setItemSupplierName(String itemSupplierName) {
        this.itemSupplierName = itemSupplierName;
    }

    public String getItemCode() {
        return itemCode;
    }

    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    public String getItemName() {
        return itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    public String getPolicyHoldersAge() {
        return policyHoldersAge;
    }

    public void setPolicyHoldersAge(String policyHoldersAge) {
        this.policyHoldersAge = policyHoldersAge;
    }

    public void setExtraId(Long extraId){
        this.extraId = extraId;
    }

    public Long getExtraId(){
        return extraId;
    }

    public void setSupplierId(Long supplierId){
        this.supplierId = supplierId;
    }

    public Long getSupplierId(){
        return supplierId;
    }

    public void setSuperiorSupplierId(Long superiorSupplierId){
        this.superiorSupplierId = superiorSupplierId;
    }

    public Long getSuperiorSupplierId(){
        return superiorSupplierId;
    }

    public void setChannelTypeCode(String channelTypeCode){
        this.channelTypeCode = channelTypeCode;
    }

    public String getChannelTypeCode(){
        return channelTypeCode;
    }

    public void setItemId(Long itemId){
        this.itemId = itemId;
    }

    public Long getItemId(){
        return itemId;
    }

    public void setContributionPeriod(String contributionPeriod){
        this.contributionPeriod = contributionPeriod;
    }

    public String getContributionPeriod(){
        return contributionPeriod;
    }

    public void setCurrency(String currency){
        this.currency = currency;
    }

    public String getCurrency(){
        return currency;
    }

    public void setPayMethod(String payMethod){
        this.payMethod = payMethod;
    }

    public String getPayMethod(){
        return payMethod;
    }

    public void setPolicyholdersMinAge(Long policyholdersMinAge){
        this.policyholdersMinAge = policyholdersMinAge;
    }

    public Long getPolicyholdersMinAge(){
        return policyholdersMinAge;
    }

    public void setPolicyholdersMaxAge(Long policyholdersMaxAge){
        this.policyholdersMaxAge = policyholdersMaxAge;
    }

    public Long getPolicyholdersMaxAge(){
        return policyholdersMaxAge;
    }

    public BigDecimal getSuperiorExtra1() {
        return superiorExtra1;
    }

    public void setSuperiorExtra1(BigDecimal superiorExtra1) {
        this.superiorExtra1 = superiorExtra1;
    }

    public BigDecimal getExtra1() {
        return extra1;
    }

    public void setExtra1(BigDecimal extra1) {
        this.extra1 = extra1;
    }

    public BigDecimal getAdjustment1() {
        return adjustment1;
    }

    public void setAdjustment1(BigDecimal adjustment1) {
        this.adjustment1 = adjustment1;
    }

    public BigDecimal getSuperiorExtra2() {
        return superiorExtra2;
    }

    public void setSuperiorExtra2(BigDecimal superiorExtra2) {
        this.superiorExtra2 = superiorExtra2;
    }

    public BigDecimal getExtra2() {
        return extra2;
    }

    public void setExtra2(BigDecimal extra2) {
        this.extra2 = extra2;
    }

    public BigDecimal getAdjustment2() {
        return adjustment2;
    }

    public void setAdjustment2(BigDecimal adjustment2) {
        this.adjustment2 = adjustment2;
    }

    public BigDecimal getSuperiorExtra3() {
        return superiorExtra3;
    }

    public void setSuperiorExtra3(BigDecimal superiorExtra3) {
        this.superiorExtra3 = superiorExtra3;
    }

    public BigDecimal getExtra3() {
        return extra3;
    }

    public void setExtra3(BigDecimal extra3) {
        this.extra3 = extra3;
    }

    public BigDecimal getAdjustment3() {
        return adjustment3;
    }

    public void setAdjustment3(BigDecimal adjustment3) {
        this.adjustment3 = adjustment3;
    }

    public BigDecimal getSuperiorExtra4() {
        return superiorExtra4;
    }

    public void setSuperiorExtra4(BigDecimal superiorExtra4) {
        this.superiorExtra4 = superiorExtra4;
    }

    public BigDecimal getExtra4() {
        return extra4;
    }

    public void setExtra4(BigDecimal extra4) {
        this.extra4 = extra4;
    }

    public BigDecimal getAdjustment4() {
        return adjustment4;
    }

    public void setAdjustment4(BigDecimal adjustment4) {
        this.adjustment4 = adjustment4;
    }

    public BigDecimal getSuperiorExtra5() {
        return superiorExtra5;
    }

    public void setSuperiorExtra5(BigDecimal superiorExtra5) {
        this.superiorExtra5 = superiorExtra5;
    }

    public BigDecimal getExtra5() {
        return extra5;
    }

    public void setExtra5(BigDecimal extra5) {
        this.extra5 = extra5;
    }

    public BigDecimal getAdjustment5() {
        return adjustment5;
    }

    public void setAdjustment5(BigDecimal adjustment5) {
        this.adjustment5 = adjustment5;
    }

    public BigDecimal getSuperiorExtra6() {
        return superiorExtra6;
    }

    public void setSuperiorExtra6(BigDecimal superiorExtra6) {
        this.superiorExtra6 = superiorExtra6;
    }

    public BigDecimal getExtra6() {
        return extra6;
    }

    public void setExtra6(BigDecimal extra6) {
        this.extra6 = extra6;
    }

    public BigDecimal getAdjustment6() {
        return adjustment6;
    }

    public void setAdjustment6(BigDecimal adjustment6) {
        this.adjustment6 = adjustment6;
    }

    public BigDecimal getSuperiorExtra7() {
        return superiorExtra7;
    }

    public void setSuperiorExtra7(BigDecimal superiorExtra7) {
        this.superiorExtra7 = superiorExtra7;
    }

    public BigDecimal getExtra7() {
        return extra7;
    }

    public void setExtra7(BigDecimal extra7) {
        this.extra7 = extra7;
    }

    public BigDecimal getAdjustment7() {
        return adjustment7;
    }

    public void setAdjustment7(BigDecimal adjustment7) {
        this.adjustment7 = adjustment7;
    }

    public BigDecimal getSuperiorExtra8() {
        return superiorExtra8;
    }

    public void setSuperiorExtra8(BigDecimal superiorExtra8) {
        this.superiorExtra8 = superiorExtra8;
    }

    public BigDecimal getExtra8() {
        return extra8;
    }

    public void setExtra8(BigDecimal extra8) {
        this.extra8 = extra8;
    }

    public BigDecimal getAdjustment8() {
        return adjustment8;
    }

    public void setAdjustment8(BigDecimal adjustment8) {
        this.adjustment8 = adjustment8;
    }

    public BigDecimal getSuperiorExtra9() {
        return superiorExtra9;
    }

    public void setSuperiorExtra9(BigDecimal superiorExtra9) {
        this.superiorExtra9 = superiorExtra9;
    }

    public BigDecimal getExtra9() {
        return extra9;
    }

    public void setExtra9(BigDecimal extra9) {
        this.extra9 = extra9;
    }

    public BigDecimal getAdjustment9() {
        return adjustment9;
    }

    public void setAdjustment9(BigDecimal adjustment9) {
        this.adjustment9 = adjustment9;
    }

    public BigDecimal getSuperiorExtra10() {
        return superiorExtra10;
    }

    public void setSuperiorExtra10(BigDecimal superiorExtra10) {
        this.superiorExtra10 = superiorExtra10;
    }

    public BigDecimal getExtra10() {
        return extra10;
    }

    public void setExtra10(BigDecimal extra10) {
        this.extra10 = extra10;
    }

    public BigDecimal getAdjustment10() {
        return adjustment10;
    }

    public void setAdjustment10(BigDecimal adjustment10) {
        this.adjustment10 = adjustment10;
    }

    public void setVersion(Long version){
        this.version = version;
    }

    public Long getVersion(){
        return version;
    }

    public void setEffectiveStartDate(Date effectiveStartDate){
        this.effectiveStartDate = effectiveStartDate;
    }

    public Date getEffectiveStartDate(){
        return effectiveStartDate;
    }

    public void setEffectiveEndDate(Date effectiveEndDate){
        this.effectiveEndDate = effectiveEndDate;
    }

    public Date getEffectiveEndDate(){
        return effectiveEndDate;
    }

    public void setProgramId(Long programId){
        this.programId = programId;
    }

    public Long getProgramId(){
        return programId;
    }

    public void setRequestId(Long requestId){
        this.requestId = requestId;
    }

    public Long getRequestId(){
        return requestId;
    }

	public Long getParentExtraId() {
		return parentExtraId;
	}

	public void setParentExtraId(Long parentExtraId) {
		this.parentExtraId = parentExtraId;
	}


}
