package clb.core.commission.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;

import clb.core.common.utils.DateUtil;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "fms_cmn_override")
public class CmnOverride extends BaseDTO {
	private static final long serialVersionUID = 4236824486096219269L;

	@Id
    @GeneratedValue
    private Long overrideId;

    @NotNull
    private Long supplierId;

    private Long parentOverrideId;
    
    @NotNull
    private Long superiorSupplierId;

    private String channelTypeCode;

    @NotNull
    private Long itemId;
    

    @NotEmpty
    private String contributionPeriod;

    @NotEmpty
    private String currency;

    @NotEmpty
    private String payMethod;

    @NotNull
    private Long policyholdersMinAge;

    @NotNull
    private Long policyholdersMaxAge;

    private BigDecimal superiorOverride1;

    private BigDecimal override1;

    private BigDecimal adjustment1;

    private BigDecimal superiorOverride2;

    private BigDecimal override2;

    private BigDecimal adjustment2;

    private BigDecimal superiorOverride3;

    private BigDecimal override3;

    private BigDecimal adjustment3;

    private BigDecimal superiorOverride4;

    private BigDecimal override4;

    private BigDecimal adjustment4;

    private BigDecimal superiorOverride5;

    private BigDecimal override5;

    private BigDecimal adjustment5;

    private BigDecimal superiorOverride6;

    private BigDecimal override6;

    private BigDecimal adjustment6;

    private BigDecimal superiorOverride7;

    private BigDecimal override7;

    private BigDecimal adjustment7;

    private BigDecimal superiorOverride8;

    private BigDecimal override8;

    private BigDecimal adjustment8;

    private BigDecimal superiorOverride9;

    private BigDecimal override9;

    private BigDecimal adjustment9;

    private BigDecimal superiorOverride10;

    private BigDecimal override10;

    private BigDecimal adjustment10;

    @NotNull
    private Long version;

    private Date effectiveStartDate;

    private Date effectiveEndDate;

    private Long programId;

    private Long requestId;

    @Transient
    private String supplierName;

    @Transient
    private String parentSupplierName;

    @Transient
    private Long itemSupplierId;

    @Transient
    private String itemSupplierName;

    @Transient
    private String itemCode;

    @Transient
    private String itemName;

    @Transient
    private String policyHoldersAge;

    public Long getItemSupplierId() {
        return itemSupplierId;
    }

    public void setItemSupplierId(Long itemSupplierId) {
        this.itemSupplierId = itemSupplierId;
    }

    public String getPolicyHoldersAge() {
        return policyHoldersAge;
    }

    public void setPolicyHoldersAge(String policyHoldersAge) {
        this.policyHoldersAge = policyHoldersAge;
    }

    public String getItemCode() {
        return itemCode;
    }

    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    public String getItemName() {
        return itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    public String getSupplierName() {
        return supplierName;
    }

    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }

    public String getParentSupplierName() {
        return parentSupplierName;
    }

    public void setParentSupplierName(String parentSupplierName) {
        this.parentSupplierName = parentSupplierName;
    }

    public String getItemSupplierName() {
        return itemSupplierName;
    }

    public void setItemSupplierName(String itemSupplierName) {
        this.itemSupplierName = itemSupplierName;
    }

    public void setOverrideId(Long overrideId){
        this.overrideId = overrideId;
    }

    public Long getOverrideId(){
        return overrideId;
    }

    public Long getParentOverrideId() {
		return parentOverrideId;
	}

	public void setParentOverrideId(Long parentOverrideId) {
		this.parentOverrideId = parentOverrideId;
	}

	public void setSupplierId(Long supplierId){
        this.supplierId = supplierId;
    }

    public Long getSupplierId(){
        return supplierId;
    }

    public void setSuperiorSupplierId(Long superiorSupplierId){
        this.superiorSupplierId = superiorSupplierId;
    }

    public Long getSuperiorSupplierId(){
        return superiorSupplierId;
    }

    public void setChannelTypeCode(String channelTypeCode){
        this.channelTypeCode = channelTypeCode;
    }

    public String getChannelTypeCode(){
        return channelTypeCode;
    }

    public void setItemId(Long itemId){
        this.itemId = itemId;
    }

    public Long getItemId(){
        return itemId;
    }

    public void setContributionPeriod(String contributionPeriod){
        this.contributionPeriod = contributionPeriod;
    }

    public String getContributionPeriod(){
        return contributionPeriod;
    }

    public void setCurrency(String currency){
        this.currency = currency;
    }

    public String getCurrency(){
        return currency;
    }

    public void setPayMethod(String payMethod){
        this.payMethod = payMethod;
    }

    public String getPayMethod(){
        return payMethod;
    }

    public void setPolicyholdersMinAge(Long policyholdersMinAge){
        this.policyholdersMinAge = policyholdersMinAge;
    }

    public Long getPolicyholdersMinAge(){
        return policyholdersMinAge;
    }

    public void setPolicyholdersMaxAge(Long policyholdersMaxAge){
        this.policyholdersMaxAge = policyholdersMaxAge;
    }

    public Long getPolicyholdersMaxAge(){
        return policyholdersMaxAge;
    }

    public BigDecimal getSuperiorOverride1() {
        return superiorOverride1;
    }

    public void setSuperiorOverride1(BigDecimal superiorOverride1) {
        this.superiorOverride1 = superiorOverride1;
    }

    public BigDecimal getOverride1() {
        return override1;
    }

    public void setOverride1(BigDecimal override1) {
        this.override1 = override1;
    }

    public BigDecimal getAdjustment1() {
        return adjustment1;
    }

    public void setAdjustment1(BigDecimal adjustment1) {
        this.adjustment1 = adjustment1;
    }

    public BigDecimal getSuperiorOverride2() {
        return superiorOverride2;
    }

    public void setSuperiorOverride2(BigDecimal superiorOverride2) {
        this.superiorOverride2 = superiorOverride2;
    }

    public BigDecimal getOverride2() {
        return override2;
    }

    public void setOverride2(BigDecimal override2) {
        this.override2 = override2;
    }

    public BigDecimal getAdjustment2() {
        return adjustment2;
    }

    public void setAdjustment2(BigDecimal adjustment2) {
        this.adjustment2 = adjustment2;
    }

    public BigDecimal getSuperiorOverride3() {
        return superiorOverride3;
    }

    public void setSuperiorOverride3(BigDecimal superiorOverride3) {
        this.superiorOverride3 = superiorOverride3;
    }

    public BigDecimal getOverride3() {
        return override3;
    }

    public void setOverride3(BigDecimal override3) {
        this.override3 = override3;
    }

    public BigDecimal getAdjustment3() {
        return adjustment3;
    }

    public void setAdjustment3(BigDecimal adjustment3) {
        this.adjustment3 = adjustment3;
    }

    public BigDecimal getSuperiorOverride4() {
        return superiorOverride4;
    }

    public void setSuperiorOverride4(BigDecimal superiorOverride4) {
        this.superiorOverride4 = superiorOverride4;
    }

    public BigDecimal getOverride4() {
        return override4;
    }

    public void setOverride4(BigDecimal override4) {
        this.override4 = override4;
    }

    public BigDecimal getAdjustment4() {
        return adjustment4;
    }

    public void setAdjustment4(BigDecimal adjustment4) {
        this.adjustment4 = adjustment4;
    }

    public BigDecimal getSuperiorOverride5() {
        return superiorOverride5;
    }

    public void setSuperiorOverride5(BigDecimal superiorOverride5) {
        this.superiorOverride5 = superiorOverride5;
    }

    public BigDecimal getOverride5() {
        return override5;
    }

    public void setOverride5(BigDecimal override5) {
        this.override5 = override5;
    }

    public BigDecimal getAdjustment5() {
        return adjustment5;
    }

    public void setAdjustment5(BigDecimal adjustment5) {
        this.adjustment5 = adjustment5;
    }

    public BigDecimal getSuperiorOverride6() {
        return superiorOverride6;
    }

    public void setSuperiorOverride6(BigDecimal superiorOverride6) {
        this.superiorOverride6 = superiorOverride6;
    }

    public BigDecimal getOverride6() {
        return override6;
    }

    public void setOverride6(BigDecimal override6) {
        this.override6 = override6;
    }

    public BigDecimal getAdjustment6() {
        return adjustment6;
    }

    public void setAdjustment6(BigDecimal adjustment6) {
        this.adjustment6 = adjustment6;
    }

    public BigDecimal getSuperiorOverride7() {
        return superiorOverride7;
    }

    public void setSuperiorOverride7(BigDecimal superiorOverride7) {
        this.superiorOverride7 = superiorOverride7;
    }

    public BigDecimal getOverride7() {
        return override7;
    }

    public void setOverride7(BigDecimal override7) {
        this.override7 = override7;
    }

    public BigDecimal getAdjustment7() {
        return adjustment7;
    }

    public void setAdjustment7(BigDecimal adjustment7) {
        this.adjustment7 = adjustment7;
    }

    public BigDecimal getSuperiorOverride8() {
        return superiorOverride8;
    }

    public void setSuperiorOverride8(BigDecimal superiorOverride8) {
        this.superiorOverride8 = superiorOverride8;
    }

    public BigDecimal getOverride8() {
        return override8;
    }

    public void setOverride8(BigDecimal override8) {
        this.override8 = override8;
    }

    public BigDecimal getAdjustment8() {
        return adjustment8;
    }

    public void setAdjustment8(BigDecimal adjustment8) {
        this.adjustment8 = adjustment8;
    }

    public BigDecimal getSuperiorOverride9() {
        return superiorOverride9;
    }

    public void setSuperiorOverride9(BigDecimal superiorOverride9) {
        this.superiorOverride9 = superiorOverride9;
    }

    public BigDecimal getOverride9() {
        return override9;
    }

    public void setOverride9(BigDecimal override9) {
        this.override9 = override9;
    }

    public BigDecimal getAdjustment9() {
        return adjustment9;
    }

    public void setAdjustment9(BigDecimal adjustment9) {
        this.adjustment9 = adjustment9;
    }

    public BigDecimal getSuperiorOverride10() {
        return superiorOverride10;
    }

    public void setSuperiorOverride10(BigDecimal superiorOverride10) {
        this.superiorOverride10 = superiorOverride10;
    }

    public BigDecimal getOverride10() {
        return override10;
    }

    public void setOverride10(BigDecimal override10) {
        this.override10 = override10;
    }

    public BigDecimal getAdjustment10() {
        return adjustment10;
    }

    public void setAdjustment10(BigDecimal adjustment10) {
        this.adjustment10 = adjustment10;
    }

    public void setVersion(Long version){
        this.version = version;
    }

    public Long getVersion(){
        return version;
    }

    public void setEffectiveStartDate(Date effectiveStartDate){
        this.effectiveStartDate = effectiveStartDate;
    }

    public Date getEffectiveStartDate(){
        return effectiveStartDate;
    }

    public void setEffectiveEndDate(Date effectiveEndDate){
        this.effectiveEndDate = effectiveEndDate;
    }

    public Date getEffectiveEndDate(){
    	if(effectiveEndDate!=null){
    		return DateUtil.dayEnd(effectiveEndDate);
    	}
        return effectiveEndDate;
    }

    public void setProgramId(Long programId){
        this.programId = programId;
    }

    public Long getProgramId(){
        return programId;
    }

    public void setRequestId(Long requestId){
        this.requestId = requestId;
    }

    public Long getRequestId(){
        return requestId;
    }

	/**
     * 是否超级管理员
     */
    @Transient
    private String isAdmin;

	public String getIsAdmin() {
		return isAdmin;
	}

	public void setIsAdmin(String isAdmin) {
		this.isAdmin = isAdmin;
	}
    
}
