package clb.core.commission.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import javax.validation.constraints.NotNull;
@ExtensionAttribute(disable=true)
@Table(name = "fms_cmn_supplier_item_relation")
public class CmnSupplierItemRelation extends BaseDTO {
     @Id
     @GeneratedValue
      private Long relationId;

     @NotNull
      private Long supplierId;

     @NotNull
      private Long itemId;

     @NotNull
      private Long reserveSupplierId;
     
     //产品公司ID
     @NotNull
     private Long prdSupplierId;

      private Long programId;

      private Long requestId;
      //所属供应商名字
      @Transient
      private String name;
      //预约供应商名字
      @Transient
      private String reserveName;
      //产品名字
      @Transient
      private String itemName;
      //产品编码
      @Transient
      private String itemCode;
      //产品公司名字
      @Transient
      private String prdSupplierName;


     public String getItemCode() {
		return itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getReserveName() {
		return reserveName;
	}

	public void setReserveName(String reserveName) {
		this.reserveName = reserveName;
	}

	public String getItemName() {
		return itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public String getPrdSupplierName() {
		return prdSupplierName;
	}

	public void setPrdSupplierName(String prdSupplierName) {
		this.prdSupplierName = prdSupplierName;
	}

	public Long getPrdSupplierId() {
		return prdSupplierId;
	}

	public void setPrdSupplierId(Long prdSupplierId) {
		this.prdSupplierId = prdSupplierId;
	}

	public void setRelationId(Long relationId){
         this.relationId = relationId;
     }

     public Long getRelationId(){
         return relationId;
     }

     public void setSupplierId(Long supplierId){
         this.supplierId = supplierId;
     }

     public Long getSupplierId(){
         return supplierId;
     }

     public void setItemId(Long itemId){
         this.itemId = itemId;
     }

     public Long getItemId(){
         return itemId;
     }

     public void setReserveSupplierId(Long reserveSupplierId){
         this.reserveSupplierId = reserveSupplierId;
     }

     public Long getReserveSupplierId(){
         return reserveSupplierId;
     }

     public void setProgramId(Long programId){
         this.programId = programId;
     }

     public Long getProgramId(){
         return programId;
     }

     public void setRequestId(Long requestId){
         this.requestId = requestId;
     }

     public Long getRequestId(){
         return requestId;
     }

     }
