package clb.core.production.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "fms_prd_hot_recommend")
public class PrdHotRecommend extends BaseDTO {
     @Id
     @GeneratedValue
      private Long recommendId;

     @NotEmpty
      private String productType;

     @NotNull
      private Long itemId;

     @NotNull
      private Long seqNum;
     
     @Transient
     private String itemName;
     
      private Long programId;

      private Long requestId;
     
     public String getItemName() {
		return itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public void setRecommendId(Long recommendId){
         this.recommendId = recommendId;
     }

     public Long getRecommendId(){
         return recommendId;
     }

     public void setProductType(String productType){
         this.productType = productType;
     }

     public String getProductType(){
         return productType;
     }

     public void setItemId(Long itemId){
         this.itemId = itemId;
     }

     public Long getItemId(){
         return itemId;
     }

     public void setSeqNum(Long seqNum){
         this.seqNum = seqNum;
     }

     public Long getSeqNum(){
         return seqNum;
     }

     public void setProgramId(Long programId){
         this.programId = programId;
     }

     public Long getProgramId(){
         return programId;
     }

     public void setRequestId(Long requestId){
         this.requestId = requestId;
     }

     public Long getRequestId(){
         return requestId;
     }

     }
