package clb.core.pln.dto;

import java.util.List;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.core.annotation.Children;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;

@ExtensionAttribute(disable = true)
@Table(name = "fms_pln_e_plan_template_detail")
public class PlnEPlanTemplateDetail extends BaseDTO {
	@Id
	@GeneratedValue
	private Long detailId;

	@NotNull
	private Long smallId;

	@NotNull
	private Long seqNum;

	@NotEmpty
	private String detailItem;

	@NotEmpty
	private String amountFormula;

	@NotEmpty
	private String fixedValue;

	private Long programId;

	private Long requestId;

	public void setDetailId(Long detailId) {
		this.detailId = detailId;
	}

	public Long getDetailId() {
		return detailId;
	}

	public void setSmallId(Long smallId) {
		this.smallId = smallId;
	}

	public Long getSmallId() {
		return smallId;
	}

	public void setSeqNum(Long seqNum) {
		this.seqNum = seqNum;
	}

	public Long getSeqNum() {
		return seqNum;
	}

	public void setDetailItem(String detailItem) {
		this.detailItem = detailItem;
	}

	public String getDetailItem() {
		return detailItem;
	}

	public void setAmountFormula(String amountFormula) {
		this.amountFormula = amountFormula;
	}

	public String getAmountFormula() {
		return amountFormula;
	}

	public void setFixedValue(String fixedValue) {
		this.fixedValue = fixedValue;
	}

	public String getFixedValue() {
		return fixedValue;
	}

	public void setProgramId(Long programId) {
		this.programId = programId;
	}

	public Long getProgramId() {
		return programId;
	}

	public void setRequestId(Long requestId) {
		this.requestId = requestId;
	}

	public Long getRequestId() {
		return requestId;
	}
	
}
