package clb.core.pln.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import javax.validation.constraints.NotNull;
@ExtensionAttribute(disable=true)
@Table(name = "fms_pln_plan_request_extract")
public class PlnPlanRequestExtract extends BaseDTO {
     @Id
     @GeneratedValue
      private Long lineId;

     @NotNull
      private Long planId;

     @NotNull
      private Long yearFrom;

     @NotNull
      private Long yearTo;

      private String amount;

      private Long programId;

      private Long requestId;
      
      @Transient
      private String type;
      
     public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public void setLineId(Long lineId){
         this.lineId = lineId;
     }

     public Long getLineId(){
         return lineId;
     }

     public void setPlanId(Long planId){
         this.planId = planId;
     }

     public Long getPlanId(){
         return planId;
     }

     public void setYearFrom(Long yearFrom){
         this.yearFrom = yearFrom;
     }

     public Long getYearFrom(){
         return yearFrom;
     }

     public void setYearTo(Long yearTo){
         this.yearTo = yearTo;
     }

     public Long getYearTo(){
         return yearTo;
     }



     public String getAmount() {
		return amount;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}

	public void setProgramId(Long programId){
         this.programId = programId;
     }

     public Long getProgramId(){
         return programId;
     }

     public void setRequestId(Long requestId){
         this.requestId = requestId;
     }

     public Long getRequestId(){
         return requestId;
     }

     }
