package clb.core.pln.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
@ExtensionAttribute(disable=true)
@Table(name = "fms_pln_plan_spider_setting")
public class PlnPlanSpiderSetting extends BaseDTO {
     @Id
     @GeneratedValue
      private Long settingId; //表ID，主键，供其他表做外键

     @NotNull
      private Long supplierId; //保险公司ID

     @NotNull
      private Long itemId; //产品ID

     @NotEmpty
      private String currency; //币种

     @NotNull
      private Long sublineId; //子产品ID

     @NotEmpty
      private String payMethod; //缴费方式

     @NotEmpty
      private String insuranceItemName; //保险公司产品名称

      private String insuranceCurrency; //币种

      private String insuranceSublineName; //年期

      private String insurancePayMethod; //缴费方式

     @NotEmpty
      private String spiderProgram; //爬虫程序

    private String specialUsername;//特殊账号

    private String specialPassword;//特殊密码


     @NotEmpty
      private String enableFlag; //启用

      private Long programId;

      private Long requestId;

    @Transient
    private String supplierName;

    @Transient
    private String itemName;

    @Transient
    private String sublineItemName;

    @Transient
    private String userName;

    @Transient
    private String password;

     public void setSettingId(Long settingId){
         this.settingId = settingId;
     }

     public Long getSettingId(){
         return settingId;
     }

     public void setSupplierId(Long supplierId){
         this.supplierId = supplierId;
     }

     public Long getSupplierId(){
         return supplierId;
     }

     public void setItemId(Long itemId){
         this.itemId = itemId;
     }

     public Long getItemId(){
         return itemId;
     }

     public void setCurrency(String currency){
         this.currency = currency;
     }

     public String getCurrency(){
         return currency;
     }

     public void setSublineId(Long sublineId){
         this.sublineId = sublineId;
     }

     public Long getSublineId(){
         return sublineId;
     }

     public void setPayMethod(String payMethod){
         this.payMethod = payMethod;
     }

     public String getPayMethod(){
         return payMethod;
     }

     public void setInsuranceItemName(String insuranceItemName){
         this.insuranceItemName = insuranceItemName;
     }

     public String getInsuranceItemName(){
         return insuranceItemName;
     }

     public void setInsuranceCurrency(String insuranceCurrency){
         this.insuranceCurrency = insuranceCurrency;
     }

     public String getInsuranceCurrency(){
         return insuranceCurrency;
     }

     public void setInsuranceSublineName(String insuranceSublineName){
         this.insuranceSublineName = insuranceSublineName;
     }

     public String getInsuranceSublineName(){
         return insuranceSublineName;
     }

     public void setInsurancePayMethod(String insurancePayMethod){
         this.insurancePayMethod = insurancePayMethod;
     }

     public String getInsurancePayMethod(){
         return insurancePayMethod;
     }

     public void setSpiderProgram(String spiderProgram){
         this.spiderProgram = spiderProgram;
     }

     public String getSpiderProgram(){
         return spiderProgram;
     }

     public void setUserName(String userName){
         this.userName = userName;
     }

     public String getUserName(){
         return userName;
     }

     public void setPassword(String password){
         this.password = password;
     }

     public String getPassword(){
         return password;
     }

     public void setEnableFlag(String enableFlag){
         this.enableFlag = enableFlag;
     }

     public String getEnableFlag(){
         return enableFlag;
     }

     public void setProgramId(Long programId){
         this.programId = programId;
     }

     public Long getProgramId(){
         return programId;
     }

     public void setRequestId(Long requestId){
         this.requestId = requestId;
     }

     public Long getRequestId(){
         return requestId;
     }

    public String getSupplierName() {
        return supplierName;
    }

    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }

    public String getItemName() {
        return itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    public String getSublineItemName() {
        return sublineItemName;
    }

    public void setSublineItemName(String sublineItemName) {
        this.sublineItemName = sublineItemName;
    }

    public String getSpecialUsername() {
        return specialUsername;
    }

    public void setSpecialUsername(String specialUsername) {
        this.specialUsername = specialUsername;
    }

    public String getSpecialPassword() {
        return specialPassword;
    }

    public void setSpecialPassword(String specialPassword) {
        this.specialPassword = specialPassword;
    }
}
