package clb.core.notification.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;

import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

@ExtensionAttribute(disable = true)
@Table(name = "fms_ntn_notification_template")
public class NtnNotificationTemplate extends BaseDTO {
    @Id
    @GeneratedValue
    private Long templateId;

    @NotEmpty
    private String templateCode;

    @NotEmpty
    private String name;

    @NotEmpty
    private String object;

    @NotEmpty
    private String status;

    private String platformFlag;

    private String platformContent;

    private String redirectPage;

    private String messageFlag;

    private String messageContent;

    private String emailFlag;
    
    private String importantFlag;

    private String emailSubject;

    private String emailContent;

    private String webchatFlag;

    private String originalId;
    
    private String webchatApi;

    private String webchatContent;
    
    private String whtContent;
    
    private String whtJumpUrl;

    private Long programId;

    private Long requestId;
    
	public String getWhtJumpUrl() {
		return whtJumpUrl;
	}

	public void setWhtJumpUrl(String whtJumpUrl) {
		this.whtJumpUrl = whtJumpUrl;
	}

	public String getWhtContent() {
		return whtContent;
	}

	public void setWhtContent(String whtContent) {
		this.whtContent = whtContent;
	}

	public String getOriginalId() {
		return originalId;
	}

	public void setOriginalId(String originalId) {
		this.originalId = originalId;
	}

	public String getImportantFlag() {
		return importantFlag;
	}

	public void setImportantFlag(String importantFlag) {
		this.importantFlag = importantFlag;
	}

	public String getEmailFlag() {
        return emailFlag;
    }

    public void setEmailFlag(String emailFlag) {
        this.emailFlag = emailFlag;
    }

    public String getEmailContent() {
        return emailContent;
    }

    public void setEmailContent(String emailContent) {
        this.emailContent = emailContent;
    }

    public void setTemplateId(Long templateId) {
        this.templateId = templateId;
    }

    public Long getTemplateId() {
        return templateId;
    }

    public void setTemplateCode(String templateCode) {
        this.templateCode = templateCode;
    }

    public String getTemplateCode() {
        return templateCode;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setObject(String object) {
        this.object = object;
    }

    public String getObject() {
        return object;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getStatus() {
        return status;
    }

    public void setPlatformFlag(String platformFlag) {
        this.platformFlag = platformFlag;
    }

    public String getPlatformFlag() {
        return platformFlag;
    }

    public void setPlatformContent(String platformContent) {
        this.platformContent = platformContent;
    }

    public String getPlatformContent() {
        return platformContent;
    }

    public void setRedirectPage(String redirectPage) {
        this.redirectPage = redirectPage;
    }

    public String getRedirectPage() {
        return redirectPage;
    }

    public void setMessageFlag(String messageFlag) {
        this.messageFlag = messageFlag;
    }

    public String getMessageFlag() {
        return messageFlag;
    }

    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent;
    }

    public String getMessageContent() {
        return messageContent;
    }

    public void setWebchatFlag(String webchatFlag) {
        this.webchatFlag = webchatFlag;
    }

    public String getWebchatFlag() {
        return webchatFlag;
    }

    public void setWebchatApi(String webchatApi) {
        this.webchatApi = webchatApi;
    }

    public String getWebchatApi() {
        return webchatApi;
    }

    public void setWebchatContent(String webchatContent) {
        this.webchatContent = webchatContent;
    }

    public String getWebchatContent() {
        return webchatContent;
    }

    public void setProgramId(Long programId) {
        this.programId = programId;
    }

    public Long getProgramId() {
        return programId;
    }

    public void setRequestId(Long requestId) {
        this.requestId = requestId;
    }

    public Long getRequestId() {
        return requestId;
    }

    public String getEmailSubject() {
        return emailSubject;
    }

    public void setEmailSubject(String emailSubject) {
        this.emailSubject = emailSubject;
    }

}
