package clb.core.common.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.validator.constraints.NotEmpty;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

@ExtensionAttribute(disable = true)
@Table(name = "FMS_PUB_SEQUENCE")
public class Sequence extends BaseDTO {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 4114631733744945966L;

	@Id
	@GeneratedValue
	private Long sequenceId;

	@NotEmpty
	private String sequenceCode;

	@NotEmpty
	private String sequenceName;

	private String sequencePrefix;

	private String dateFormat;

	private String incrCode;

	private Long serialNumber;

	@NotEmpty
	private String seqLength;

	public void setSequenceId(Long sequenceId) {
		this.sequenceId = sequenceId;
	}

	public Long getSequenceId() {
		return sequenceId;
	}

	public void setSequenceCode(String sequenceCode) {
		this.sequenceCode = sequenceCode;
	}

	public String getSequenceCode() {
		return sequenceCode;
	}

	public void setSequenceName(String sequenceName) {
		this.sequenceName = sequenceName;
	}

	public String getSequenceName() {
		return sequenceName;
	}

	public void setSequencePrefix(String sequencePrefix) {
		this.sequencePrefix = sequencePrefix;
	}

	public String getSequencePrefix() {
		return sequencePrefix;
	}

	public void setDateFormat(String dateFormat) {
		this.dateFormat = dateFormat;
	}

	public String getDateFormat() {
		return dateFormat;
	}

	public String getIncrCode() {
		return incrCode;
	}

	public void setIncrCode(String incrCode) {
		this.incrCode = incrCode;
	}

	public void setSeqLength(String seqLength) {
		this.seqLength = seqLength;
	}

	public String getSeqLength() {
		return seqLength;
	}

	public static long getSerialVersionUID() {
		return serialVersionUID;
	}

	public Long getSerialNumber() {
		return serialNumber;
	}

	public void setSerialNumber(Long serialNumber) {
		this.serialNumber = serialNumber;
	}
}
