package clb.core.course.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import javax.validation.constraints.NotNull;
@ExtensionAttribute(disable=true)
@Table(name = "fms_trn_course_notice")
public class TrnCourseNotice extends BaseDTO {
     @Id
     @GeneratedValue
      private Long lineId;

     @NotNull
      private Long courseId;

      private String notice;

      private Long programId;

      private Long requestId;


     public void setLineId(Long lineId){
         this.lineId = lineId;
     }

     public Long getLineId(){
         return lineId;
     }

     public void setCourseId(Long courseId){
         this.courseId = courseId;
     }

     public Long getCourseId(){
         return courseId;
     }

     public void setNotice(String notice){
         this.notice = notice;
     }

     public String getNotice(){
         return notice;
     }

     public void setProgramId(Long programId){
         this.programId = programId;
     }

     public Long getProgramId(){
         return programId;
     }

     public void setRequestId(Long requestId){
         this.requestId = requestId;
     }

     public Long getRequestId(){
         return requestId;
     }

     }
