package clb.core.course.dto;

import java.util.Date;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;

import clb.core.core.annotation.SecurityField;

import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;

@ExtensionAttribute(disable = true)
@Table(name = "fms_trn_course_student")
public class TrnCourseStudent extends BaseDTO {
	@Id
	@GeneratedValue
	private Long lineId;

	@NotNull
	private Long courseId;

	@NotEmpty
	private String name;

	@SecurityField
	private String phoneCode;

	/* @NotEmpty */
	@SecurityField
	private String phoneNumber;

	@NotEmpty
	private String mailAddress;

	@NotEmpty
	private Integer joinMethod;

	@NotNull
	private String company;

	@NotEmpty
	private String position;

	private Long channelId;

	@Transient
	private String channelName;

	private String belongTo;

	private String payStatus;

	private Long programId;

	private Long requestId;

	private Long createdBy;

	@Transient
	private String shalongNum;

	@Transient
	private String peixunNum;

	@Transient
	private String total;

	@Transient
	private String channelOrName;

	@Transient
	private String createdName;

	@Transient
	private Date lastUpdateDate;

	@Transient
	@SecurityField
	private String contactPhoneComb;

	public String getCreatedName() {
		return createdName;
	}

	public void setCreatedName(String createdName) {
		this.createdName = createdName;
	}

	public Date getLastUpdateDate() {
		return lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public String getPhoneCode() {
		return phoneCode;
	}

	public void setPhoneCode(String phoneCode) {
		this.phoneCode = phoneCode;
	}

	public String getContactPhoneComb() {
		return contactPhoneComb;
	}

	public void setContactPhoneComb(String contactPhoneComb) {
		this.contactPhoneComb = contactPhoneComb;
	}

	public String getCompany() {
		return company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getChannelOrName() {
		return channelOrName;
	}

	public void setChannelOrName(String channelOrName) {
		this.channelOrName = channelOrName;
	}

	public String getChannelName() {
		return channelName;
	}

	public void setChannelName(String channelName) {
		this.channelName = channelName;
	}

	public String getShalongNum() {
		return shalongNum;
	}

	public void setShalongNum(String shalongNum) {
		this.shalongNum = shalongNum;
	}

	public String getPeixunNum() {
		return peixunNum;
	}

	public void setPeixunNum(String peixunNum) {
		this.peixunNum = peixunNum;
	}

	public String getTotal() {
		return total;
	}

	public void setTotal(String total) {
		this.total = total;
	}

	public void setLineId(Long lineId) {
		this.lineId = lineId;
	}

	public Long getLineId() {
		return lineId;
	}

	public void setCourseId(Long courseId) {
		this.courseId = courseId;
	}

	public Long getCourseId() {
		return courseId;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getName() {
		return name;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getPhoneNumber() {
		return phoneNumber;
	}

	public void setMailAddress(String mailAddress) {
		this.mailAddress = mailAddress;
	}

	public String getMailAddress() {
		return mailAddress;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public String getPosition() {
		return position;
	}

	public void setChannelId(Long channelId) {
		this.channelId = channelId;
	}

	public Long getChannelId() {
		return channelId;
	}

	public void setBelongTo(String belongTo) {
		this.belongTo = belongTo;
	}

	public String getBelongTo() {
		return belongTo;
	}

	public void setProgramId(Long programId) {
		this.programId = programId;
	}

	public Long getProgramId() {
		return programId;
	}

	public void setRequestId(Long requestId) {
		this.requestId = requestId;
	}

	public Long getRequestId() {
		return requestId;
	}

	public String getPayStatus() {
		return payStatus;
	}

	public void setPayStatus(String payStatus) {
		this.payStatus = payStatus;
	}

	public Long getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	public Integer getJoinMethod() {
		return joinMethod;
	}

	public void setJoinMethod(Integer joinMethod) {
		this.joinMethod = joinMethod;
	}

	@Transient
	private String appPayType;

	public String getAppPayType() {
		return appPayType;
	}

	public void setAppPayType(String appPayType) {
		this.appPayType = appPayType;
	}

	@Transient
	private Long userId;

	public Long getUserId() {
		return userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}
}
