package clb.core.course.dto;

import java.util.Date;

import javax.persistence.Column;
/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.hand.hap.mybatis.annotation.Condition;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "fms_trn_course_file")
public class TrnCourseFile extends BaseDTO {
     /**
	 * 
	 */
	private static final long serialVersionUID = -6064673416864936152L;

	@Id
     @GeneratedValue
      private Long lineId;

     @NotNull
      private Long courseId;

     @NotNull
      private Long fileId;
     
     @Transient
	  private String fileName;
     
     @Transient
 	  private String fileSize;
 	
 	 @Transient
 	  private Date uploadDate;
 	 
 	 @Transient
 	 @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
 	 private Date lastUpdateDate;
 	 
 	 @Transient
 	 private String name;

	private Long programId;

    private Long requestId;
      
    public Date getLastUpdateDate() {
    	return lastUpdateDate;
    }
      
    public void setLastUpdateDate(Date lastUpdateDate) {
    	this.lastUpdateDate = lastUpdateDate;
    }
     
    public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getFileSize() {
		return fileSize;
	}

	public void setFileSize(String fileSize) {
		this.fileSize = fileSize;
	}

	

	public Date getUploadDate() {
		return uploadDate;
	}

	public void setUploadDate(Date uploadDate) {
		this.uploadDate = uploadDate;
	}

	public void setLineId(Long lineId){
         this.lineId = lineId;
     }

     public Long getLineId(){
         return lineId;
     }

     public void setCourseId(Long courseId){
         this.courseId = courseId;
     }

     public Long getCourseId(){
         return courseId;
     }

     public void setFileId(Long fileId){
         this.fileId = fileId;
     }

     public Long getFileId(){
         return fileId;
     }

     public void setProgramId(Long programId){
         this.programId = programId;
     }

     public Long getProgramId(){
         return programId;
     }

     public void setRequestId(Long requestId){
         this.requestId = requestId;
     }

     public Long getRequestId(){
         return requestId;
     }
     private Long downloadTimes;
     
     private Long supplierId;
     
     private String productClass;
     
     private String fileContent;
     
     private String fileNum;
     
     @Transient
 	  private String startDate;// 开始日期

 	  @Transient
 	  private String endDate;// 结束日期
 	  
 	  
 	 @Transient
	  private String topic;

 	 
 	 
 	 
	public String getFileNum() {
		return fileNum;
	}

	public void setFileNum(String fileNum) {
		this.fileNum = fileNum;
	}

	public String getTopic() {
		return topic;
	}

	public void setTopic(String topic) {
		this.topic = topic;
	}

	public String getStartDate() {
		return startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	public String getEndDate() {
		return endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public Long getDownloadTimes() {
		return downloadTimes;
	}

	public void setDownloadTimes(Long downloadTimes) {
		this.downloadTimes = downloadTimes;
	}

	public Long getSupplierId() {
		return supplierId;
	}

	public void setSupplierId(Long supplierId) {
		this.supplierId = supplierId;
	}

	public String getProductClass() {
		return productClass;
	}

	public void setProductClass(String productClass) {
		this.productClass = productClass;
	}

	public String getFileContent() {
		return fileContent;
	}

	public void setFileContent(String fileContent) {
		this.fileContent = fileContent;
	}
	
	@Transient
	private String filePath;

	public String getFilePath() {
		return filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}
     
	private String prdDivision;
    private String prdClass;

	public String getPrdDivision() {
		return prdDivision;
	}

	public void setPrdDivision(String prdDivision) {
		this.prdDivision = prdDivision;
	}

	public String getPrdClass() {
		return prdClass;
	}

	public void setPrdClass(String prdClass) {
		this.prdClass = prdClass;
	}
	
     }
