package clb.core.supplier.dto;

import java.util.Date;

import javax.persistence.Column;
/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "fms_spe_archives")
public class SpeArchives extends BaseDTO {
     @Id
     @Column
     @GeneratedValue
     private Long archiveId;

     @NotNull
     @Column
     private Long contractId;

     @NotNull
     @Column
     private Long fileId;

     @NotEmpty
     @Column
     private String name;

     @Column
     private String comments;
     
     

	/**
      * 文件大小 
      */
     @Transient
     private Long fileSize;
     
     /**
      * 上传日期.
      */
     @Transient
     private Date uploadDate;
     
     /**
      * 文件相对项目的虚拟路径.
      */
     @Transient
     private String filePath;
     
     @Transient
     private Long oldFileId;


     public Long getOldFileId() {
		return oldFileId;
	}

	public void setOldFileId(Long oldFileId) {
		this.oldFileId = oldFileId;
	}

	public String getFilePath() {
		return filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	public Long getFileSize() {
		return fileSize;
	}

	public void setFileSize(Long fileSize) {
		this.fileSize = fileSize;
	}

	public Date getUploadDate() {
		return uploadDate;
	}

	public void setUploadDate(Date uploadDate) {
		this.uploadDate = uploadDate;
	}

	public void setArchiveId(Long archiveId){
         this.archiveId = archiveId;
     }

     public Long getArchiveId(){
         return archiveId;
     }

    public Long getContractId() {
		return contractId;
	}

	public void setContractId(Long contractId) {
		this.contractId = contractId;
	}

	public void setFileId(Long fileId){
         this.fileId = fileId;
     }

     public Long getFileId(){
         return fileId;
     }

     public void setName(String name){
         this.name = name;
     }

     public String getName(){
         return name;
     }

     public void setComments(String comments){
         this.comments = comments;
     }

     public String getComments(){
         return comments;
     }

}
