package clb.core.supplier.dto;

import java.util.List;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import clb.core.core.annotation.SecurityField;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "fms_spe_contract")
public class SpeContract extends BaseDTO {
      @Id
      @GeneratedValue
      private Long contractId;
      
      @NotNull
      private Long supplierId;

      private String levelOneType;

      private String levelTwoType;

      private String levelThreeType;

     @NotEmpty
      private String contractName;

     @NotEmpty
      private String br;

     @NotEmpty
      private String ci;

     @NotEmpty
      private String addressMessage;

     @NotEmpty
      private String sameSettle;

     @NotEmpty
      private String settleContractName;

     @NotEmpty
      private String settleBr;

     @NotEmpty
      private String settleCi;

     @SecurityField
     @NotEmpty
      private String settleAddressMessage;

     @NotNull
      private Long collectionTermId;

     @NotEmpty
      private String settleTypeCode;

     @SecurityField
     @NotEmpty
      private String collectionAccount;
     
     @Transient
     private List<SpeArchives> attachData;
     
     @Transient
     private List<SpeSupplierSettle> settleData;


     public void setContractId(Long contractId){
         this.contractId = contractId;
     }

     public Long getContractId(){
         return contractId;
     }
     
      public Long getSupplierId() {
		return supplierId;
	}

	public void setSupplierId(Long supplierId) {
		this.supplierId = supplierId;
	}

	public void setLevelOneType(String levelOneType){
         this.levelOneType = levelOneType;
     }

     public String getLevelOneType(){
         return levelOneType;
     }

     public void setLevelTwoType(String levelTwoType){
         this.levelTwoType = levelTwoType;
     }

     public String getLevelTwoType(){
         return levelTwoType;
     }

     public void setLevelThreeType(String levelThreeType){
         this.levelThreeType = levelThreeType;
     }

     public String getLevelThreeType(){
         return levelThreeType;
     }
     
     public void setContractName(String contractName){
         this.contractName = contractName;
     }

     public String getContractName(){
         return contractName;
     }

     public void setBr(String br){
         this.br = br;
     }

     public String getBr(){
         return br;
     }

     public void setCi(String ci){
         this.ci = ci;
     }

     public String getCi(){
         return ci;
     }

     public void setAddressMessage(String addressMessage){
         this.addressMessage = addressMessage;
     }

     public String getAddressMessage(){
         return addressMessage;
     }

     public void setSameSettle(String sameSettle){
         this.sameSettle = sameSettle;
     }

     public String getSameSettle(){
         return sameSettle;
     }

     public void setSettleContractName(String settleContractName){
         this.settleContractName = settleContractName;
     }

     public String getSettleContractName(){
         return settleContractName;
     }

     public void setSettleBr(String settleBr){
         this.settleBr = settleBr;
     }

     public String getSettleBr(){
         return settleBr;
     }

     public void setSettleCi(String settleCi){
         this.settleCi = settleCi;
     }

     public String getSettleCi(){
         return settleCi;
     }

     public void setSettleAddressMessage(String settleAddressMessage){
         this.settleAddressMessage = settleAddressMessage;
     }

     public String getSettleAddressMessage(){
         return settleAddressMessage;
     }

     public void setCollectionTermId(Long collectionTermId){
         this.collectionTermId = collectionTermId;
     }

     public Long getCollectionTermId(){
         return collectionTermId;
     }

     public void setSettleTypeCode(String settleTypeCode){
         this.settleTypeCode = settleTypeCode;
     }

     public String getSettleTypeCode(){
         return settleTypeCode;
     }

     public void setCollectionAccount(String collectionAccount){
         this.collectionAccount = collectionAccount;
     }

     public String getCollectionAccount(){
         return collectionAccount;
     }

	public List<SpeArchives> getAttachData() {
		return attachData;
	}

	public void setAttachData(List<SpeArchives> attachData) {
		this.attachData = attachData;
	}

	public List<SpeSupplierSettle> getSettleData() {
		return settleData;
	}

	public void setSettleData(List<SpeSupplierSettle> settleData) {
		this.settleData = settleData;
	}
     
}
