package clb.core.supplier.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotEmpty;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

@ExtensionAttribute(disable = true)
@Table(name = "fms_spe_supplier_line")
public class SpeSupplierLine extends BaseDTO {
	private static final long serialVersionUID = 7260245252614802362L;

	@Id
	@GeneratedValue
	private Long speLineId;

	@NotNull
	private Long supplierId;
	@NotEmpty
	private String addrName;
	private String addr;
	private String contractPerson;

	private String contractNum;

	public Long getSpeLineId() {
		return speLineId;
	}

	public void setSpeLineId(Long speLineId) {
		this.speLineId = speLineId;
	}

	public Long getSupplierId() {
		return supplierId;
	}

	public void setSupplierId(Long supplierId) {
		this.supplierId = supplierId;
	}

	public String getAddrName() {
		return addrName;
	}

	public void setAddrName(String addrName) {
		this.addrName = addrName;
	}

	public String getAddr() {
		return addr;
	}

	public void setAddr(String addr) {
		this.addr = addr;
	}

	public String getContractPerson() {
		return contractPerson;
	}

	public void setContractPerson(String contractPerson) {
		this.contractPerson = contractPerson;
	}

	public String getContractNum() {
		return contractNum;
	}

	public void setContractNum(String contractNum) {
		this.contractNum = contractNum;
	}

}
