package clb.core.whtcustom.dto;

import java.util.List;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.attachment.dto.SysFile;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "fms_wht_custom_reply")
public class WhtCustomReply extends BaseDTO {
     @Id
     @GeneratedValue
      private Long replyId;

      private String accountNum;
     
      private String originalId;

      private String msgType;

      private String replyType;

      private String addContent;

      private String addPictureId;

      private String addVoiceId;

      private String addVideoId;

      private String autoContent;

      private String autoPictureId;

      private String autoVoiceId;

      private String autoVideoId;
      
      private String whtAttachContent;

      private Long programId;

      private Long requestId;
      
      @Transient
  	  private List<WhtCrKeyword> whtCrKeywordList;
      
      @Transient
      private List<WhtCrKeywordRule> whtCrKeywordRuleList;
      
      @Transient
      private Long ruleId;
      
      @Transient
      private String ruleName;
      
      @Transient
      private String replyAllFlag;;
      
      @Transient
      private String content;
      
      @Transient
      private String rulePictureId;
      
      @Transient
      private String ruleVoiceId;
      
      @Transient
      private String ruleVideoId;

      @Transient
      private String rulePictureText;
      
      
      
     public String getWhtAttachContent() {
		return whtAttachContent;
	}

	public void setWhtAttachContent(String whtAttachContent) {
		this.whtAttachContent = whtAttachContent;
	}

	public List<WhtCrKeywordRule> getWhtCrKeywordRuleList() {
		return whtCrKeywordRuleList;
	}

	public void setWhtCrKeywordRuleList(List<WhtCrKeywordRule> whtCrKeywordRuleList) {
		this.whtCrKeywordRuleList = whtCrKeywordRuleList;
	}

	public String getOriginalId() {
		return originalId;
	}

	public void setOriginalId(String originalId) {
		this.originalId = originalId;
	}

	public Long getRuleId() {
		return ruleId;
	}

	public void setRuleId(Long ruleId) {
		this.ruleId = ruleId;
	}

	public String getRuleName() {
		return ruleName;
	}

	public void setRuleName(String ruleName) {
		this.ruleName = ruleName;
	}

	public String getReplyAllFlag() {
		return replyAllFlag;
	}

	public void setReplyAllFlag(String replyAllFlag) {
		this.replyAllFlag = replyAllFlag;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getRulePictureId() {
		return rulePictureId;
	}

	public void setRulePictureId(String rulePictureId) {
		this.rulePictureId = rulePictureId;
	}

	public String getRuleVoiceId() {
		return ruleVoiceId;
	}

	public void setRuleVoiceId(String ruleVoiceId) {
		this.ruleVoiceId = ruleVoiceId;
	}

	public String getRuleVideoId() {
		return ruleVideoId;
	}

	public void setRuleVideoId(String ruleVideoId) {
		this.ruleVideoId = ruleVideoId;
	}

	public String getRulePictureText() {
		return rulePictureText;
	}

	public void setRulePictureText(String rulePictureText) {
		this.rulePictureText = rulePictureText;
	}

	

	public List<WhtCrKeyword> getWhtCrKeywordList() {
		return whtCrKeywordList;
	}

	public void setWhtCrKeywordList(List<WhtCrKeyword> whtCrKeywordList) {
		this.whtCrKeywordList = whtCrKeywordList;
	}

	public void setReplyId(Long replyId){
         this.replyId = replyId;
     }

     public Long getReplyId(){
         return replyId;
     }

     public void setAccountNum(String accountNum){
         this.accountNum = accountNum;
     }

     public String getAccountNum(){
         return accountNum;
     }

     public void setMsgType(String msgType){
         this.msgType = msgType;
     }

     public String getMsgType(){
         return msgType;
     }

     public void setReplyType(String replyType){
         this.replyType = replyType;
     }

     public String getReplyType(){
         return replyType;
     }

     public void setAddContent(String addContent){
         this.addContent = addContent;
     }

     public String getAddContent(){
         return addContent;
     }

     public void setAddPictureId(String addPictureId){
         this.addPictureId = addPictureId;
     }

     public String getAddPictureId(){
         return addPictureId;
     }

     public void setAddVoiceId(String addVoiceId){
         this.addVoiceId = addVoiceId;
     }

     public String getAddVoiceId(){
         return addVoiceId;
     }

     public void setAddVideoId(String addVideoId){
         this.addVideoId = addVideoId;
     }

     public String getAddVideoId(){
         return addVideoId;
     }

     public void setAutoContent(String autoContent){
         this.autoContent = autoContent;
     }

     public String getAutoContent(){
         return autoContent;
     }

     public void setAutoPictureId(String autoPictureId){
         this.autoPictureId = autoPictureId;
     }

     public String getAutoPictureId(){
         return autoPictureId;
     }

     public void setAutoVoiceId(String autoVoiceId){
         this.autoVoiceId = autoVoiceId;
     }

     public String getAutoVoiceId(){
         return autoVoiceId;
     }

     public void setAutoVideoId(String autoVideoId){
         this.autoVideoId = autoVideoId;
     }

     public String getAutoVideoId(){
         return autoVideoId;
     }

     public void setProgramId(Long programId){
         this.programId = programId;
     }

     public Long getProgramId(){
         return programId;
     }

     public void setRequestId(Long requestId){
         this.requestId = requestId;
     }

     public Long getRequestId(){
         return requestId;
     }

     }
