package clb.core.whtcustom.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "fms_wht_cr_keyword")
public class WhtCrKeyword extends BaseDTO {
     @Id
     @GeneratedValue
      private Long keywordId;

     @NotEmpty
      private String keywordValue;

     @NotEmpty
      private Long ruleId;

     @NotEmpty
      private String matchingFlag;

      private Long programId;

      private Long requestId;


     public void setKeywordId(Long keywordId){
         this.keywordId = keywordId;
     }

     public Long getKeywordId(){
         return keywordId;
     }

     public void setKeywordValue(String keywordValue){
         this.keywordValue = keywordValue;
     }

     public String getKeywordValue(){
         return keywordValue;
     }

     public void setRuleId(Long ruleId){
         this.ruleId = ruleId;
     }

     public Long getRuleId(){
         return ruleId;
     }

     public void setMatchingFlag(String matchingFlag){
         this.matchingFlag = matchingFlag;
     }

     public String getMatchingFlag(){
         return matchingFlag;
     }

     public void setProgramId(Long programId){
         this.programId = programId;
     }

     public Long getProgramId(){
         return programId;
     }

     public void setRequestId(Long requestId){
         this.requestId = requestId;
     }

     public Long getRequestId(){
         return requestId;
     }

     }
