package clb.core.whtcustom.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "fms_wht_msg_detail")
public class WhtMsgDetail extends BaseDTO {
     @Id
     @GeneratedValue
      private Long msgDetailId;

     @NotEmpty
      private String templateCode;

     @NotEmpty
      private String templateName;

      private String templateDescribe;

     @NotNull
      private Long templateSerialNum;

      private String relationTemplateCode;

      private String templateEnabled;
      
      @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
      private Date templateDateFrom;
      
      @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
      private Date templateDateTo;

      private String additionalParameter;

      private Long programId;

      private Long requestId;


     public void setMsgDetailId(Long msgDetailId){
         this.msgDetailId = msgDetailId;
     }

     public Long getMsgDetailId(){
         return msgDetailId;
     }

     public void setTemplateCode(String templateCode){
         this.templateCode = templateCode;
     }

     public String getTemplateCode(){
         return templateCode;
     }

     public void setTemplateName(String templateName){
         this.templateName = templateName;
     }

     public String getTemplateName(){
         return templateName;
     }

     public void setTemplateDescribe(String templateDescribe){
         this.templateDescribe = templateDescribe;
     }

     public String getTemplateDescribe(){
         return templateDescribe;
     }

     public void setTemplateSerialNum(Long templateSerialNum){
         this.templateSerialNum = templateSerialNum;
     }

     public Long getTemplateSerialNum(){
         return templateSerialNum;
     }

     public void setRelationTemplateCode(String relationTemplateCode){
         this.relationTemplateCode = relationTemplateCode;
     }

     public String getRelationTemplateCode(){
         return relationTemplateCode;
     }

     public void setTemplateEnabled(String templateEnabled){
         this.templateEnabled = templateEnabled;
     }

     public String getTemplateEnabled(){
         return templateEnabled;
     }

     public void setTemplateDateFrom(Date templateDateFrom){
         this.templateDateFrom = templateDateFrom;
     }

     public Date getTemplateDateFrom(){
         return templateDateFrom;
     }

     public void setTemplateDateTo(Date templateDateTo){
         this.templateDateTo = templateDateTo;
     }

     public Date getTemplateDateTo(){
         return templateDateTo;
     }

     public void setAdditionalParameter(String additionalParameter){
         this.additionalParameter = additionalParameter;
     }

     public String getAdditionalParameter(){
         return additionalParameter;
     }

     public void setProgramId(Long programId){
         this.programId = programId;
     }

     public Long getProgramId(){
         return programId;
     }

     public void setRequestId(Long requestId){
         this.requestId = requestId;
     }

     public Long getRequestId(){
         return requestId;
     }

     }
