package clb.core.whtcustom.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "fms_wht_official_account_cfg")
public class WhtOfficialAccountCfg extends BaseDTO {
     @Id
     @GeneratedValue
      private Long cfgId;

     @NotEmpty
      private String accountName;

     @NotEmpty
      private String originalId;

     @NotEmpty
      private String wechatToken;

     @NotEmpty
      private String backgroundAppid;

     @NotEmpty
      private String backgroundAppSecret;

      private String secretKey;
      
      private String encodingAeskey;
      
      private String accountPattern;

      private String accesstToken;

     @NotEmpty
      private String enableFlag;

     @NotEmpty
      private String accountType;

      private String merchantId;

      private String paymentSecretKey;

      private Long paymentFileId;

      private Date effectiveDateFrom;

      private Date effectiveDateTo;

      private Long programId;

      private Long requestId;
      
      @Transient
	  private String fileName;
      

	public String getEncodingAeskey() {
		return encodingAeskey;
	}

	public void setEncodingAeskey(String encodingAeskey) {
		this.encodingAeskey = encodingAeskey;
	}

	public String getAccountPattern() {
		return accountPattern;
	}

	public void setAccountPattern(String accountPattern) {
		this.accountPattern = accountPattern;
	}

	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public void setCfgId(Long cfgId){
         this.cfgId = cfgId;
     }

     public Long getCfgId(){
         return cfgId;
     }

     public void setAccountName(String accountName){
         this.accountName = accountName;
     }

     public String getAccountName(){
         return accountName;
     }

     public void setOriginalId(String originalId){
         this.originalId = originalId;
     }

     public String getOriginalId(){
         return originalId;
     }

     public void setWechatToken(String wechatToken){
         this.wechatToken = wechatToken;
     }

     public String getWechatToken(){
         return wechatToken;
     }

     public void setBackgroundAppid(String backgroundAppid){
         this.backgroundAppid = backgroundAppid;
     }

     public String getBackgroundAppid(){
         return backgroundAppid;
     }

     public void setBackgroundAppSecret(String backgroundAppSecret){
         this.backgroundAppSecret = backgroundAppSecret;
     }

     public String getBackgroundAppSecret(){
         return backgroundAppSecret;
     }

     public void setSecretKey(String secretKey){
         this.secretKey = secretKey;
     }

     public String getSecretKey(){
         return secretKey;
     }

     public void setAccesstToken(String accesstToken){
         this.accesstToken = accesstToken;
     }

     public String getAccesstToken(){
         return accesstToken;
     }

     public void setEnableFlag(String enableFlag){
         this.enableFlag = enableFlag;
     }

     public String getEnableFlag(){
         return enableFlag;
     }

     public void setAccountType(String accountType){
         this.accountType = accountType;
     }

     public String getAccountType(){
         return accountType;
     }

     public void setMerchantId(String merchantId){
         this.merchantId = merchantId;
     }

     public String getMerchantId(){
         return merchantId;
     }

     public void setPaymentSecretKey(String paymentSecretKey){
         this.paymentSecretKey = paymentSecretKey;
     }

     public String getPaymentSecretKey(){
         return paymentSecretKey;
     }

     public void setPaymentFileId(Long paymentFileId){
         this.paymentFileId = paymentFileId;
     }

     public Long getPaymentFileId(){
         return paymentFileId;
     }

     public void setEffectiveDateFrom(Date effectiveDateFrom){
         this.effectiveDateFrom = effectiveDateFrom;
     }

     public Date getEffectiveDateFrom(){
         return effectiveDateFrom;
     }

     public void setEffectiveDateTo(Date effectiveDateTo){
         this.effectiveDateTo = effectiveDateTo;
     }

     public Date getEffectiveDateTo(){
         return effectiveDateTo;
     }

     public void setProgramId(Long programId){
         this.programId = programId;
     }

     public Long getProgramId(){
         return programId;
     }

     public void setRequestId(Long requestId){
         this.requestId = requestId;
     }

     public Long getRequestId(){
         return requestId;
     }

     }
